"""Models for Agent Proposals bridging suggestions to OKR and Strategy Tasks."""

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import BigInteger, DateTime, Float, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from db.base_class import Base
from db.snowflake_model import SnowflakeIDMixin


class AgentProposal(SnowflakeIDMixin, Base):
    """Proposal record generated by an agent for Founder review and application to real OKRs or Tasks.

    G3 Phase 1E: also doubles as the Learning Candidate record (G1 §9) for
    `proposal_type="learning_candidate"` rows written by the Learning Review
    Worker — deliberately NOT a new table, per G2 §2.5 "reuse a generic
    proposal/governance entity". These rows can never reach
    `AgentProposalService.apply_proposal()`'s auto-apply paths: that method's
    type-dispatch only recognizes `okr_objective`/`strategy_task`/
    `project_cycle` and safely 400s on anything else (see service.py), so a
    learning candidate is structurally inert even if someone tries to apply
    it - it can only be approved/rejected for human review.
    """
    __tablename__ = "agent_proposals"
    __table_args__ = {"schema": "agent_runtime"}

    workspace_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("core.workspaces.id"), index=True, nullable=False)
    company_id: Mapped[Optional[int]] = mapped_column(BigInteger, index=True, nullable=True)
    run_id: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("agent_runtime.agent_runs.id"), nullable=True, index=True)

    proposal_type: Mapped[str] = mapped_column(String(50), nullable=False)  # okr_objective, strategy_task, project_cycle, learning_candidate
    created_by_agent: Mapped[str] = mapped_column(String(100), default="chief_of_staff", nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    payload_jsonb: Mapped[dict] = mapped_column(JSONB, nullable=False)

    status: Mapped[str] = mapped_column(String(50), default="pending", nullable=False)  # pending, approved, rejected, applied
    reviewed_by: Mapped[Optional[int]] = mapped_column(BigInteger, ForeignKey("core.users.id"), nullable=True)
    reviewed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    rejection_reason: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    applied_resource_id: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # G3 Phase 1E (Learning Candidate fields, G1 §9) - all nullable, only
    # populated by learning_candidate rows; ordinary okr/task/project
    # proposals leave these unset.
    domain: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    target_key: Mapped[Optional[str]] = mapped_column(String(150), nullable=True)  # e.g. a skill/capability key this candidate refines
    diff_jsonb: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)  # proposed before/after change, if any
    confidence: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    evidence_ids_jsonb: Mapped[Optional[list]] = mapped_column(JSONB, nullable=True)
    source_outcome_id: Mapped[Optional[int]] = mapped_column(BigInteger, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )
