apiVersion: v1
kind: Service
metadata:
  name: opensandbox-server
  namespace: cosa-sandbox
  labels:
    app.kubernetes.io/name: opensandbox-server
    app.kubernetes.io/part-of: cosa-os
    app.kubernetes.io/component: execution-runtime
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: opensandbox-server
