"""Unit tests cho các bộ phân tích định lượng Marketing (100% Python Standard Library)."""

from __future__ import annotations

from agent.marketing.analyzers import (
    AEOReadinessCalculator,
    BrandVoiceAnalyzer,
    LinkedInPostLinter,
    PaletteContrastValidator,
)


def test_brand_voice_analyzer_flesch_and_cliches():
    text = (
        "Our team decided to revolutionize the software landscape with a seamless experience. "
        "We built a tool that saves hours of tedious work every single week. "
        "Reports are generated by the server automatically."
    )
    report = BrandVoiceAnalyzer.analyze(text)

    assert report.word_count > 20
    assert report.sentence_count >= 2
    assert report.flesch_reading_ease > 0.0
    # Clichés found: revolutionize, seamless
    assert "revolutionize" in report.flagged_cliches
    assert "seamless" in report.flagged_cliches
    assert report.passive_sentence_count >= 1
    assert report.passive_ratio > 0.0

    dict_repr = report.to_dict()
    assert "flesch_reading_ease" in dict_repr
    assert "formality_score" in dict_repr


def test_brand_voice_analyzer_empty():
    report = BrandVoiceAnalyzer.analyze("")
    assert report.word_count == 0
    assert report.flesch_reading_ease == 100.0
    assert len(report.recommendations) > 0


def test_aeo_readiness_calculator():
    text = (
        "# How to Scale B2B SaaS Growth in 2026?\n\n"
        "In 2026, we tested 15 growth loops across 500 active users and achieved a 35% conversion lift. "
        "Our data shows that reducing signup friction saves $12,000 monthly in acquisition waste.\n\n"
        "## What is the Core Metric?\n"
        "According to source [1], customer lifetime value increased by 42%.\n"
        "Schema: FAQPage and Article."
    )
    report = AEOReadinessCalculator.calculate(text)

    assert report.overall_score > 60.0
    assert report.grade in ("A", "B")
    assert report.fact_count >= 4
    assert report.factual_density_per_1000 > 20.0
    assert report.has_fact_first_lede is True
    assert report.question_header_count >= 2
    assert report.schema_ready is True
    assert report.dimension_scores["experience"] > 0.0
    assert report.dimension_scores["trustworthiness"] > 0.0

    dict_repr = report.to_dict()
    assert dict_repr["grade"] in ("A", "B")


def test_palette_contrast_validator_wcag():
    # Test Black on White: 21:1 ratio
    res_black_white = PaletteContrastValidator.validate("#000000", "#FFFFFF")
    assert res_black_white.contrast_ratio >= 20.0
    assert res_black_white.normal_text_aa is True
    assert res_black_white.normal_text_aaa is True
    assert res_black_white.large_text_aa is True
    assert res_black_white.is_accessible is True

    # Test Light Gray on White: Low contrast
    res_low = PaletteContrastValidator.validate("#CCCCCC", "#FFFFFF")
    assert res_low.contrast_ratio < 2.0
    assert res_low.normal_text_aa is False
    assert res_low.is_accessible is False

    # Test Palette Derivation
    derived = PaletteContrastValidator.derive_palette("#2563EB")
    assert "primary" in derived
    assert "accent" in derived
    assert "background" in derived
    assert "surface" in derived
    assert "text_primary" in derived

    # Check contrast of derived text on bg
    bg_check = PaletteContrastValidator.validate(derived["text_primary"], derived["background"])
    assert bg_check.normal_text_aa is True


def test_linkedin_post_linter_blocking_unicode():
    # Post with Unicode pseudo-bold (Mathematical bold: 𝗧𝗵𝗶𝘀 𝗶𝘀 𝗯𝗼𝗹𝗱)
    bad_post = "𝗧𝗵𝗶𝘀 𝗶𝘀 𝗯𝗼𝗹𝗱 text that should be rejected by the accessibility gate."
    report = LinkedInPostLinter.lint(bad_post)

    assert report.is_valid is False
    blocking_codes = [f.code for f in report.findings if f.severity == "BLOCKING"]
    assert "BLOCKING_UNICODE_PSEUDO_BOLD" in blocking_codes


def test_linkedin_post_linter_clean_post():
    good_post = (
        "Here is a counter-intuitive insight on B2B pricing.\n\n"
        "Most founders underprice their software by 50%.\n"
        "When you price too low, enterprise buyers perceive risk rather than value.\n\n"
        "Three ways to fix this:\n"
        "1. Anchor against high-friction alternative costs\n"
        "2. Introduce an annual commit discount\n"
        "3. Protect gross margins early\n\n"
        "#saas #pricing #b2b"
    )
    report = LinkedInPostLinter.lint(good_post)

    assert report.is_valid is True
    assert report.has_early_fold_break is True
    assert report.hook_length < 140
    assert report.hashtag_count == 3
    assert report.link_count == 0
    assert len([f for f in report.findings if f.severity == "BLOCKING"]) == 0


def test_linkedin_post_linter_2026_heuristics():
    # 1. Question first hook warning
    q_post = "Tại sao 90% startup thất bại trong năm đầu tiên?\n\nNguyên nhân chính là thiếu PMF."
    q_report = LinkedInPostLinter.lint(q_post)
    codes = [f.code for f in q_report.findings]
    assert "QUESTION_FIRST_HOOK" in codes

    # 2. Number first hook positive info
    num_post = "14,200 USD là số tiền chúng tôi tiết kiệm được sau khi chuyển hạ tầng.\n\nChi tiết bài học:"
    num_report = LinkedInPostLinter.lint(num_post)
    num_codes = [f.code for f in num_report.findings]
    assert "NUMBER_FIRST_HOOK" in num_codes

    # 3. Comment-gate bait warning
    bait_post = "Bí kíp gọi vốn vòng Seed cho Founder.\n\nHãy comment bên dưới để nhận tài liệu nhé!"
    bait_report = LinkedInPostLinter.lint(bait_post)
    bait_codes = [f.code for f in bait_report.findings]
    assert "COMMENT_GATE_BAIT" in bait_codes

    # 4. Reveal bridge used
    bridge_post = "Chúng tôi đã thử nghiệm chiến lược mới trong 3 tháng.\n\nKết quả là? Doanh số tăng vọt."
    bridge_report = LinkedInPostLinter.lint(bridge_post)
    bridge_codes = [f.code for f in bridge_report.findings]
    assert "REVEAL_BRIDGE_USED" in bridge_codes


def test_brand_voice_analyzer_2026_humanizer_v3():
    # 1. Staccato / forced burstiness detection
    staccato_text = "Nhanh. Gọn. Tối ưu. Chúng tôi đã xây dựng hệ thống mới chỉ trong ba ngày."
    report = BrandVoiceAnalyzer.analyze(staccato_text)
    assert report.forced_burstiness_detected is True
    assert len(report.staccato_sequences) > 0

    # 2. Paragraph AI density
    dense_text = "It is crucial to have a comprehensive and robust framework to leverage AI."
    dense_report = BrandVoiceAnalyzer.analyze(dense_text)
    assert dense_report.max_paragraph_ai_density >= 3

    # 3. False vulnerability recommendation
    vuln_text = "Thú thật là chúng tôi từng mắc sai lầm nghiêm trọng khi chọn phân khúc khách hàng."
    vuln_report = BrandVoiceAnalyzer.analyze(vuln_text)
    assert any("thú thật là" in r.lower() or "false vulnerability" in r.lower() for r in vuln_report.recommendations)

