/**
 * GENERATED FILE — DO NOT MODIFY DIRECTLY
 * Source: shared/contracts/mvp-surface.json · Generator: scripts/gen-mvp-contracts.mjs
 * To update: edit shared/contracts/mvp-surface.json and run `node scripts/gen-mvp-contracts.mjs`
 */

export type MvpPlane = "company" | "platform" | "agent" | "localWorker";
export type MvpSourceKind = "company_db" | "agent_db" | "object_store" | "control_plane" | "external_connector";

export interface MvpCapabilityMetadata {
  readonly id: string;
  readonly enabled: boolean;
  readonly owner: string;
  readonly plane: MvpPlane;
  readonly method: string;
  readonly path: string;
  readonly schema: string;
  readonly sourceKind: MvpSourceKind;
  readonly requiresWorkspace: boolean;
  readonly frontendSymbol: string;
  readonly backendTest: string;
  readonly flutterTest: string;
  readonly integrationTest: string;
}

export const MVP_CAPABILITIES: readonly MvpCapabilityMetadata[] = [
  {
    id: "automation.approval.decide",
    enabled: false,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/automation/approvals/:approvalId/decision",
    schema: "automation.approval.decide.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationRunInspectorService.decideApproval",
    backendTest: "services/company/operations/tests/automation-outcome.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_run_inspector_view_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.definition.configure",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PATCH",
    path: "/operations/automation/definitions/:definitionId/configuration",
    schema: "automation.definition.configure.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationLibraryService.configureDefinition",
    backendTest: "services/company/operations/tests/automation-definition.handler.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_configuration_view_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.definition.get",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/automation/definitions/:definitionId",
    schema: "automation.definition.get.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationLibraryService.getDefinition",
    backendTest: "services/company/operations/tests/automation-definition.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_service_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.definition.list",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/automation/definitions",
    schema: "automation.definition.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationLibraryService.listDefinitions",
    backendTest: "services/company/operations/tests/automation-definition.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_service_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.definition.publish",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/automation/definitions/:definitionId/revisions",
    schema: "automation.definition.publish.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationLibraryService.publishRevision",
    backendTest: "services/company/operations/tests/automation-definition.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_library_controller_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.definition.suspend",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/automation/definitions/:definitionId/suspension",
    schema: "automation.definition.suspend.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationLibraryService.suspendDefinition",
    backendTest: "services/company/operations/tests/automation-definition.handler.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_library_controller_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.invocation.cancel",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/automation/invocations/:invocationId/cancellation",
    schema: "automation.invocation.cancel.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationRunInspectorService.cancelInvocation",
    backendTest: "services/company/operations/tests/automation-invocation.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_run_inspector_view_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.invocation.create",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/automation/definitions/:definitionId/invocations",
    schema: "automation.invocation.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationLibraryService.createInvocation",
    backendTest: "services/company/operations/tests/automation-invocation.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_library_controller_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.invocation.get",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/automation/invocations/:invocationId",
    schema: "automation.invocation.get.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationRunInspectorService.getInvocation",
    backendTest: "services/company/operations/tests/automation-invocation.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_run_inspector_view_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.needs_you.list",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/automation/needs-you",
    schema: "automation.needs_you.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationRunInspectorService.listNeedsYou",
    backendTest: "services/company/operations/tests/automation-inspector.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_run_inspector_view_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "automation.run.inspector.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/automation/invocations/:invocationId/inspector",
    schema: "automation.run.inspector.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "AutomationRunInspectorService.getRunInspector",
    backendTest: "services/company/operations/tests/automation-inspector.service.test.ts",
    flutterTest: "frontend/test/modules/automation/automation_run_inspector_view_test.dart",
    integrationTest: "tests/e2e/test_automation_mvp_cross_plane.py",
  },
  {
    id: "commercial.contact.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/contacts",
    schema: "commercial.contact.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "CrmService.createContact",
    backendTest: "services/company/commercial/tests/contact.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.interview.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/interviews",
    schema: "commercial.interview.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "CrmService.createInterview",
    backendTest: "services/company/operations/tests/founder-trial-interview-evidence.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.interview.submit_evidence",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/interviews/:id/submit-evidence",
    schema: "commercial.interview.submit_evidence.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialCommands.submitInterviewEvidence",
    backendTest: "services/company/operations/tests/founder-trial-interview-evidence.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.lead.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/leads",
    schema: "commercial.lead.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "CrmService.createLead",
    backendTest: "services/company/commercial/tests/lead.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "finance.budget_summary.read",
    enabled: true,
    owner: "company-finance",
    plane: "company",
    method: "GET",
    path: "/finance/budget-summary",
    schema: "finance.budget_summary.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FinanceService.fetchBudgetSummary",
    backendTest: "services/company/finance-legal/tests/budget-summary.test.ts",
    flutterTest: "frontend/test/modules/finance/finance_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "finance.snapshot.latest",
    enabled: true,
    owner: "company-finance",
    plane: "company",
    method: "GET",
    path: "/finance/snapshots/latest",
    schema: "finance.snapshot.latest.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FinanceService.fetchLatestSnapshot",
    backendTest: "services/company/finance-legal/tests/finance-snapshot.test.ts",
    flutterTest: "frontend/test/modules/finance/finance_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "marketing.campaign.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/marketing/campaigns",
    schema: "marketing.campaign.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "MarketingMvpService.createCampaign",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.campaign.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/marketing/campaigns",
    schema: "marketing.campaign.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "MarketingMvpService.listCampaigns",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.experiment.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/marketing/experiments",
    schema: "marketing.experiment.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "MarketingMvpService.createExperiment",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.experiment.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/marketing/experiments",
    schema: "marketing.experiment.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "MarketingMvpService.listExperiments",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "settings.capability_manifest.read",
    enabled: true,
    owner: "control-plane",
    plane: "platform",
    method: "GET",
    path: "/platform/workspaces/:workspaceId/capability-manifest",
    schema: "settings.capability_manifest.read.v1",
    sourceKind: "control_plane",
    requiresWorkspace: true,
    frontendSymbol: "WorkspaceCapabilityManifestService.fetch",
    backendTest: "services/cosa/tests/workspace-capability-manifest.test.ts",
    flutterTest: "frontend/test/core/services/workspace_capability_manifest_controller_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.assumption.create",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/assumptions",
    schema: "strategy.assumption.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialCommands.createAssumption",
    backendTest: "services/company/operations/tests/founder-trial-board.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_board_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.assumptions.ranked",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/strategy/projects/:projectId/ranked-assumptions",
    schema: "strategy.assumptions.ranked.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialBoardService.fetchRankedAssumptions",
    backendTest: "services/company/operations/tests/founder-trial-board.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_board_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.decision.create",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/decision-records",
    schema: "strategy.decision.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialCommands.createDecision",
    backendTest: "services/company/operations/tests/founder-trial-board.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.evidence.review",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/evidence/:id/review",
    schema: "strategy.evidence.review.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialCommands.reviewEvidence",
    backendTest: "services/company/operations/tests/evidence-lifecycle.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.founder_brief.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/founder-brief",
    schema: "strategy.founder_brief.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderBriefService.fetch",
    backendTest: "services/company/operations/tests/founder-brief.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_brief_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.founder_trial.board.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/founder-trial-board",
    schema: "strategy.founder_trial.board.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialBoardService.fetch",
    backendTest: "services/company/operations/tests/founder-trial-board.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_board_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.founder_trial.experiment.create",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/founder-trial/experiments",
    schema: "strategy.founder_trial.experiment.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialCommands.createExperiment",
    backendTest: "services/company/operations/tests/founder-trial-experiment.service.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_board_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "strategy.operating_cycle.resize",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PATCH",
    path: "/operations/projects/:projectId/operating-cycle",
    schema: "strategy.operating_cycle.resize.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    frontendSymbol: "FounderTrialCommands.resizeCycle",
    backendTest: "services/company/operations/tests/active-cycle-resize.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
] as const;

export const MVP_CAPABILITY_BY_ID = new Map<string, MvpCapabilityMetadata>(
  MVP_CAPABILITIES.map((c) => [c.id, c])
);
