/**
 * GENERATED FILE — DO NOT MODIFY DIRECTLY
 * Source: shared/contracts/mvp-surface.json · Generator: scripts/gen-mvp-contracts.mjs
 * To update: edit shared/contracts/mvp-surface.json and run `node scripts/gen-mvp-contracts.mjs`
 */

export type MvpPlane = "company" | "platform" | "agent" | "localWorker";
export type MvpSourceKind = "company_db" | "agent_db" | "object_store" | "control_plane" | "external_connector";

export interface MvpCapabilityMetadata {
  readonly id: string;
  readonly enabled: boolean;
  readonly owner: string;
  readonly plane: MvpPlane;
  readonly method: string;
  readonly path: string;
  readonly schema: string;
  readonly sourceKind: MvpSourceKind;
  readonly requiresWorkspace: boolean;
  readonly requiresProject: boolean;
  readonly frontendSymbol: string;
  readonly backendTest: string;
  readonly flutterTest: string;
  readonly integrationTest: string;
}

export const MVP_CAPABILITIES: readonly MvpCapabilityMetadata[] = [
  {
    id: "agent.conversation.create",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "POST",
    path: "/agent/projects/:projectId/conversations",
    schema: "agent.conversation.create.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "FounderHubService.createConversation",
    backendTest: "tests/apps/cosa/api/test_project_scoped_conversation_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "agent.conversation.message.create",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "POST",
    path: "/agent/projects/:projectId/conversations/:conversationId/messages",
    schema: "agent.conversation.message.create.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "FounderHubService.sendMessage",
    backendTest: "tests/apps/cosa/api/test_project_scoped_conversation_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "agent.conversation.read",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "GET",
    path: "/agent/projects/:projectId/conversations/:conversationId",
    schema: "agent.conversation.read.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "FounderHubService.getConversation",
    backendTest: "tests/apps/cosa/api/test_project_scoped_conversation_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "agent.conversation.update",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "PATCH",
    path: "/agent/projects/:projectId/conversations/:conversationId",
    schema: "agent.conversation.update.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "FounderHubService.updateConversation",
    backendTest: "tests/apps/cosa/api/test_project_scoped_conversation_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "agent.knowledge.project.search",
    enabled: true,
    owner: "cosa-knowledge",
    plane: "agent",
    method: "POST",
    path: "/agent/knowledge/projects/:projectId/search",
    schema: "agent.knowledge.project.search.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectKnowledgeService.search",
    backendTest: "tests/apps/cosa/api/test_project_knowledge_routes.py",
    flutterTest: "frontend/test/modules/knowledge/project_knowledge_service_test.dart",
    integrationTest: "tests/integration/test_startup_core_knowledge_e2e.py",
  },
  {
    id: "agent.project_activity.detail",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "GET",
    path: "/agent/projects/:projectId/activity/:runId",
    schema: "agent.project_activity.detail.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectActivityService.detail",
    backendTest: "tests/apps/cosa/api/test_project_activity_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "agent.project_activity.read",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "GET",
    path: "/agent/projects/:projectId/activity",
    schema: "agent.project_activity.read.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectActivityService.list",
    backendTest: "tests/apps/cosa/api/test_project_activity_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "agent.project_activity.stream",
    enabled: true,
    owner: "cosa-agent-hub",
    plane: "agent",
    method: "GET",
    path: "/agent/projects/:projectId/activity/stream",
    schema: "agent.project_activity.stream.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectActivityService.stream",
    backendTest: "tests/apps/cosa/api/test_project_activity_routes.py",
    flutterTest: "frontend/test/modules/hologram_hub/founder_hub_project_scope_test.dart",
    integrationTest: "tests/e2e/test_project_scoped_founder_hub.py",
  },
  {
    id: "commercial.contact.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/contacts",
    schema: "commercial.contact.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "CrmService.createContact",
    backendTest: "services/company/commercial/tests/contact.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.interview.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/interviews",
    schema: "commercial.interview.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "CrmService.createInterview",
    backendTest: "services/company/operations/tests/founder-trial-interview-evidence.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.interview.submit_evidence",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/interviews/:id/submit-evidence",
    schema: "commercial.interview.submit_evidence.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FounderTrialCommands.submitInterviewEvidence",
    backendTest: "services/company/operations/tests/founder-trial-interview-evidence.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.lead.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/leads",
    schema: "commercial.lead.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "CrmService.createLead",
    backendTest: "services/company/commercial/tests/lead.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.project_crm.field_definitions.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/projects/:projectId/crm/field-definitions",
    schema: "commercial.project_crm.field_definitions.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.createFieldDefinition",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.field_definitions.patch",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "PATCH",
    path: "/commercial/projects/:projectId/crm/field-definitions/:fieldId",
    schema: "commercial.project_crm.field_definitions.patch.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.patchFieldDefinition",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.field_definitions.retire",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/projects/:projectId/crm/field-definitions/:fieldId/retire",
    schema: "commercial.project_crm.field_definitions.retire.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.retireFieldDefinition",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.lead_sources.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/projects/:projectId/crm/lead-sources",
    schema: "commercial.project_crm.lead_sources.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.createLeadSource",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.lead_sources.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/projects/:projectId/crm/lead-sources",
    schema: "commercial.project_crm.lead_sources.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.listLeadSources",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.leads.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/projects/:projectId/crm/leads",
    schema: "commercial.project_crm.leads.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.createLead",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.leads.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/projects/:projectId/crm/leads",
    schema: "commercial.project_crm.leads.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.listLeads",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "commercial.project_crm.schema.get",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/projects/:projectId/crm/schema",
    schema: "commercial.project_crm.schema.get.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectCrmService.getSchema",
    backendTest: "services/company/commercial/tests/project-crm.handler.test.ts",
    flutterTest: "frontend/test/modules/commercial/project_crm_service_test.dart",
    integrationTest: "tests/e2e/test_project_crm_sales_support_knowledge.py",
  },
  {
    id: "finance.budget_summary.read",
    enabled: true,
    owner: "company-finance",
    plane: "company",
    method: "GET",
    path: "/finance/budget-summary",
    schema: "finance.budget_summary.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FinanceService.fetchBudgetSummary",
    backendTest: "services/company/finance-legal/tests/budget-summary.test.ts",
    flutterTest: "frontend/test/modules/finance/finance_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "finance.snapshot.latest",
    enabled: true,
    owner: "company-finance",
    plane: "company",
    method: "GET",
    path: "/finance/snapshots/latest",
    schema: "finance.snapshot.latest.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FinanceService.fetchLatestSnapshot",
    backendTest: "services/company/finance-legal/tests/finance-snapshot.test.ts",
    flutterTest: "frontend/test/modules/finance/finance_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "identity.agent_capability_grant.create",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "POST",
    path: "/identity/agent-capability-grants",
    schema: "identity.agent_capability_grant.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "PermissionsService.createAgentCapabilityGrant",
    backendTest: "services/company/identity/tests/agent-authorization.test.ts",
    flutterTest: "frontend/test/modules/settings/permissions_service_test.dart",
    integrationTest: "tests/e2e/test_cross_plane_smoke.py",
  },
  {
    id: "identity.agent_capability_grant.revoke",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "POST",
    path: "/identity/agent-capability-grants/:grantId/revoke",
    schema: "identity.agent_capability_grant.revoke.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "PermissionsService.revokeAgentCapabilityGrant",
    backendTest: "services/company/identity/tests/agent-authorization.test.ts",
    flutterTest: "frontend/test/modules/settings/permissions_service_test.dart",
    integrationTest: "tests/e2e/test_cross_plane_smoke.py",
  },
  {
    id: "identity.permissions.read",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "GET",
    path: "/identity/permissions",
    schema: "identity.permissions.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "PermissionsService.getPermissions",
    backendTest: "services/company/identity/tests/founder-authorization.test.ts",
    flutterTest: "frontend/test/modules/settings/permissions_service_test.dart",
    integrationTest: "tests/e2e/test_cross_plane_smoke.py",
  },
  {
    id: "identity.permissions.simulate",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "POST",
    path: "/identity/permissions/simulate",
    schema: "identity.permissions.simulate.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "PermissionsService.simulatePermissions",
    backendTest: "services/company/identity/tests/founder-authorization.test.ts",
    flutterTest: "frontend/test/modules/settings/permissions_service_test.dart",
    integrationTest: "tests/e2e/test_cross_plane_smoke.py",
  },
  {
    id: "identity.permissions.write",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "PUT",
    path: "/identity/permissions",
    schema: "identity.permissions.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "PermissionsService.updatePermissions",
    backendTest: "services/company/identity/tests/founder-authorization.test.ts",
    flutterTest: "frontend/test/modules/settings/permissions_service_test.dart",
    integrationTest: "tests/e2e/test_cross_plane_smoke.py",
  },
  {
    id: "identity.workspace.lifecycle.events",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "GET",
    path: "/identity/workspaces/:workspaceId/lifecycle/events",
    schema: "identity.workspace.lifecycle.events.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "LifecycleService.getHistory",
    backendTest: "services/company/identity/tests/workspace-lifecycle.service.test.ts",
    flutterTest: "frontend/test/core/lifecycle/lifecycle_service_test.dart",
    integrationTest: "",
  },
  {
    id: "identity.workspace.lifecycle.transition",
    enabled: true,
    owner: "company-identity",
    plane: "company",
    method: "PATCH",
    path: "/identity/workspaces/:workspaceId/lifecycle",
    schema: "identity.workspace.lifecycle.transition.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "LifecycleService.transition",
    backendTest: "services/company/identity/tests/workspace-lifecycle.service.test.ts",
    flutterTest: "frontend/test/core/lifecycle/lifecycle_service_test.dart",
    integrationTest: "",
  },
  {
    id: "marketing.campaign.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/marketing/campaigns",
    schema: "marketing.campaign.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.createCampaign",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.campaign.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/marketing/campaigns",
    schema: "marketing.campaign.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.listCampaigns",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.experiment.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/marketing/experiments",
    schema: "marketing.experiment.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.createExperiment",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.experiment.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/marketing/experiments",
    schema: "marketing.experiment.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.listExperiments",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "operations.execution_cycle_view.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/execution-cycle-view",
    schema: "operations.execution_cycle_view.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "TwelveWeekService.getCycleTimeline",
    backendTest: "services/company/operations/tests/mvp-okr-twelve-week.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.executive_board.stage_suggestion",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/executive-board/stage-suggestion",
    schema: "operations.executive_board.stage_suggestion.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveBoardStageSuggestionService.get",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.executive_board.workspace_role.activate",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/workspaces/:workspaceId/executive-roles/:roleKey/activate",
    schema: "operations.executive_board.workspace_role.activate.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "ExecutiveAdvisoryBoardService.activateRole",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.executive_board.workspace_role.disable",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/workspaces/:workspaceId/executive-roles/:roleKey/disable",
    schema: "operations.executive_board.workspace_role.disable.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "ExecutiveAdvisoryBoardService.disableRole",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.founder_asset.command",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/founder/assets/commands",
    schema: "operations.founder_asset.command.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FounderAssetService.commandAsset",
    backendTest: "services/company/operations/tests/founder-asset-authoring.service.test.ts",
    flutterTest: "frontend/test/modules/skills/founder_asset_service_test.dart",
    integrationTest: "tests/apps/cosa/events/test_founder_asset_events.py",
  },
  {
    id: "operations.founder_asset.library",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/founder-assets",
    schema: "operations.founder_asset.library.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FounderAssetService.listLibrary",
    backendTest: "services/company/operations/tests/founder-asset-query.handler.test.ts",
    flutterTest: "frontend/test/modules/skills/founder_asset_service_test.dart",
    integrationTest: "tests/apps/cosa/events/test_founder_asset_events.py",
  },
  {
    id: "operations.okr.cycle.create",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/okr-cycles",
    schema: "operations.okr.cycle.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.createOkrCycle",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.cycle.list",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/okr-cycles",
    schema: "operations.okr.cycle.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.getOkrCycles",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.generate_weekly_cycle",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/objectives/:objectiveId/generate-weekly-cycle",
    schema: "operations.okr.generate_weekly_cycle.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrWeeklyGeneratorService.generate",
    backendTest: "services/company/operations/tests/okr-weekly-generator.service.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.key_result.checkin",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/key-results/:keyResultId/checkin",
    schema: "operations.okr.key_result.checkin.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.checkinKeyResult",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.key_result.delete",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "DELETE",
    path: "/operations/key-results/:keyResultId",
    schema: "operations.okr.key_result.delete.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.deleteKeyResult",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.key_result.update",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PUT",
    path: "/operations/key-results/:keyResultId",
    schema: "operations.okr.key_result.update.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.updateKeyResult",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.objective.delete",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "DELETE",
    path: "/operations/objectives/:objectiveId",
    schema: "operations.okr.objective.delete.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.deleteObjective",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.objective.publish",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/objectives/:objectiveId/publish",
    schema: "operations.okr.objective.publish.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.publishObjective",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.okr.objective.update",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PUT",
    path: "/operations/objectives/:objectiveId",
    schema: "operations.okr.objective.update.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "OkrService.updateObjective",
    backendTest: "services/company/operations/tests/okr.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.project.lifecycle.events",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/lifecycle/events",
    schema: "operations.project.lifecycle.events.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "LifecycleService.getHistory",
    backendTest: "services/company/operations/tests/project-lifecycle.service.test.ts",
    flutterTest: "frontend/test/core/lifecycle/lifecycle_service_test.dart",
    integrationTest: "",
  },
  {
    id: "operations.project.lifecycle.transition",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PATCH",
    path: "/operations/projects/:projectId/lifecycle",
    schema: "operations.project.lifecycle.transition.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "LifecycleService.transition",
    backendTest: "services/company/operations/tests/project-lifecycle.service.test.ts",
    flutterTest: "frontend/test/core/lifecycle/lifecycle_service_test.dart",
    integrationTest: "",
  },
  {
    id: "operations.task.delete",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "DELETE",
    path: "/operations/tasks/:id",
    schema: "operations.task.delete.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "TaskService.deleteTask",
    backendTest: "services/company/operations/tests/task.service.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "operations.twelve_week.cycle.list",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/workspaces/:workspaceId/cycles",
    schema: "operations.twelve_week.cycle.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "TwelveWeekService.getTwelveWeekCycles",
    backendTest: "services/company/operations/tests/twelve-week-year.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "project.agent_deployments.create",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/agent-deployments",
    schema: "project.agent_deployments.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectAgentDeploymentService.deploy",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "",
    integrationTest: "",
  },
  {
    id: "project.commitment.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/commitments",
    schema: "project.commitment.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createCommitment",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.cycle.week.advance",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PATCH",
    path: "/operations/projects/:projectId/operating-loop/cycles/:cycleId/week",
    schema: "project.cycle.week.advance.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.advanceCycleWeek",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.cycle.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/cycles",
    schema: "project.cycle.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createCycle",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.deliberations.cancel",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/deliberations/:deliberationId/cancel",
    schema: "project.deliberations.cancel.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.cancelDeliberation",
    backendTest: "services/company/operations/tests/executive-deliberation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.deliberations.decision",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/deliberations/:deliberationId/decision",
    schema: "project.deliberations.decision.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.appendDecision",
    backendTest: "services/company/operations/tests/executive-deliberation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.deliberations.draft",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/deliberations/draft",
    schema: "project.deliberations.draft.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.createDraft",
    backendTest: "services/company/operations/tests/executive-deliberation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.deliberations.frame",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/deliberations/:deliberationId/frame",
    schema: "project.deliberations.frame.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.frameDeliberation",
    backendTest: "services/company/operations/tests/executive-deliberation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.deliberations.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/deliberations/:deliberationId",
    schema: "project.deliberations.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.getDeliberation",
    backendTest: "services/company/operations/tests/executive-deliberation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.executive_roles.activate",
    enabled: false,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/executive-roles/:roleKey/activate",
    schema: "project.executive_roles.activate.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.activateRole",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.executive_roles.disable",
    enabled: false,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/executive-roles/:roleKey/disable",
    schema: "project.executive_roles.disable.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.disableRole",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.executive_roles.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/executive-roles",
    schema: "project.executive_roles.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.fetchRoles",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.executive_roles.select_preset",
    enabled: false,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/executive-preset",
    schema: "project.executive_roles.select_preset.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ExecutiveAdvisoryBoardService.selectPreset",
    backendTest: "services/company/operations/tests/executive-role-activation.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/executive_advisory_board_service_test.dart",
    integrationTest: "tests/e2e/test_executive_advisory_board.py",
  },
  {
    id: "project.initiative.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/initiatives",
    schema: "project.initiative.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createInitiative",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.key_result.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/key-results",
    schema: "project.key_result.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createKeyResult",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.loop.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/operating-loop",
    schema: "project.loop.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopService.fetch",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.okr.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/objectives",
    schema: "project.okr.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createObjective",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.startup_team.activate",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/startup-team/:profileKey/activate",
    schema: "project.startup_team.activate.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectStartupTeamService.activate",
    backendTest: "services/company/operations/tests/project-startup-team.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/project_startup_team_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.startup_team.pause",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/startup-team/:profileKey/pause",
    schema: "project.startup_team.pause.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectStartupTeamService.pause",
    backendTest: "services/company/operations/tests/project-startup-team.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/project_startup_team_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.startup_team.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/startup-team",
    schema: "project.startup_team.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectStartupTeamService.fetch",
    backendTest: "services/company/operations/tests/project-startup-team.handler.test.ts",
    flutterTest: "frontend/test/modules/hologram_hub/services/project_startup_team_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.task.status.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "PATCH",
    path: "/operations/projects/:projectId/operating-loop/tasks/:taskId/status",
    schema: "project.task.status.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.advanceTaskStatus",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.task.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/tasks",
    schema: "project.task.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createTask",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.week.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/weeks",
    schema: "project.week.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createWeek",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "settings.capability_manifest.read",
    enabled: true,
    owner: "control-plane",
    plane: "platform",
    method: "GET",
    path: "/platform/workspaces/:workspaceId/capability-manifest",
    schema: "settings.capability_manifest.read.v1",
    sourceKind: "control_plane",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "WorkspaceCapabilityManifestService.fetch",
    backendTest: "services/cosa/tests/workspace-capability-manifest.test.ts",
    flutterTest: "frontend/test/core/services/workspace_capability_manifest_controller_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
] as const;

export const MVP_CAPABILITY_BY_ID = new Map<string, MvpCapabilityMetadata>(
  MVP_CAPABILITIES.map((c) => [c.id, c])
);
