/**
 * GENERATED FILE — DO NOT MODIFY DIRECTLY
 * Source: shared/contracts/mvp-surface.json · Generator: scripts/gen-mvp-contracts.mjs
 * To update: edit shared/contracts/mvp-surface.json and run `node scripts/gen-mvp-contracts.mjs`
 */

export type MvpPlane = "company" | "platform" | "agent" | "localWorker";
export type MvpSourceKind = "company_db" | "agent_db" | "object_store" | "control_plane" | "external_connector";

export interface MvpCapabilityMetadata {
  readonly id: string;
  readonly enabled: boolean;
  readonly owner: string;
  readonly plane: MvpPlane;
  readonly method: string;
  readonly path: string;
  readonly schema: string;
  readonly sourceKind: MvpSourceKind;
  readonly requiresWorkspace: boolean;
  readonly requiresProject: boolean;
  readonly frontendSymbol: string;
  readonly backendTest: string;
  readonly flutterTest: string;
  readonly integrationTest: string;
}

export const MVP_CAPABILITIES: readonly MvpCapabilityMetadata[] = [
  {
    id: "agent.knowledge.project.search",
    enabled: true,
    owner: "cosa-knowledge",
    plane: "agent",
    method: "POST",
    path: "/agent/knowledge/projects/:projectId/search",
    schema: "agent.knowledge.project.search.v1",
    sourceKind: "agent_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectKnowledgeService.search",
    backendTest: "tests/apps/cosa/api/test_project_knowledge_routes.py",
    flutterTest: "frontend/test/modules/knowledge/project_knowledge_service_test.dart",
    integrationTest: "tests/integration/test_startup_core_knowledge_e2e.py",
  },
  {
    id: "commercial.contact.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/contacts",
    schema: "commercial.contact.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "CrmService.createContact",
    backendTest: "services/company/commercial/tests/contact.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.interview.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/interviews",
    schema: "commercial.interview.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "CrmService.createInterview",
    backendTest: "services/company/operations/tests/founder-trial-interview-evidence.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.interview.submit_evidence",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/operations/strategy/interviews/:id/submit-evidence",
    schema: "commercial.interview.submit_evidence.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FounderTrialCommands.submitInterviewEvidence",
    backendTest: "services/company/operations/tests/founder-trial-interview-evidence.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "commercial.lead.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/leads",
    schema: "commercial.lead.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "CrmService.createLead",
    backendTest: "services/company/commercial/tests/lead.test.ts",
    flutterTest: "frontend/test/modules/strategy/founder_trial_full_loop_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "finance.budget_summary.read",
    enabled: true,
    owner: "company-finance",
    plane: "company",
    method: "GET",
    path: "/finance/budget-summary",
    schema: "finance.budget_summary.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FinanceService.fetchBudgetSummary",
    backendTest: "services/company/finance-legal/tests/budget-summary.test.ts",
    flutterTest: "frontend/test/modules/finance/finance_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "finance.snapshot.latest",
    enabled: true,
    owner: "company-finance",
    plane: "company",
    method: "GET",
    path: "/finance/snapshots/latest",
    schema: "finance.snapshot.latest.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "FinanceService.fetchLatestSnapshot",
    backendTest: "services/company/finance-legal/tests/finance-snapshot.test.ts",
    flutterTest: "frontend/test/modules/finance/finance_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "marketing.campaign.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/marketing/campaigns",
    schema: "marketing.campaign.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.createCampaign",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.campaign.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/marketing/campaigns",
    schema: "marketing.campaign.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.listCampaigns",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.experiment.create",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "POST",
    path: "/commercial/marketing/experiments",
    schema: "marketing.experiment.create.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.createExperiment",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "marketing.experiment.list",
    enabled: true,
    owner: "company-commercial",
    plane: "company",
    method: "GET",
    path: "/commercial/marketing/experiments",
    schema: "marketing.experiment.list.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "MarketingMvpService.listExperiments",
    backendTest: "services/company/commercial/tests/mvp-marketing.test.ts",
    flutterTest: "frontend/test/marketing_mvp_service_test.dart",
    integrationTest: "tests/e2e/test_mvp_marketing_http.py",
  },
  {
    id: "project.commitment.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/commitments",
    schema: "project.commitment.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createCommitment",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.cycle.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/cycles",
    schema: "project.cycle.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createCycle",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.loop.read",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "GET",
    path: "/operations/projects/:projectId/operating-loop",
    schema: "project.loop.read.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopService.fetch",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.okr.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/objectives",
    schema: "project.okr.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createObjective",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.task.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/tasks",
    schema: "project.task.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createTask",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "project.week.write",
    enabled: true,
    owner: "company-operations",
    plane: "company",
    method: "POST",
    path: "/operations/projects/:projectId/operating-loop/weeks",
    schema: "project.week.write.v1",
    sourceKind: "company_db",
    requiresWorkspace: true,
    requiresProject: true,
    frontendSymbol: "ProjectOperatingLoopCommands.createWeek",
    backendTest: "services/company/operations/tests/project-operating-loop.handler.test.ts",
    flutterTest: "frontend/test/modules/projects/project_operating_loop_service_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
  {
    id: "settings.capability_manifest.read",
    enabled: true,
    owner: "control-plane",
    plane: "platform",
    method: "GET",
    path: "/platform/workspaces/:workspaceId/capability-manifest",
    schema: "settings.capability_manifest.read.v1",
    sourceKind: "control_plane",
    requiresWorkspace: true,
    requiresProject: false,
    frontendSymbol: "WorkspaceCapabilityManifestService.fetch",
    backendTest: "services/cosa/tests/workspace-capability-manifest.test.ts",
    flutterTest: "frontend/test/core/services/workspace_capability_manifest_controller_test.dart",
    integrationTest: "tests/e2e/test_founder_trial_http.py",
  },
] as const;

export const MVP_CAPABILITY_BY_ID = new Map<string, MvpCapabilityMetadata>(
  MVP_CAPABILITIES.map((c) => [c.id, c])
);
