ALTER TABLE IF EXISTS cosa.users ADD COLUMN IF NOT EXISTS is_platform_admin BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS cosa.users ADD COLUMN IF NOT EXISTS platform_role_id TEXT;
ALTER TABLE IF EXISTS cosa.users ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE IF EXISTS cosa.users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE IF EXISTS cosa.users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE IF EXISTS cosa.users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS cosa.companies ADD COLUMN IF NOT EXISTS industry TEXT;
ALTER TABLE IF EXISTS cosa.companies ADD COLUMN IF NOT EXISTS country_code TEXT DEFAULT 'VN';
ALTER TABLE IF EXISTS cosa.companies ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE IF EXISTS cosa.companies ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE IF EXISTS cosa.companies ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE IF EXISTS cosa.companies ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS cosa.licenses ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
