from unittest.mock import MagicMock
from datetime import datetime
import pytest

from core.snowflake import generate_snowflake_id
from platform_core.license.handoff_service import HandoffService
from platform_core.license.models import Handoff, WorkReview, Blocker
from platform_core.license.routers.handoffs_router import (
    HandoffCreateRequest,
    accept_handoff_endpoint,
    complete_handoff_endpoint,
    create_handoff_endpoint,
)
from founder_os.tasks.models import Task, TaskDependency
from founder_os.outcomes.models import Outcome, Artifact


def test_handoff_lifecycle():
    db = MagicMock()
    ws_id = generate_snowflake_id()

    handoff = HandoffService.create_handoff(
        db=db,
        workspace_id=ws_id,
        from_function="MARKETING",
        to_function="SALES",
        handoff_type="TRANSFER_ARTIFACT",
        requested_action="Qualify 10 new beta leads generated by campaign",
        artifact_refs=["https://s3/leads.csv"],
    )

    assert handoff.from_function == "MARKETING"
    assert handoff.to_function == "SALES"
    assert handoff.status == "PENDING"
    assert db.commit.called

    # Accept handoff
    db.query.return_value.filter.return_value.first.return_value = handoff
    accepted = HandoffService.accept_handoff(db, ws_id, handoff.id)
    assert accepted.status == "ACCEPTED"


def test_handoff_rejects_completion_before_acceptance():
    db = MagicMock()
    handoff = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="PENDING")
    db.query.return_value.filter.return_value.first.return_value = handoff

    with pytest.raises(ValueError, match="PENDING -> COMPLETED"):
        HandoffService.complete_handoff(db, 1, 123)


def test_handoff_creation_reuses_an_existing_idempotency_key():
    db = MagicMock()
    existing = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="PENDING")
    db.query.return_value.filter.return_value.first.return_value = existing

    result = HandoffService.create_handoff(
        db=db,
        workspace_id=1,
        from_function="SALES",
        to_function="FINANCE",
        handoff_type="HANDOFF_TO_NEXT_FUNCTION",
        requested_action="Record receivable",
        idempotency_key="sales-opportunity-won:123",
    )

    assert result is existing
    db.add.assert_not_called()


def test_finance_handoff_accept_requires_finance_feature(monkeypatch):
    db = MagicMock()
    member = MagicMock(workspace_id=1)
    handoff = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="PENDING")
    db.query.return_value.filter.return_value.first.return_value = handoff
    require_flag = MagicMock()
    monkeypatch.setattr("platform_core.license.routers.handoffs_router.require_flag", require_flag)
    monkeypatch.setattr("platform_core.license.routers.handoffs_router.HandoffService.accept_handoff", MagicMock(return_value=handoff))

    accept_handoff_endpoint(123, 1, member, db)

    require_flag.assert_called_once()


def test_create_handoff_uses_requested_target_function_without_an_id(monkeypatch):
    db = MagicMock()
    member = MagicMock(workspace_id=1)
    created = Handoff(id=123, workspace_id=1, from_function="MARKETING", to_function="SALES", handoff_type="TRANSFER_ARTIFACT", requested_action="Qualify lead", status="PENDING", created_at=datetime.utcnow())
    monkeypatch.setattr("platform_core.license.routers.handoffs_router.HandoffService.create_handoff", MagicMock(return_value=created))

    response = create_handoff_endpoint(
        HandoffCreateRequest(from_function="MARKETING", to_function="SALES", handoff_type="TRANSFER_ARTIFACT", requested_action="Qualify lead"),
        1,
        member,
        db,
    )

    assert response["id"] == "123"


def test_finance_handoff_complete_requires_finance_feature(monkeypatch):
    db = MagicMock()
    member = MagicMock(workspace_id=1)
    handoff = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="ACCEPTED")
    db.query.return_value.filter.return_value.first.return_value = handoff
    require_flag = MagicMock()
    monkeypatch.setattr("platform_core.license.routers.handoffs_router.require_flag", require_flag)
    monkeypatch.setattr("platform_core.license.routers.handoffs_router.HandoffService.complete_handoff", MagicMock(return_value=handoff))

    complete_handoff_endpoint(123, 1, member, db)

    require_flag.assert_called_once()


def test_work_inspector_data_aggregation():
    db = MagicMock()
    ws_id = generate_snowflake_id()
    task_id = generate_snowflake_id()
    outcome_id = generate_snowflake_id()

    task = Task(id=task_id, workspace_id=ws_id, title="Deploy Landing Page", function="TECH", status="in_progress", execution_mode="AGENT", created_at=datetime.utcnow())
    outcome = Outcome(id=outcome_id, workspace_id=ws_id, task_id=task_id, title="Landing Outcome", desired_result="Live URL", status="running", rework_count=0)

    db.query.return_value.filter.return_value.first.side_effect = [task, outcome]
    db.query.return_value.filter.return_value.all.return_value = []
    db.query.return_value.filter.return_value.order_by.return_value.all.return_value = []

    inspector = HandoffService.get_work_inspector(db, ws_id, task_id)
    assert inspector["task"]["id"] == str(task_id)
    assert inspector["outcome"]["title"] == "Landing Outcome"
    assert "dependencies" in inspector
    assert "reviews" in inspector
    assert "handoffs" in inspector
    assert "blockers" in inspector
    assert "artifacts" in inspector


def _get_db():
    from sqlalchemy import create_engine
    from sqlalchemy.ext.compiler import compiles
    from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
    from sqlalchemy.orm import sessionmaker
    from sqlalchemy.pool import StaticPool
    from db.base import Base
    from db.session import SessionLocal, engine as main_engine

    @compiles(JSONB, "sqlite")
    def compile_jsonb_sqlite(type_, compiler, **kw):
        return "TEXT"

    @compiles(TSVECTOR, "sqlite")
    def compile_tsvector_sqlite(type_, compiler, **kw):
        return "TEXT"

    try:
        from pgvector.sqlalchemy import Vector
        @compiles(Vector, "sqlite")
        def compile_vector_sqlite(type_, compiler, **kw):
            return "TEXT"
    except ImportError:
        pass

    try:
        with main_engine.connect() as conn:
            pass
        return SessionLocal()
    except Exception:
        mem_engine = create_engine(
            "sqlite:///:memory:",
            connect_args={"check_same_thread": False},
            poolclass=StaticPool,
        )
        mem_engine = mem_engine.execution_options(schema_translate_map={"agent_runtime": None, "integrations": None})
        Base.metadata.create_all(mem_engine)
        return sessionmaker(bind=mem_engine)()


def test_get_work_inspector_includes_run_steps_trace():
    from core.snowflake import generate_snowflake_id
    from founder_os.outcomes.models import Outcome, OutcomeRun, RunStep
    from founder_os.tasks.models import Task
    from platform_core.auth.models import User, Workspace
    from platform_core.license.handoff_service import HandoffService

    db = _get_db()
    try:
        user_id = generate_snowflake_id()
        workspace_id = generate_snowflake_id()
        db.add(User(id=user_id, email=f"inspector-{user_id}@example.invalid"))
        db.add(Workspace(id=workspace_id, name=f"Inspector {workspace_id}"))
        db.flush()
        task = Task(
            id=generate_snowflake_id(),
            workspace_id=workspace_id,
            title="Deploy core components",
            function="TECH",
            execution_mode="AGENT",
            status="in_progress",
        )
        db.add(task)
        db.flush()
        outcome = Outcome(
            id=generate_snowflake_id(),
            workspace_id=workspace_id,
            task_id=task.id,
            function="TECH",
            title="Outcome: Deploy",
            desired_result="Working deployment",
            requested_by=user_id,
            status="running",
        )
        db.add(outcome)
        db.flush()
        outcome_run = OutcomeRun(
            id=generate_snowflake_id(), outcome_id=outcome.id, status="running"
        )
        db.add(outcome_run)
        db.flush()
        step = RunStep(
            id=generate_snowflake_id(),
            run_id=outcome_run.id,
            type="agent",
            status="pending",
            assigned_agent_profile_id="tech",
        )
        db.add(step)
        db.commit()

        inspector = HandoffService.get_work_inspector(
            db=db, workspace_id=workspace_id, task_id=task.id
        )

        assert "run_steps" in inspector
        assert len(inspector["run_steps"]) == 1
        assert inspector["run_steps"][0]["assigned_agent_profile_id"] == "tech"
        assert inspector["run_steps"][0]["status"] == "pending"
    finally:
        db.rollback()
        db.close()
