from enum import Enum


class ValidationWorkflowState(str, Enum):
    UNASSESSED = "UNASSESSED"
    DATA_COLLECTION = "DATA_COLLECTION"
    ASSUMPTION_MAPPED = "ASSUMPTION_MAPPED"
    RISK_PRIORITIZED = "RISK_PRIORITIZED"
    HYPOTHESIS_READY = "HYPOTHESIS_READY"
    EXPERIMENT_READY = "EXPERIMENT_READY"
    TESTING = "TESTING"
    EVIDENCE_READY = "EVIDENCE_READY"
    REVIEW_READY = "REVIEW_READY"
    DECIDED = "DECIDED"
    PIVOT_REQUIRED = "PIVOT_REQUIRED"


class EpistemicType(str, Enum):
    FACT = "FACT"
    BELIEF = "BELIEF"
    ASSUMPTION = "ASSUMPTION"
    HYPOTHESIS = "HYPOTHESIS"
    EVIDENCE = "EVIDENCE"
    DECISION = "DECISION"


class ClaimConfirmationStatus(str, Enum):
    DRAFT = "DRAFT"
    AI_INFERRED = "AI_INFERRED"
    FOUNDER_CONFIRMED = "FOUNDER_CONFIRMED"
    FOUNDER_EDITED = "FOUNDER_EDITED"
    EVIDENCE_SUPPORTED = "EVIDENCE_SUPPORTED"
    CHALLENGED = "CHALLENGED"
    SUPERSEDED = "SUPERSEDED"


class DimensionName(str, Enum):
    FOUNDER_FIT = "FOUNDER_FIT"
    CUSTOMER = "CUSTOMER"
    PROBLEM = "PROBLEM"
    SOLUTION = "SOLUTION"
    PRICING = "PRICING"
    CHANNEL = "CHANNEL"
    REVENUE = "REVENUE"
    GROWTH = "GROWTH"
    TECHNICAL = "TECHNICAL"
    OPERATIONAL = "OPERATIONAL"
    LEGAL = "LEGAL"
    FINANCE = "FINANCE"


class DimensionStateEnum(str, Enum):
    UNKNOWN = "UNKNOWN"
    BELIEF = "BELIEF"
    ASSUMPTION = "ASSUMPTION"
    HYPOTHESIS = "HYPOTHESIS"
    TESTING = "TESTING"
    SUPPORTED = "SUPPORTED"
    CHALLENGED = "CHALLENGED"
    VALIDATED = "VALIDATED"
    INVALIDATED = "INVALIDATED"


class FeasibilityPillar(str, Enum):
    DESIRABILITY = "DESIRABILITY"
    VIABILITY = "VIABILITY"
    FEASIBILITY = "FEASIBILITY"
    FOUNDER_FIT = "FOUNDER_FIT"


class AssumptionCategory(str, Enum):
    FOUNDER = "FOUNDER"
    CUSTOMER = "CUSTOMER"
    PROBLEM = "PROBLEM"
    SOLUTION = "SOLUTION"
    PRICING = "PRICING"
    CHANNEL = "CHANNEL"
    REVENUE = "REVENUE"
    GROWTH = "GROWTH"
    TECHNICAL = "TECHNICAL"
    OPERATIONAL = "OPERATIONAL"
    LEGAL = "LEGAL"
    FINANCE = "FINANCE"


class AssumptionStatus(str, Enum):
    UNKNOWN = "UNKNOWN"
    UNTESTED = "UNTESTED"
    HYPOTHESIZED = "HYPOTHESIZED"
    TESTING = "TESTING"
    SUPPORTED = "SUPPORTED"
    CHALLENGED = "CHALLENGED"
    VALIDATED = "VALIDATED"
    INVALIDATED = "INVALIDATED"


class ExperimentType(str, Enum):
    CUSTOMER_INTERVIEW = "CUSTOMER_INTERVIEW"
    LANDING_PAGE = "LANDING_PAGE"
    FAKE_DOOR = "FAKE_DOOR"
    WAITLIST = "WAITLIST"
    PREORDER = "PREORDER"
    PAID_OFFER = "PAID_OFFER"
    CONCIERGE_MVP = "CONCIERGE_MVP"
    PROTOTYPE_TEST = "PROTOTYPE_TEST"
    A_B_TEST = "A_B_TEST"
    SALES_CALL = "SALES_CALL"
    CHANNEL_TEST = "CHANNEL_TEST"
    PRICING_TEST = "PRICING_TEST"


class EvidenceType(str, Enum):
    REAL_PAYMENT = "REAL_PAYMENT"
    DEPOSIT_PREORDER = "DEPOSIT_PREORDER"
    ACTION_COMMITMENT = "ACTION_COMMITMENT"
    OBSERVED_BEHAVIOR = "OBSERVED_BEHAVIOR"
    TIME_INVESTMENT = "TIME_INVESTMENT"
    CUSTOMER_INTERVIEW = "CUSTOMER_INTERVIEW"
    SURVEY = "SURVEY"
    SOCIAL_PRAISE = "SOCIAL_PRAISE"
    DESK_RESEARCH = "DESK_RESEARCH"
    AI_ANALYSIS = "AI_ANALYSIS"
    FOUNDER_BELIEF = "FOUNDER_BELIEF"


class QuestionTypeEnum(str, Enum):
    PAST_BEHAVIOR = "PAST_BEHAVIOR"
    CURRENT_BEHAVIOR = "CURRENT_BEHAVIOR"
    OPINION = "OPINION"
    HYPOTHETICAL_FUTURE = "HYPOTHETICAL_FUTURE"
    LEADING = "LEADING"
    SOLUTION_PITCH = "SOLUTION_PITCH"
    COST_DISCOVERY = "COST_DISCOVERY"
    ALTERNATIVE_DISCOVERY = "ALTERNATIVE_DISCOVERY"


class BuyingSignalLevelEnum(str, Enum):
    LEVEL_1_INTEREST = "LEVEL_1_INTEREST"
    LEVEL_2_PAIN = "LEVEL_2_PAIN"
    LEVEL_3_WTP = "LEVEL_3_WTP"
    LEVEL_4_ACTION = "LEVEL_4_ACTION"
    LEVEL_5_STRONG_PROOF = "LEVEL_5_STRONG_PROOF"


class CustomerRoleEnum(str, Enum):
    USER = "USER"
    BUYER = "BUYER"
    DECISION_MAKER = "DECISION_MAKER"
    INFLUENCER = "INFLUENCER"


class ICPLifecycleState(str, Enum):
    HYPOTHESIZED = "HYPOTHESIZED"
    EVIDENCE_BUILDING = "EVIDENCE_BUILDING"
    EVIDENCE_BACKED = "EVIDENCE_BACKED"
    CHALLENGED = "CHALLENGED"
    SUPERSEDED = "SUPERSEDED"


class AutopsyClusterType(str, Enum):
    PATTERN = "PATTERN"
    NICHE = "NICHE"
    SHOCK = "SHOCK"


class ProblemValidationResultEnum(str, Enum):
    PROBLEM_NOT_ESTABLISHED = "PROBLEM_NOT_ESTABLISHED"
    PROBLEM_WEAKLY_SUPPORTED = "PROBLEM_WEAKLY_SUPPORTED"
    PROBLEM_SUPPORTED = "PROBLEM_SUPPORTED"
    PROBLEM_STRONGLY_SUPPORTED = "PROBLEM_STRONGLY_SUPPORTED"


class EvidenceRelationship(str, Enum):
    SUPPORTS = "SUPPORTS"
    CHALLENGES = "CHALLENGES"
    COMPLICATES = "COMPLICATES"
    NEUTRAL = "NEUTRAL"


class ReviewProviderType(str, Enum):
    AI = "AI"
    HUMAN_INTERNAL = "HUMAN_INTERNAL"
    HUMAN_EXPERT = "HUMAN_EXPERT"
    MENTOR = "MENTOR"
    ADVISOR = "ADVISOR"
    PANEL = "PANEL"


class ReviewVerdict(str, Enum):
    PASS = "PASS"
    CONDITIONAL_PASS = "CONDITIONAL_PASS"
    TEST_MORE = "TEST_MORE"
    CHALLENGED = "CHALLENGED"
    FAIL = "FAIL"


class FounderDecisionEnum(str, Enum):
    PROCEED = "PROCEED"
    TEST_MORE = "TEST_MORE"
    PIVOT = "PIVOT"
    PAUSE = "PAUSE"
    STOP = "STOP"


# -------------------------------------------------------------------------
# DATABASE TABLES (F1.md §50 - §52)
# -------------------------------------------------------------------------
