# core/validation/models.py aggregates all Startup/Validation domain models,
# which now live in per-concept files (enums.py, session.py, evidence_chain.py,
# customer_discovery.py). Kept as a single import surface for app/db/base.py and
# the app/founder_os/validation backward-compat shim.
from core.validation.enums import (
    ValidationWorkflowState,
    EpistemicType,
    ClaimConfirmationStatus,
    DimensionName,
    DimensionStateEnum,
    FeasibilityPillar,
    AssumptionCategory,
    AssumptionStatus,
    ExperimentType,
    EvidenceType,
    QuestionTypeEnum,
    BuyingSignalLevelEnum,
    CustomerRoleEnum,
    ICPLifecycleState,
    AutopsyClusterType,
    ProblemValidationResultEnum,
    EvidenceRelationship,
    ReviewProviderType,
    ReviewVerdict,
    FounderDecisionEnum,
)
from core.validation.session import (
    ValidationSession,
    StructuredClaim,
    FieldRevision,
    DimensionState,
    ProjectStageHistory,
)
from core.validation.evidence_chain import (
    ValidationAssumption,
    ValidationHypothesis,
    ValidationExperiment,
    ValidationEvidence,
    ValidationReview,
    ValidationDecision,
)
from core.validation.customer_discovery import (
    CustomerContact,
    CustomerInterviewSession,
    VerbatimQuote,
    ProblemSeverityScorecard,
    PainPattern,
    EarlyAdopterCandidate,
)

__all__ = [
    "ValidationWorkflowState",
    "EpistemicType",
    "ClaimConfirmationStatus",
    "DimensionName",
    "DimensionStateEnum",
    "FeasibilityPillar",
    "AssumptionCategory",
    "AssumptionStatus",
    "ExperimentType",
    "EvidenceType",
    "QuestionTypeEnum",
    "BuyingSignalLevelEnum",
    "CustomerRoleEnum",
    "ICPLifecycleState",
    "AutopsyClusterType",
    "ProblemValidationResultEnum",
    "EvidenceRelationship",
    "ReviewProviderType",
    "ReviewVerdict",
    "FounderDecisionEnum",
    "ValidationSession",
    "StructuredClaim",
    "FieldRevision",
    "DimensionState",
    "ProjectStageHistory",
    "ValidationAssumption",
    "ValidationHypothesis",
    "ValidationExperiment",
    "ValidationEvidence",
    "ValidationReview",
    "ValidationDecision",
    "CustomerContact",
    "CustomerInterviewSession",
    "VerbatimQuote",
    "ProblemSeverityScorecard",
    "PainPattern",
    "EarlyAdopterCandidate",
]
