from unittest.mock import MagicMock
from datetime import datetime
import pytest

from app.core.snowflake import generate_snowflake_id
from app.modules.company_runtime.handoff_service import HandoffService
from app.modules.company_runtime.models import Handoff, WorkReview, Blocker
from app.modules.company_runtime.routers.handoffs_router import accept_handoff_endpoint
from app.modules.tasks.models import Task, TaskDependency
from app.modules.outcomes.models import Outcome, Artifact


def test_handoff_lifecycle():
    db = MagicMock()
    ws_id = generate_snowflake_id()

    handoff = HandoffService.create_handoff(
        db=db,
        workspace_id=ws_id,
        from_function="MARKETING",
        to_function="SALES",
        handoff_type="TRANSFER_ARTIFACT",
        requested_action="Qualify 10 new beta leads generated by campaign",
        artifact_refs=["https://s3/leads.csv"],
    )

    assert handoff.from_function == "MARKETING"
    assert handoff.to_function == "SALES"
    assert handoff.status == "PENDING"
    assert db.commit.called

    # Accept handoff
    db.query.return_value.filter.return_value.first.return_value = handoff
    accepted = HandoffService.accept_handoff(db, ws_id, handoff.id)
    assert accepted.status == "ACCEPTED"


def test_handoff_rejects_completion_before_acceptance():
    db = MagicMock()
    handoff = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="PENDING")
    db.query.return_value.filter.return_value.first.return_value = handoff

    with pytest.raises(ValueError, match="PENDING -> COMPLETED"):
        HandoffService.complete_handoff(db, 1, 123)


def test_handoff_creation_reuses_an_existing_idempotency_key():
    db = MagicMock()
    existing = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="PENDING")
    db.query.return_value.filter.return_value.first.return_value = existing

    result = HandoffService.create_handoff(
        db=db,
        workspace_id=1,
        from_function="SALES",
        to_function="FINANCE",
        handoff_type="HANDOFF_TO_NEXT_FUNCTION",
        requested_action="Record receivable",
        idempotency_key="sales-opportunity-won:123",
    )

    assert result is existing
    db.add.assert_not_called()


def test_finance_handoff_accept_requires_finance_feature(monkeypatch):
    db = MagicMock()
    member = MagicMock(workspace_id=1)
    handoff = Handoff(id=123, workspace_id=1, from_function="SALES", to_function="FINANCE", handoff_type="HANDOFF_TO_NEXT_FUNCTION", requested_action="Record receivable", status="PENDING")
    db.query.return_value.filter.return_value.first.return_value = handoff
    require_flag = MagicMock()
    monkeypatch.setattr("app.modules.company_runtime.routers.handoffs_router.require_flag", require_flag)
    monkeypatch.setattr("app.modules.company_runtime.routers.handoffs_router.HandoffService.accept_handoff", MagicMock(return_value=handoff))

    accept_handoff_endpoint(123, 1, member, db)

    require_flag.assert_called_once()


def test_work_inspector_data_aggregation():
    db = MagicMock()
    ws_id = generate_snowflake_id()
    task_id = generate_snowflake_id()
    outcome_id = generate_snowflake_id()

    task = Task(id=task_id, workspace_id=ws_id, title="Deploy Landing Page", function="TECH", status="in_progress", execution_mode="AGENT", created_at=datetime.utcnow())
    outcome = Outcome(id=outcome_id, workspace_id=ws_id, task_id=task_id, title="Landing Outcome", desired_result="Live URL", status="running", rework_count=0)

    db.query.return_value.filter.return_value.first.side_effect = [task, outcome]
    db.query.return_value.filter.return_value.all.return_value = []
    db.query.return_value.filter.return_value.order_by.return_value.all.return_value = []

    inspector = HandoffService.get_work_inspector(db, ws_id, task_id)
    assert inspector["task"]["id"] == str(task_id)
    assert inspector["outcome"]["title"] == "Landing Outcome"
    assert "dependencies" in inspector
    assert "reviews" in inspector
    assert "handoffs" in inspector
    assert "blockers" in inspector
    assert "artifacts" in inspector
