// GENERATED FILE — DO NOT MODIFY DIRECTLY
// Source: shared/contracts/mvp-surface.json · Generator: scripts/gen-mvp-contracts.mjs
// To update: edit shared/contracts/mvp-surface.json and run `node scripts/gen-mvp-contracts.mjs`

import 'api_result.dart';

enum MvpEndpoint {
  agentConversationCreate(
    id: 'agent.conversation.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/projects/:projectId/conversations',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentConversationMessageCreate(
    id: 'agent.conversation.message.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/projects/:projectId/conversations/:conversationId/messages',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentConversationRead(
    id: 'agent.conversation.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/conversations/:conversationId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentConversationUpdate(
    id: 'agent.conversation.update',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'PATCH',
    path: '/agent/projects/:projectId/conversations/:conversationId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentKnowledgeProjectSearch(
    id: 'agent.knowledge.project.search',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/knowledge/projects/:projectId/search',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentProjectActivityDetail(
    id: 'agent.project_activity.detail',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/activity/:runId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentProjectActivityRead(
    id: 'agent.project_activity.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/activity',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentProjectActivityStream(
    id: 'agent.project_activity.stream',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/activity/stream',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialAccountCreate(
    id: 'commercial.account.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/accounts',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialAccountsList(
    id: 'commercial.accounts.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/workspaces/:workspaceId/accounts',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialContactCreate(
    id: 'commercial.contact.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/contacts',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialContactsList(
    id: 'commercial.contacts.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/workspaces/:workspaceId/contacts',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialCustomerCreate(
    id: 'commercial.customer.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/customers',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialCustomersList(
    id: 'commercial.customers.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/workspaces/:workspaceId/customers',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialInterviewCreate(
    id: 'commercial.interview.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/interviews',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialInterviewSubmitEvidence(
    id: 'commercial.interview.submit_evidence',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/interviews/:id/submit-evidence',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialLeadCreate(
    id: 'commercial.lead.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/leads',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialLeadStageUpdate(
    id: 'commercial.lead.stage.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/leads/:id/stage',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialLeadsList(
    id: 'commercial.leads.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/leads',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialOpportunitiesList(
    id: 'commercial.opportunities.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/workspaces/:workspaceId/opportunities',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialOpportunityCreate(
    id: 'commercial.opportunity.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/opportunities',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialOpportunityStageUpdate(
    id: 'commercial.opportunity.stage.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/opportunities/:id/stage',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialProjectCrmFieldDefinitionsCreate(
    id: 'commercial.project_crm.field_definitions.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/field-definitions',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmFieldDefinitionsPatch(
    id: 'commercial.project_crm.field_definitions.patch',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/commercial/projects/:projectId/crm/field-definitions/:fieldId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmFieldDefinitionsRetire(
    id: 'commercial.project_crm.field_definitions.retire',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/field-definitions/:fieldId/retire',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadSourcesCreate(
    id: 'commercial.project_crm.lead_sources.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/lead-sources',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadSourcesList(
    id: 'commercial.project_crm.lead_sources.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/projects/:projectId/crm/lead-sources',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadsCreate(
    id: 'commercial.project_crm.leads.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/leads',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadsList(
    id: 'commercial.project_crm.leads.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/projects/:projectId/crm/leads',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmSchemaGet(
    id: 'commercial.project_crm.schema.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/projects/:projectId/crm/schema',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  financeAccountingDocumentsList(
    id: 'finance.accounting_documents.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance/accounting-documents',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  financeAccountingPeriodsList(
    id: 'finance.accounting_periods.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance-legal/accounting-periods',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  financeBudgetSummaryRead(
    id: 'finance.budget_summary.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance/budget-summary',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  financeExceptionsList(
    id: 'finance.exceptions.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance-legal/workspaces/:workspaceId/exceptions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  financeSnapshotLatest(
    id: 'finance.snapshot.latest',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance-legal/snapshots/latest',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  financeTransactionsList(
    id: 'finance.transactions.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance-legal/transactions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityAgentCapabilityGrantCreate(
    id: 'identity.agent_capability_grant.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/agent-capability-grants',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityAgentCapabilityGrantRevoke(
    id: 'identity.agent_capability_grant.revoke',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/agent-capability-grants/:grantId/revoke',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityPermissionsRead(
    id: 'identity.permissions.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/identity/permissions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityPermissionsSimulate(
    id: 'identity.permissions.simulate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/permissions/simulate',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityPermissionsWrite(
    id: 'identity.permissions.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/identity/permissions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityWorkspaceLifecycleEvents(
    id: 'identity.workspace.lifecycle.events',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/identity/workspaces/:workspaceId/lifecycle/events',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityWorkspaceLifecycleTransition(
    id: 'identity.workspace.lifecycle.transition',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/identity/workspaces/:workspaceId/lifecycle',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingCampaignCreate(
    id: 'marketing.campaign.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/marketing/campaigns',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingCampaignList(
    id: 'marketing.campaign.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/campaigns',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingExperimentCreate(
    id: 'marketing.experiment.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/marketing/experiments',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingExperimentList(
    id: 'marketing.experiment.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/experiments',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsExecutionCycleViewRead(
    id: 'operations.execution_cycle_view.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/execution-cycle-view',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsExecutiveBoardBootstrapP0Core(
    id: 'operations.executive_board.bootstrap_p0_core',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-board/bootstrap-p0-core',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  operationsExecutiveBoardStageSuggestion(
    id: 'operations.executive_board.stage_suggestion',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/executive-board/stage-suggestion',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  operationsExecutiveBoardWorkspaceRoleActivate(
    id: 'operations.executive_board.workspace_role.activate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/workspaces/:workspaceId/executive-roles/:roleKey/activate',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsExecutiveBoardWorkspaceRoleDisable(
    id: 'operations.executive_board.workspace_role.disable',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/workspaces/:workspaceId/executive-roles/:roleKey/disable',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsFounderAssetCommand(
    id: 'operations.founder_asset.command',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/founder/assets/commands',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsFounderAssetLibrary(
    id: 'operations.founder_asset.library',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/founder-assets',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrCycleCreate(
    id: 'operations.okr.cycle.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/okr-cycles',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrCycleList(
    id: 'operations.okr.cycle.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/okr-cycles',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrGenerateWeeklyCycle(
    id: 'operations.okr.generate_weekly_cycle',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives/:objectiveId/generate-weekly-cycle',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrKeyResultCheckin(
    id: 'operations.okr.key_result.checkin',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/key-results/:keyResultId/checkin',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrKeyResultCreate(
    id: 'operations.okr.key_result.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives/:objectiveId/key-results',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrKeyResultDelete(
    id: 'operations.okr.key_result.delete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'DELETE',
    path: '/operations/key-results/:keyResultId',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrKeyResultList(
    id: 'operations.okr.key_result.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/key-results',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrKeyResultUpdate(
    id: 'operations.okr.key_result.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/key-results/:keyResultId',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrObjectiveCreate(
    id: 'operations.okr.objective.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrObjectiveDelete(
    id: 'operations.okr.objective.delete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'DELETE',
    path: '/operations/objectives/:objectiveId',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrObjectiveList(
    id: 'operations.okr.objective.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/objectives',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrObjectivePublish(
    id: 'operations.okr.objective.publish',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives/:objectiveId/publish',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsOkrObjectiveUpdate(
    id: 'operations.okr.objective.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/objectives/:objectiveId',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsProjectLifecycleEvents(
    id: 'operations.project.lifecycle.events',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/lifecycle/events',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  operationsProjectLifecycleTransition(
    id: 'operations.project.lifecycle.transition',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/operations/projects/:projectId/lifecycle',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  operationsTaskDelete(
    id: 'operations.task.delete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'DELETE',
    path: '/operations/tasks/:id',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsTwelveWeekCycleList(
    id: 'operations.twelve_week.cycle.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/workspaces/:workspaceId/cycles',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  organizationAiWorkforceCreate(
    id: 'organization.ai_workforce.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/organizations/:organizationId/ai-workforce',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  organizationOverviewRead(
    id: 'organization.overview.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/organizations/:organizationId/overview',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  organizationWorkforceList(
    id: 'organization.workforce.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/organizations/:organizationId/workforce',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  projectAgentDeploymentsCreate(
    id: 'project.agent_deployments.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/agent-deployments',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectCommitmentWrite(
    id: 'project.commitment.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/commitments',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectCycleWeekAdvance(
    id: 'project.cycle.week.advance',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/operations/projects/:projectId/operating-loop/cycles/:cycleId/week',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectCycleWrite(
    id: 'project.cycle.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/cycles',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsCancel(
    id: 'project.deliberations.cancel',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/:deliberationId/cancel',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsDecision(
    id: 'project.deliberations.decision',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/:deliberationId/decision',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsDraft(
    id: 'project.deliberations.draft',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/draft',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsFrame(
    id: 'project.deliberations.frame',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/:deliberationId/frame',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsRead(
    id: 'project.deliberations.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/deliberations/:deliberationId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesActivate(
    id: 'project.executive_roles.activate',
    enabled: false,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-roles/:roleKey/activate',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesDisable(
    id: 'project.executive_roles.disable',
    enabled: false,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-roles/:roleKey/disable',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesRead(
    id: 'project.executive_roles.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/executive-roles',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesSelectPreset(
    id: 'project.executive_roles.select_preset',
    enabled: false,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-preset',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectInitiativeWrite(
    id: 'project.initiative.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/initiatives',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectKeyResultWrite(
    id: 'project.key_result.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/key-results',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectLoopRead(
    id: 'project.loop.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/operating-loop',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectOkrWrite(
    id: 'project.okr.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/objectives',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectStartupTeamActivate(
    id: 'project.startup_team.activate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/startup-team/:profileKey/activate',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectStartupTeamPause(
    id: 'project.startup_team.pause',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/startup-team/:profileKey/pause',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectStartupTeamRead(
    id: 'project.startup_team.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/startup-team',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectTaskStatusWrite(
    id: 'project.task.status.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/operations/projects/:projectId/operating-loop/tasks/:taskId/status',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectTaskWrite(
    id: 'project.task.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/tasks',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectWeekWrite(
    id: 'project.week.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/weeks',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  settingsAuditEventsList(
    id: 'settings.audit_events.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/organizations/:organizationId/audit-events',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsCapabilityManifestRead(
    id: 'settings.capability_manifest.read',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/organizations/:organizationId/capability-manifest',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsConnectorInstall(
    id: 'settings.connector.install',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'POST',
    path: '/platform/organizations/:organizationId/connectors/:connectorKey/install',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsConnectorRevoke(
    id: 'settings.connector.revoke',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'POST',
    path: '/platform/organizations/:organizationId/connectors/:connectorKey/revoke',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsConnectorsList(
    id: 'settings.connectors.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/organizations/:organizationId/connectors',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsMembersList(
    id: 'settings.members.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/organizations/:organizationId/members',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsModelPolicyRead(
    id: 'settings.model_policy.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/settings/model-policies/:agentProfile',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsModelPolicyWrite(
    id: 'settings.model_policy.write',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'PUT',
    path: '/agent/settings/model-policies/:agentProfile',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsModelProviderCreate(
    id: 'settings.model_provider.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/settings/model-providers',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsModelProviderList(
    id: 'settings.model_provider.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/settings/model-providers',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsModelProviderTest(
    id: 'settings.model_provider.test',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/settings/model-providers/:profileId/test',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsRuntimeNodeRevoke(
    id: 'settings.runtime_node.revoke',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'POST',
    path: '/platform/organizations/:organizationId/runtime-nodes/:nodeId/revoke',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsRuntimeNodesList(
    id: 'settings.runtime_nodes.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/organizations/:organizationId/runtime-nodes',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsSkillUpdate(
    id: 'settings.skill.update',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'PUT',
    path: '/agent/settings/skills/:skillKey',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  settingsSkillsList(
    id: 'settings.skills.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/settings/skills',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsGoalTreeRead(
    id: 'startup_os.goal_tree.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/goals/tree',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsGoalComplete(
    id: 'startup_os.goal.complete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/goals/:id/complete',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsGoalCreate(
    id: 'startup_os.goal.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/goals',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsGoalsNeedingReviewRead(
    id: 'startup_os.goals_needing_review.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/goals/needing-review',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsOnboardCadenceRead(
    id: 'startup_os.onboard_cadence.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/onboard/cadence/status',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsOnboardContextRead(
    id: 'startup_os.onboard_context.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/onboard/context/current',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsOnboardDimensionUpdate(
    id: 'startup_os.onboard_dimension.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/onboard/dimensions/:dimension',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsOnboardSessionCreate(
    id: 'startup_os.onboard_session.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/onboard/sessions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsOnboardSnapshotCreate(
    id: 'startup_os.onboard_snapshot.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/onboard/snapshots',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsPendingProjectsRead(
    id: 'startup_os.pending_projects.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/pending-review',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  startupOsProjectTriageCreate(
    id: 'startup_os.project_triage.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/triage',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceApprovalDecide(
    id: 'workforce.approval.decide',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/approvals/:approvalId/decision',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceApprovalsList(
    id: 'workforce.approvals.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/approvals',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceAssignmentCreate(
    id: 'workforce.assignment.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/assignments',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceAssignmentRetire(
    id: 'workforce.assignment.retire',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/assignments/:assignmentId/retire',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceAssignmentsList(
    id: 'workforce.assignments.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/assignments',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceCapabilitiesList(
    id: 'workforce.capabilities.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/capabilities',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceCompositionRead(
    id: 'workforce.composition.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/composition',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceCostObservationsList(
    id: 'workforce.cost_observations.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/cost-observations',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceDashboardSummaryRead(
    id: 'workforce.dashboard_summary.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/dashboard-summary',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceExceptionsList(
    id: 'workforce.exceptions.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/exceptions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceHealthRead(
    id: 'workforce.health.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/health',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceOrgChartRead(
    id: 'workforce.org_chart.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/org-chart',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceRosterList(
    id: 'workforce.roster.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/roster',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceRunArtifacts(
    id: 'workforce.run.artifacts',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs/:runId/artifacts',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceRunEvents(
    id: 'workforce.run.events',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs/:runId/events',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceRunRead(
    id: 'workforce.run.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs/:runId',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceRunsList(
    id: 'workforce.runs.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceScheduleCreate(
    id: 'workforce.schedule.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/schedules',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceScheduleRunNow(
    id: 'workforce.schedule.run_now',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/schedules/:scheduleId/run-now',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceSchedulesList(
    id: 'workforce.schedules.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/schedules',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceStageRosterRead(
    id: 'workforce.stage_roster.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/stage-roster/:stageCode',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  workforceWorkProductsList(
    id: 'workforce.work_products.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/artifacts',
    requiresWorkspace: true,
    requiresProject: false,
  );

  const MvpEndpoint({
    required this.id,
    required this.enabled,
    required this.plane,
    required this.method,
    required this.path,
    required this.requiresWorkspace,
    required this.requiresProject,
  });

  final String id;
  // Fix-review (2026-09-02, final review I-4) — `shared/contracts/mvp-surface.json`
  // đánh dấu `enabled: false` cho các capability chưa có backend thật (vd. vault.*);
  // trước đây field này không được emit ra Dart nên client Flutter không có cách
  // nào tự chặn gọi một endpoint đã biết trước là chưa khả dụng.
  final bool enabled;
  final ApiPlane plane;
  final String method;
  final String path;
  final bool requiresWorkspace;
  final bool requiresProject;

  static MvpEndpoint? fromId(String id) {
    for (final endpoint in MvpEndpoint.values) {
      if (endpoint.id == id) return endpoint;
    }
    return null;
  }

  static MvpEndpoint byId(String id) {
    final endpoint = fromId(id);
    if (endpoint == null) {
      throw ArgumentError.value(id, 'id', 'Unknown MvpEndpoint ID');
    }
    return endpoint;
  }
}
