// GENERATED FILE — DO NOT MODIFY DIRECTLY
// Source: shared/contracts/mvp-surface.json · Generator: scripts/gen-mvp-contracts.mjs
// To update: edit shared/contracts/mvp-surface.json and run `node scripts/gen-mvp-contracts.mjs`

import 'api_result.dart';

enum MvpEndpoint {
  agentConversationCreate(
    id: 'agent.conversation.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/projects/:projectId/conversations',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentConversationMessageCreate(
    id: 'agent.conversation.message.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/projects/:projectId/conversations/:conversationId/messages',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentConversationRead(
    id: 'agent.conversation.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/conversations/:conversationId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentConversationUpdate(
    id: 'agent.conversation.update',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'PATCH',
    path: '/agent/projects/:projectId/conversations/:conversationId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentKnowledgeProjectSearch(
    id: 'agent.knowledge.project.search',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/knowledge/projects/:projectId/search',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentProjectActivityDetail(
    id: 'agent.project_activity.detail',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/activity/:runId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentProjectActivityRead(
    id: 'agent.project_activity.read',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/activity',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  agentProjectActivityStream(
    id: 'agent.project_activity.stream',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/projects/:projectId/activity/stream',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialContactCreate(
    id: 'commercial.contact.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/contacts',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialInterviewCreate(
    id: 'commercial.interview.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/interviews',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialInterviewSubmitEvidence(
    id: 'commercial.interview.submit_evidence',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/interviews/:id/submit-evidence',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialLeadCreate(
    id: 'commercial.lead.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/leads',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  commercialProjectCrmFieldDefinitionsCreate(
    id: 'commercial.project_crm.field_definitions.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/field-definitions',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmFieldDefinitionsPatch(
    id: 'commercial.project_crm.field_definitions.patch',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/commercial/projects/:projectId/crm/field-definitions/:fieldId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmFieldDefinitionsRetire(
    id: 'commercial.project_crm.field_definitions.retire',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/field-definitions/:fieldId/retire',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadSourcesCreate(
    id: 'commercial.project_crm.lead_sources.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/lead-sources',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadSourcesList(
    id: 'commercial.project_crm.lead_sources.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/projects/:projectId/crm/lead-sources',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadsCreate(
    id: 'commercial.project_crm.leads.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/projects/:projectId/crm/leads',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmLeadsList(
    id: 'commercial.project_crm.leads.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/projects/:projectId/crm/leads',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  commercialProjectCrmSchemaGet(
    id: 'commercial.project_crm.schema.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/projects/:projectId/crm/schema',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  financeBudgetSummaryRead(
    id: 'finance.budget_summary.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance/budget-summary',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  financeSnapshotLatest(
    id: 'finance.snapshot.latest',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/finance/snapshots/latest',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityAgentCapabilityGrantCreate(
    id: 'identity.agent_capability_grant.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/agent-capability-grants',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityAgentCapabilityGrantRevoke(
    id: 'identity.agent_capability_grant.revoke',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/agent-capability-grants/:grantId/revoke',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityPermissionsRead(
    id: 'identity.permissions.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/identity/permissions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityPermissionsSimulate(
    id: 'identity.permissions.simulate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/permissions/simulate',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  identityPermissionsWrite(
    id: 'identity.permissions.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/identity/permissions',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingCampaignCreate(
    id: 'marketing.campaign.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/marketing/campaigns',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingCampaignList(
    id: 'marketing.campaign.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/campaigns',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingExperimentCreate(
    id: 'marketing.experiment.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/commercial/marketing/experiments',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  marketingExperimentList(
    id: 'marketing.experiment.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/experiments',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsFounderAssetCommand(
    id: 'operations.founder_asset.command',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/founder/assets/commands',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  operationsFounderAssetLibrary(
    id: 'operations.founder_asset.library',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/founder-assets',
    requiresWorkspace: true,
    requiresProject: false,
  ),
  projectCommitmentWrite(
    id: 'project.commitment.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/commitments',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectCycleWrite(
    id: 'project.cycle.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/cycles',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsCancel(
    id: 'project.deliberations.cancel',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/:deliberationId/cancel',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsDecision(
    id: 'project.deliberations.decision',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/:deliberationId/decision',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsDraft(
    id: 'project.deliberations.draft',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/draft',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsFrame(
    id: 'project.deliberations.frame',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/deliberations/:deliberationId/frame',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectDeliberationsRead(
    id: 'project.deliberations.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/deliberations/:deliberationId',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesActivate(
    id: 'project.executive_roles.activate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-roles/:roleKey/activate',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesDisable(
    id: 'project.executive_roles.disable',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-roles/:roleKey/disable',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesRead(
    id: 'project.executive_roles.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/executive-roles',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectExecutiveRolesSelectPreset(
    id: 'project.executive_roles.select_preset',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/executive-preset',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectLoopRead(
    id: 'project.loop.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/operating-loop',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectOkrWrite(
    id: 'project.okr.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/objectives',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectStartupTeamActivate(
    id: 'project.startup_team.activate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/startup-team/:profileKey/activate',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectStartupTeamPause(
    id: 'project.startup_team.pause',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/startup-team/:profileKey/pause',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectStartupTeamRead(
    id: 'project.startup_team.read',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/projects/:projectId/startup-team',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectTaskWrite(
    id: 'project.task.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/tasks',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  projectWeekWrite(
    id: 'project.week.write',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/projects/:projectId/operating-loop/weeks',
    requiresWorkspace: true,
    requiresProject: true,
  ),
  settingsCapabilityManifestRead(
    id: 'settings.capability_manifest.read',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/workspaces/:workspaceId/capability-manifest',
    requiresWorkspace: true,
    requiresProject: false,
  );

  const MvpEndpoint({
    required this.id,
    required this.enabled,
    required this.plane,
    required this.method,
    required this.path,
    required this.requiresWorkspace,
    required this.requiresProject,
  });

  final String id;
  // Fix-review (2026-09-02, final review I-4) — `shared/contracts/mvp-surface.json`
  // đánh dấu `enabled: false` cho các capability chưa có backend thật (vd. vault.*);
  // trước đây field này không được emit ra Dart nên client Flutter không có cách
  // nào tự chặn gọi một endpoint đã biết trước là chưa khả dụng.
  final bool enabled;
  final ApiPlane plane;
  final String method;
  final String path;
  final bool requiresWorkspace;
  final bool requiresProject;

  static MvpEndpoint? fromId(String id) {
    for (final endpoint in MvpEndpoint.values) {
      if (endpoint.id == id) return endpoint;
    }
    return null;
  }

  static MvpEndpoint byId(String id) {
    final endpoint = fromId(id);
    if (endpoint == null) {
      throw ArgumentError.value(id, 'id', 'Unknown MvpEndpoint ID');
    }
    return endpoint;
  }
}
