// GENERATED FILE — DO NOT MODIFY DIRECTLY
// Source: shared/contracts/mvp-surface.json · Generator: scripts/gen-mvp-contracts.mjs
// To update: edit shared/contracts/mvp-surface.json and run `node scripts/gen-mvp-contracts.mjs`

import 'api_result.dart';

enum MvpEndpoint {
  marketingAssetList(
    id: 'marketing.asset.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/assets',
    requiresWorkspace: true,
  ),
  marketingCampaignList(
    id: 'marketing.campaign.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/campaigns',
    requiresWorkspace: true,
  ),
  marketingContextGet(
    id: 'marketing.context.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing-context',
    requiresWorkspace: true,
  ),
  marketingContextUpdate(
    id: 'marketing.context.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/commercial/marketing-context',
    requiresWorkspace: true,
  ),
  marketingExperimentList(
    id: 'marketing.experiment.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/experiments',
    requiresWorkspace: true,
  ),
  marketingMetricObserved(
    id: 'marketing.metric.observed',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/metrics/observed',
    requiresWorkspace: true,
  ),
  marketingObjectiveList(
    id: 'marketing.objective.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/commercial/marketing/objectives',
    requiresWorkspace: true,
  ),
  settingsAuditEventList(
    id: 'settings.audit_event.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/workspaces/:workspaceId/audit-events',
    requiresWorkspace: true,
  ),
  settingsConnectorInstall(
    id: 'settings.connector.install',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'POST',
    path: '/platform/workspaces/:workspaceId/connectors/:connectorKey/install',
    requiresWorkspace: true,
  ),
  settingsConnectorList(
    id: 'settings.connector.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/workspaces/:workspaceId/connectors',
    requiresWorkspace: true,
  ),
  settingsConnectorRevoke(
    id: 'settings.connector.revoke',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'POST',
    path: '/platform/workspaces/:workspaceId/connectors/:connectorKey/revoke',
    requiresWorkspace: true,
  ),
  settingsMemberList(
    id: 'settings.member.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/workspaces/:workspaceId/members',
    requiresWorkspace: true,
  ),
  settingsPermissionGet(
    id: 'settings.permission.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/identity/permissions',
    requiresWorkspace: true,
  ),
  settingsPermissionSimulate(
    id: 'settings.permission.simulate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/identity/permissions/simulate',
    requiresWorkspace: true,
  ),
  settingsPermissionUpdate(
    id: 'settings.permission.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/identity/permissions',
    requiresWorkspace: true,
  ),
  settingsRuntimeNodeList(
    id: 'settings.runtime_node.list',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/workspaces/:workspaceId/runtime-nodes',
    requiresWorkspace: true,
  ),
  settingsRuntimeNodeRevoke(
    id: 'settings.runtime_node.revoke',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'POST',
    path: '/platform/workspaces/:workspaceId/runtime-nodes/:nodeId/revoke',
    requiresWorkspace: true,
  ),
  settingsSessionContextGet(
    id: 'settings.session_context.get',
    enabled: true,
    plane: ApiPlane.platform,
    method: 'GET',
    path: '/platform/workspaces/:workspaceId/session-context',
    requiresWorkspace: true,
  ),
  settingsSkillList(
    id: 'settings.skill.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/settings/skills',
    requiresWorkspace: true,
  ),
  settingsSkillUpdate(
    id: 'settings.skill.update',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'PUT',
    path: '/agent/settings/skills/:skillKey',
    requiresWorkspace: true,
  ),
  strategyAnalysisPestelCreate(
    id: 'strategy.analysis.pestel.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/objectives/:objectiveId/analysis/pestel',
    requiresWorkspace: true,
  ),
  strategyAnalysisPestelList(
    id: 'strategy.analysis.pestel.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/objectives/:objectiveId/analysis/pestel',
    requiresWorkspace: true,
  ),
  strategyAnalysisPestelUpdate(
    id: 'strategy.analysis.pestel.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/objectives/:objectiveId/analysis/pestel/:id',
    requiresWorkspace: true,
  ),
  strategyAnalysisResourceCreate(
    id: 'strategy.analysis.resource.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/objectives/:objectiveId/analysis/resources',
    requiresWorkspace: true,
  ),
  strategyAnalysisResourceList(
    id: 'strategy.analysis.resource.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/objectives/:objectiveId/analysis/resources',
    requiresWorkspace: true,
  ),
  strategyAnalysisResourceUpdate(
    id: 'strategy.analysis.resource.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/objectives/:objectiveId/analysis/resources/:id',
    requiresWorkspace: true,
  ),
  strategyAnalysisSwotCreate(
    id: 'strategy.analysis.swot.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/objectives/:objectiveId/analysis/swot',
    requiresWorkspace: true,
  ),
  strategyAnalysisSwotDeriveDrafts(
    id: 'strategy.analysis.swot.derive_drafts',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/objectives/:objectiveId/analysis/swot/derive-drafts',
    requiresWorkspace: true,
  ),
  strategyAnalysisSwotList(
    id: 'strategy.analysis.swot.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/objectives/:objectiveId/analysis/swot',
    requiresWorkspace: true,
  ),
  strategyAnalysisSwotUpdate(
    id: 'strategy.analysis.swot.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/objectives/:objectiveId/analysis/swot/:id',
    requiresWorkspace: true,
  ),
  strategyCanvasCreate(
    id: 'strategy.canvas.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/canvases',
    requiresWorkspace: true,
  ),
  strategyCanvasDelete(
    id: 'strategy.canvas.delete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'DELETE',
    path: '/operations/strategy/canvases/:id',
    requiresWorkspace: true,
  ),
  strategyCanvasGet(
    id: 'strategy.canvas.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/canvases/:id',
    requiresWorkspace: true,
  ),
  strategyCanvasList(
    id: 'strategy.canvas.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/canvases',
    requiresWorkspace: true,
  ),
  strategyCanvasRevisionApprove(
    id: 'strategy.canvas.revision.approve',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/canvas-revisions/:id/approve',
    requiresWorkspace: true,
  ),
  strategyCanvasRevisionCreate(
    id: 'strategy.canvas.revision.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/canvases/:id/revisions',
    requiresWorkspace: true,
  ),
  strategyCanvasRevisionGet(
    id: 'strategy.canvas.revision.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/canvas-revisions/:id',
    requiresWorkspace: true,
  ),
  strategyCanvasRevisionReject(
    id: 'strategy.canvas.revision.reject',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/canvas-revisions/:id/reject',
    requiresWorkspace: true,
  ),
  strategyCanvasRevisionSubmitReview(
    id: 'strategy.canvas.revision.submit_review',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/canvas-revisions/:id/submit-review',
    requiresWorkspace: true,
  ),
  strategyCanvasUpdate(
    id: 'strategy.canvas.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/canvases/:id',
    requiresWorkspace: true,
  ),
  strategyCycleReviewClose(
    id: 'strategy.cycle_review.close',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/cycle-reviews/:id/close',
    requiresWorkspace: true,
  ),
  strategyCycleReviewCreateCustomMidCycle(
    id: 'strategy.cycle_review.create_custom_mid_cycle',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/cycles/:cycleId/reviews/custom-mid-cycle',
    requiresWorkspace: true,
  ),
  strategyCycleReviewGet(
    id: 'strategy.cycle_review.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/cycle-reviews/:id',
    requiresWorkspace: true,
  ),
  strategyCycleReviewList(
    id: 'strategy.cycle_review.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/cycles/:cycleId/reviews',
    requiresWorkspace: true,
  ),
  strategyCycleReviewStart(
    id: 'strategy.cycle_review.start',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/cycle-reviews/:id/start',
    requiresWorkspace: true,
  ),
  strategyCycleReviewUpdate(
    id: 'strategy.cycle_review.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/operations/cycle-reviews/:id',
    requiresWorkspace: true,
  ),
  strategyExecutionCycleView(
    id: 'strategy.execution_cycle_view',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/execution-cycle-view',
    requiresWorkspace: true,
  ),
  strategyFundingMatches(
    id: 'strategy.funding.matches',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/funding-matches',
    requiresWorkspace: true,
  ),
  strategyInitiativeApprove(
    id: 'strategy.initiative.approve',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/initiatives/:id/approve',
    requiresWorkspace: true,
  ),
  strategyInitiativeCreate(
    id: 'strategy.initiative.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/initiatives',
    requiresWorkspace: true,
  ),
  strategyInitiativeGet(
    id: 'strategy.initiative.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/initiatives/:id',
    requiresWorkspace: true,
  ),
  strategyInitiativeList(
    id: 'strategy.initiative.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/initiatives',
    requiresWorkspace: true,
  ),
  strategyInitiativeUpdate(
    id: 'strategy.initiative.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/initiatives/:id',
    requiresWorkspace: true,
  ),
  strategyKeyResultCheckin(
    id: 'strategy.key_result.checkin',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/key-results/:id/checkin',
    requiresWorkspace: true,
  ),
  strategyKeyResultCreate(
    id: 'strategy.key_result.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives/:objectiveId/key-results',
    requiresWorkspace: true,
  ),
  strategyKeyResultDelete(
    id: 'strategy.key_result.delete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'DELETE',
    path: '/operations/key-results/:id',
    requiresWorkspace: true,
  ),
  strategyKeyResultList(
    id: 'strategy.key_result.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/key-results',
    requiresWorkspace: true,
  ),
  strategyKeyResultUpdate(
    id: 'strategy.key_result.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/key-results/:id',
    requiresWorkspace: true,
  ),
  strategyObjectiveCreate(
    id: 'strategy.objective.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives',
    requiresWorkspace: true,
  ),
  strategyObjectiveDelete(
    id: 'strategy.objective.delete',
    enabled: true,
    plane: ApiPlane.company,
    method: 'DELETE',
    path: '/operations/objectives/:id',
    requiresWorkspace: true,
  ),
  strategyObjectiveGet(
    id: 'strategy.objective.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/objectives/:id',
    requiresWorkspace: true,
  ),
  strategyObjectiveList(
    id: 'strategy.objective.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/objectives',
    requiresWorkspace: true,
  ),
  strategyObjectiveProgress(
    id: 'strategy.objective.progress',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/objectives/:id/progress',
    requiresWorkspace: true,
  ),
  strategyObjectivePublish(
    id: 'strategy.objective.publish',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/objectives/:id/publish',
    requiresWorkspace: true,
  ),
  strategyObjectiveUpdate(
    id: 'strategy.objective.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/objectives/:id',
    requiresWorkspace: true,
  ),
  strategyOkrCycleCreate(
    id: 'strategy.okr_cycle.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/okr-cycles',
    requiresWorkspace: true,
  ),
  strategyOkrCycleList(
    id: 'strategy.okr_cycle.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/okr-cycles',
    requiresWorkspace: true,
  ),
  strategySettingsGet(
    id: 'strategy.settings.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/settings',
    requiresWorkspace: true,
  ),
  strategySettingsUpdate(
    id: 'strategy.settings.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/settings',
    requiresWorkspace: true,
  ),
  strategyStrategicObjectiveBscFocusUpdate(
    id: 'strategy.strategic_objective.bsc_focus.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/objectives/:id/bsc-focus',
    requiresWorkspace: true,
  ),
  strategyStrategicObjectiveCreate(
    id: 'strategy.strategic_objective.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/objectives',
    requiresWorkspace: true,
  ),
  strategyStrategicObjectiveGet(
    id: 'strategy.strategic_objective.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/objectives/:id',
    requiresWorkspace: true,
  ),
  strategyStrategicObjectiveList(
    id: 'strategy.strategic_objective.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/objectives',
    requiresWorkspace: true,
  ),
  strategyStrategicObjectiveUpdate(
    id: 'strategy.strategic_objective.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/objectives/:id',
    requiresWorkspace: true,
  ),
  strategyTowsCreate(
    id: 'strategy.tows.create',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/objectives/:objectiveId/tows-options',
    requiresWorkspace: true,
  ),
  strategyTowsEvaluate(
    id: 'strategy.tows.evaluate',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/tows-options/:id/evaluations',
    requiresWorkspace: true,
  ),
  strategyTowsGet(
    id: 'strategy.tows.get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/tows-options/:id',
    requiresWorkspace: true,
  ),
  strategyTowsList(
    id: 'strategy.tows.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/strategy/objectives/:objectiveId/tows-options',
    requiresWorkspace: true,
  ),
  strategyTowsReject(
    id: 'strategy.tows.reject',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/tows-options/:id/reject',
    requiresWorkspace: true,
  ),
  strategyTowsSelect(
    id: 'strategy.tows.select',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/strategy/tows-options/:id/select',
    requiresWorkspace: true,
  ),
  strategyTowsUpdate(
    id: 'strategy.tows.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PUT',
    path: '/operations/strategy/tows-options/:id',
    requiresWorkspace: true,
  ),
  strategyTwelveWeekCommitmentList(
    id: 'strategy.twelve_week.commitment.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/twelve-week-commitments',
    requiresWorkspace: true,
  ),
  strategyTwelveWeekCycleList(
    id: 'strategy.twelve_week.cycle.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/twelve-week-cycles',
    requiresWorkspace: true,
  ),
  strategyTwelveWeekPlanList(
    id: 'strategy.twelve_week.plan.list',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/twelve-week-plans',
    requiresWorkspace: true,
  ),
  strategyTwelveWeekPlanUpdate(
    id: 'strategy.twelve_week.plan.update',
    enabled: true,
    plane: ApiPlane.company,
    method: 'PATCH',
    path: '/operations/twelve-week-plans/:id',
    requiresWorkspace: true,
  ),
  vaultDocumentArchive(
    id: 'vault.document.archive',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'DELETE',
    path: '/agent/vault/documents/:id',
    requiresWorkspace: true,
  ),
  vaultDocumentCreate(
    id: 'vault.document.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/vault/documents',
    requiresWorkspace: true,
  ),
  vaultDocumentGet(
    id: 'vault.document.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/vault/documents/:id',
    requiresWorkspace: true,
  ),
  vaultDocumentList(
    id: 'vault.document.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/vault/documents',
    requiresWorkspace: true,
  ),
  vaultDocumentPublish(
    id: 'vault.document.publish',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/vault/documents/:id/publish',
    requiresWorkspace: true,
  ),
  vaultDocumentPurge(
    id: 'vault.document.purge',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/vault/documents/:id/purge',
    requiresWorkspace: true,
  ),
  vaultDocumentReview(
    id: 'vault.document.review',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/vault/documents/:id/review',
    requiresWorkspace: true,
  ),
  vaultKnowledgeGraph(
    id: 'vault.knowledge.graph',
    enabled: false,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/vault/knowledge/graph',
    requiresWorkspace: true,
  ),
  vaultKnowledgeIndexedSources(
    id: 'vault.knowledge.indexed_sources',
    enabled: false,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/vault/knowledge/sources',
    requiresWorkspace: true,
  ),
  vaultKnowledgeRetrievalQuery(
    id: 'vault.knowledge.retrieval_query',
    enabled: false,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/vault/retrieval/query',
    requiresWorkspace: true,
  ),
  vaultUploadComplete(
    id: 'vault.upload.complete',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/vault/uploads/:id/complete',
    requiresWorkspace: true,
  ),
  workforceApprovalDecision(
    id: 'workforce.approval.decision',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/approvals/:approvalId/decision',
    requiresWorkspace: true,
  ),
  workforceApprovalList(
    id: 'workforce.approval.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/approvals',
    requiresWorkspace: true,
  ),
  workforceAssignmentCreate(
    id: 'workforce.assignment.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/assignments',
    requiresWorkspace: true,
  ),
  workforceAssignmentList(
    id: 'workforce.assignment.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/assignments',
    requiresWorkspace: true,
  ),
  workforceAssignmentRetire(
    id: 'workforce.assignment.retire',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/assignments/:id/retire',
    requiresWorkspace: true,
  ),
  workforceCapabilityList(
    id: 'workforce.capability.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/capabilities',
    requiresWorkspace: true,
  ),
  workforceCompositionGet(
    id: 'workforce.composition.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/composition',
    requiresWorkspace: true,
  ),
  workforceCostObservationList(
    id: 'workforce.cost_observation.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/cost-observations',
    requiresWorkspace: true,
  ),
  workforceDashboardSummaryGet(
    id: 'workforce.dashboard_summary.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/dashboard-summary',
    requiresWorkspace: true,
  ),
  workforceExceptionList(
    id: 'workforce.exception.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/exceptions',
    requiresWorkspace: true,
  ),
  workforceHealthGet(
    id: 'workforce.health.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/health',
    requiresWorkspace: true,
  ),
  workforceOrgChartGet(
    id: 'workforce.org_chart.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/org-chart',
    requiresWorkspace: true,
  ),
  workforceRosterList(
    id: 'workforce.roster.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/roster',
    requiresWorkspace: true,
  ),
  workforceRunArtifacts(
    id: 'workforce.run.artifacts',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs/:runId/artifacts',
    requiresWorkspace: true,
  ),
  workforceRunEvents(
    id: 'workforce.run.events',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs/:runId/events',
    requiresWorkspace: true,
  ),
  workforceRunGet(
    id: 'workforce.run.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs/:runId',
    requiresWorkspace: true,
  ),
  workforceRunList(
    id: 'workforce.run.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/runs',
    requiresWorkspace: true,
  ),
  workforceScheduleCreate(
    id: 'workforce.schedule.create',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/schedules',
    requiresWorkspace: true,
  ),
  workforceScheduleList(
    id: 'workforce.schedule.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/schedules',
    requiresWorkspace: true,
  ),
  workforceScheduleRunNow(
    id: 'workforce.schedule.run_now',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'POST',
    path: '/agent/workforce/schedules/:scheduleId/run-now',
    requiresWorkspace: true,
  ),
  workforceStageRosterGet(
    id: 'workforce.stage_roster.get',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/stage-roster/:stageCode',
    requiresWorkspace: true,
  ),
  workforceWorkProductList(
    id: 'workforce.work_product.list',
    enabled: true,
    plane: ApiPlane.agent,
    method: 'GET',
    path: '/agent/workforce/artifacts',
    requiresWorkspace: true,
  ),
  workspaceRuntimeBlockers(
    id: 'workspace_runtime.blockers',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/workspace-runtime/blockers',
    requiresWorkspace: true,
  ),
  workspaceRuntimeItemGet(
    id: 'workspace_runtime.item_get',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/workspace-runtime/items/:sourceKind/:sourceId',
    requiresWorkspace: true,
  ),
  workspaceRuntimeItemSnooze(
    id: 'workspace_runtime.item_snooze',
    enabled: true,
    plane: ApiPlane.company,
    method: 'POST',
    path: '/operations/workspace-runtime/items/:sourceKind/:sourceId/snooze',
    requiresWorkspace: true,
  ),
  workspaceRuntimeNeedsYou(
    id: 'workspace_runtime.needs_you',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/workspace-runtime/needs-you',
    requiresWorkspace: true,
  ),
  workspaceRuntimeSourceStatus(
    id: 'workspace_runtime.source_status',
    enabled: true,
    plane: ApiPlane.company,
    method: 'GET',
    path: '/operations/workspace-runtime/source-status',
    requiresWorkspace: true,
  );

  const MvpEndpoint({
    required this.id,
    required this.enabled,
    required this.plane,
    required this.method,
    required this.path,
    required this.requiresWorkspace,
  });

  final String id;
  // Fix-review (2026-09-02, final review I-4) — `shared/contracts/mvp-surface.json`
  // đánh dấu `enabled: false` cho các capability chưa có backend thật (vd. vault.*);
  // trước đây field này không được emit ra Dart nên client Flutter không có cách
  // nào tự chặn gọi một endpoint đã biết trước là chưa khả dụng.
  final bool enabled;
  final ApiPlane plane;
  final String method;
  final String path;
  final bool requiresWorkspace;

  static MvpEndpoint? fromId(String id) {
    for (final endpoint in MvpEndpoint.values) {
      if (endpoint.id == id) return endpoint;
    }
    return null;
  }

  static MvpEndpoint byId(String id) {
    final endpoint = fromId(id);
    if (endpoint == null) {
      throw ArgumentError.value(id, 'id', 'Unknown MvpEndpoint ID');
    }
    return endpoint;
  }
}
