"""add_cosa_workforce_control_plane_tables

Revision ID: 34e87711c422
Revises: v13_050_pending_schema_sync
Create Date: 2026-08-18 03:23:39.812349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e87711c422'
down_revision: Union[str, Sequence[str], None] = 'v13_050_pending_schema_sync'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_coa_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('source_regulation', sa.String(length=50), nullable=False),
    sa.Column('target_regulation', sa.String(length=50), nullable=False),
    sa.Column('source_account_code', sa.String(length=50), nullable=False),
    sa.Column('target_account_code', sa.String(length=50), nullable=False),
    sa.Column('mapping_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_coa_mappings_source_account_code'), 'accounting_coa_mappings', ['source_account_code'], unique=False)
    op.create_index(op.f('ix_accounting_coa_mappings_source_regulation'), 'accounting_coa_mappings', ['source_regulation'], unique=False)
    op.create_index(op.f('ix_accounting_coa_mappings_target_account_code'), 'accounting_coa_mappings', ['target_account_code'], unique=False)
    op.create_index(op.f('ix_accounting_coa_mappings_target_regulation'), 'accounting_coa_mappings', ['target_regulation'], unique=False)
    op.create_table('agent_definitions',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('default_model_profile', sa.String(length=100), nullable=False),
    sa.Column('system_prompt_key', sa.String(length=255), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_config_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_agent_definitions_ws_key')
    )
    op.create_index(op.f('ix_agent_definitions_id'), 'agent_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_definitions_key'), 'agent_definitions', ['key'], unique=False)
    op.create_index(op.f('ix_agent_definitions_workspace_id'), 'agent_definitions', ['workspace_id'], unique=False)
    op.create_table('agent_routines',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('routine_type', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('target_agent_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('payload_template_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_agent_routines_ws_key')
    )
    op.create_index(op.f('ix_agent_routines_id'), 'agent_routines', ['id'], unique=False)
    op.create_index(op.f('ix_agent_routines_key'), 'agent_routines', ['key'], unique=False)
    op.create_index(op.f('ix_agent_routines_workspace_id'), 'agent_routines', ['workspace_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('requester_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('requester_agent_key', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('required_role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tool_key', sa.String(length=150), nullable=True),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('approver_user_id', sa.BigInteger(), nullable=True),
    sa.Column('approver_comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_approval_requests_requester_agent_id'), 'approval_requests', ['requester_agent_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_requester_agent_key'), 'approval_requests', ['requester_agent_key'], unique=False)
    op.create_index(op.f('ix_approval_requests_run_id'), 'approval_requests', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_task_id'), 'approval_requests', ['task_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_workspace_id'), 'approval_requests', ['workspace_id'], unique=False)
    op.create_table('cost_ledger_entries',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_vnd', sa.Float(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=50), nullable=False),
    sa.Column('meta_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_entries_agent_id'), 'cost_ledger_entries', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cost_ledger_entries_agent_key'), 'cost_ledger_entries', ['agent_key'], unique=False)
    op.create_index(op.f('ix_cost_ledger_entries_id'), 'cost_ledger_entries', ['id'], unique=False)
    op.create_index(op.f('ix_cost_ledger_entries_run_id'), 'cost_ledger_entries', ['run_id'], unique=False)
    op.create_index(op.f('ix_cost_ledger_entries_task_id'), 'cost_ledger_entries', ['task_id'], unique=False)
    op.create_index(op.f('ix_cost_ledger_entries_workspace_id'), 'cost_ledger_entries', ['workspace_id'], unique=False)
    op.create_table('legal_sources',
    sa.Column('source_id', sa.String(length=150), nullable=False),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=150), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_sources_id'), 'legal_sources', ['id'], unique=False)
    op.create_index(op.f('ix_legal_sources_jurisdiction'), 'legal_sources', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_legal_sources_source_id'), 'legal_sources', ['source_id'], unique=True)
    op.create_index(op.f('ix_legal_sources_status'), 'legal_sources', ['status'], unique=False)
    op.create_table('platform_prompt_templates',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('default_content', sa.Text(), nullable=False),
    sa.Column('current_content', sa.Text(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_platform_prompt_ws_key')
    )
    op.create_index(op.f('ix_platform_prompt_templates_id'), 'platform_prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_platform_prompt_templates_key'), 'platform_prompt_templates', ['key'], unique=False)
    op.create_index(op.f('ix_platform_prompt_templates_workspace_id'), 'platform_prompt_templates', ['workspace_id'], unique=False)
    op.create_table('platform_secret_refs',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('external_ref', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_secret_refs_id'), 'platform_secret_refs', ['id'], unique=False)
    op.create_index(op.f('ix_platform_secret_refs_workspace_id'), 'platform_secret_refs', ['workspace_id'], unique=False)
    op.create_table('tool_definitions',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_config_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_tool_definitions_ws_key')
    )
    op.create_index(op.f('ix_tool_definitions_id'), 'tool_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_tool_definitions_key'), 'tool_definitions', ['key'], unique=False)
    op.create_index(op.f('ix_tool_definitions_workspace_id'), 'tool_definitions', ['workspace_id'], unique=False)
    op.create_table('unified_permissions',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('principal_type', sa.String(length=20), nullable=False),
    sa.Column('principal_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_key', sa.String(length=150), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'principal_type', 'principal_id', 'resource_type', 'resource_key', 'action', name='uq_unified_perm')
    )
    op.create_index(op.f('ix_unified_permissions_id'), 'unified_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_unified_permissions_principal_id'), 'unified_permissions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_unified_permissions_principal_type'), 'unified_permissions', ['principal_type'], unique=False)
    op.create_index(op.f('ix_unified_permissions_resource_key'), 'unified_permissions', ['resource_key'], unique=False)
    op.create_index(op.f('ix_unified_permissions_resource_type'), 'unified_permissions', ['resource_type'], unique=False)
    op.create_index(op.f('ix_unified_permissions_workspace_id'), 'unified_permissions', ['workspace_id'], unique=False)
    op.create_table('work_products',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('artifacts_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_products_agent_key'), 'work_products', ['agent_key'], unique=False)
    op.create_index(op.f('ix_work_products_id'), 'work_products', ['id'], unique=False)
    op.create_index(op.f('ix_work_products_run_id'), 'work_products', ['run_id'], unique=False)
    op.create_index(op.f('ix_work_products_task_id'), 'work_products', ['task_id'], unique=False)
    op.create_index(op.f('ix_work_products_workspace_id'), 'work_products', ['workspace_id'], unique=False)
    op.create_table('accounting_fiscal_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_year', sa.BigInteger(), nullable=False),
    sa.Column('regulation_code', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by', sa.BigInteger(), nullable=True),
    sa.Column('opening_balance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'fiscal_year', name='uq_accounting_fiscal_profile_workspace_year')
    )
    op.create_index(op.f('ix_accounting_fiscal_profiles_fiscal_year'), 'accounting_fiscal_profiles', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_accounting_fiscal_profiles_workspace_id'), 'accounting_fiscal_profiles', ['workspace_id'], unique=False)
    op.create_table('accounting_regime_transition_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('from_fiscal_year', sa.BigInteger(), nullable=False),
    sa.Column('to_fiscal_year', sa.BigInteger(), nullable=False),
    sa.Column('from_regulation', sa.String(length=50), nullable=False),
    sa.Column('to_regulation', sa.String(length=50), nullable=False),
    sa.Column('cutoff_date', sa.Date(), nullable=False),
    sa.Column('opening_balance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_balanced', sa.Boolean(), nullable=False),
    sa.Column('total_debit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_credit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('executed_by', sa.BigInteger(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_regime_transition_logs_workspace_id'), 'accounting_regime_transition_logs', ['workspace_id'], unique=False)
    op.create_table('agent_budgets',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('cycle_type', sa.String(length=50), nullable=False),
    sa.Column('limit_usd', sa.Float(), nullable=False),
    sa.Column('spent_usd', sa.Float(), nullable=False),
    sa.Column('soft_limit_percent', sa.Float(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_budgets_agent_id'), 'agent_budgets', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_budgets_agent_key'), 'agent_budgets', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_budgets_department'), 'agent_budgets', ['department'], unique=False)
    op.create_index(op.f('ix_agent_budgets_id'), 'agent_budgets', ['id'], unique=False)
    op.create_index(op.f('ix_agent_budgets_workspace_id'), 'agent_budgets', ['workspace_id'], unique=False)
    op.create_table('agent_heartbeats',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('active_runs_count', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'agent_key', name='uq_agent_heartbeat_ws_key')
    )
    op.create_index(op.f('ix_agent_heartbeats_agent_id'), 'agent_heartbeats', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_heartbeats_agent_key'), 'agent_heartbeats', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_heartbeats_id'), 'agent_heartbeats', ['id'], unique=False)
    op.create_index(op.f('ix_agent_heartbeats_workspace_id'), 'agent_heartbeats', ['workspace_id'], unique=False)
    op.create_table('agent_hierarchies',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('child_agent_id', sa.BigInteger(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('meta_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_agent_id'], ['agent_definitions.id'], ),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agent_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'parent_agent_id', 'child_agent_id', name='uq_agent_hierarchy_ws_nodes')
    )
    op.create_index(op.f('ix_agent_hierarchies_child_agent_id'), 'agent_hierarchies', ['child_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_hierarchies_id'), 'agent_hierarchies', ['id'], unique=False)
    op.create_index(op.f('ix_agent_hierarchies_parent_agent_id'), 'agent_hierarchies', ['parent_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_hierarchies_workspace_id'), 'agent_hierarchies', ['workspace_id'], unique=False)
    op.create_table('agent_tool_permissions',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('tool_id', sa.BigInteger(), nullable=False),
    sa.Column('allow_execute', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definitions.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'agent_id', 'tool_id', name='uq_agent_tool_perm_ws')
    )
    op.create_index(op.f('ix_agent_tool_permissions_agent_id'), 'agent_tool_permissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_id'), 'agent_tool_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_tool_id'), 'agent_tool_permissions', ['tool_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_permissions_workspace_id'), 'agent_tool_permissions', ['workspace_id'], unique=False)
    op.create_table('business_asset_overrides',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('pack_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content_override_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_override_markdown', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'asset_id', name='uq_asset_override_ws_asset')
    )
    op.create_index(op.f('ix_business_asset_overrides_asset_id'), 'business_asset_overrides', ['asset_id'], unique=False)
    op.create_index(op.f('ix_business_asset_overrides_id'), 'business_asset_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_business_asset_overrides_pack_id'), 'business_asset_overrides', ['pack_id'], unique=False)
    op.create_index(op.f('ix_business_asset_overrides_workspace_id'), 'business_asset_overrides', ['workspace_id'], unique=False)
    op.create_table('business_packs',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('pack_id', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_factory', sa.Boolean(), nullable=False),
    sa.Column('manifest_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'pack_id', name='uq_business_packs_ws_pack')
    )
    op.create_index(op.f('ix_business_packs_domain'), 'business_packs', ['domain'], unique=False)
    op.create_index(op.f('ix_business_packs_id'), 'business_packs', ['id'], unique=False)
    op.create_index(op.f('ix_business_packs_pack_id'), 'business_packs', ['pack_id'], unique=False)
    op.create_index(op.f('ix_business_packs_workspace_id'), 'business_packs', ['workspace_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('work_product_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('decision_content', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('alternatives_considered', sa.Text(), nullable=True),
    sa.Column('author_agent_key', sa.String(length=100), nullable=False),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['work_product_id'], ['work_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_id'), 'decision_records', ['id'], unique=False)
    op.create_index(op.f('ix_decision_records_task_id'), 'decision_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_decision_records_work_product_id'), 'decision_records', ['work_product_id'], unique=False)
    op.create_index(op.f('ix_decision_records_workspace_id'), 'decision_records', ['workspace_id'], unique=False)
    op.create_table('legal_annotations',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('legal_source_id', sa.String(length=150), nullable=False),
    sa.Column('applicability_status', sa.String(length=30), nullable=False),
    sa.Column('business_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_sops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linked_templates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'legal_source_id', name='uq_legal_annotation_ws_source')
    )
    op.create_index(op.f('ix_legal_annotations_id'), 'legal_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_legal_annotations_legal_source_id'), 'legal_annotations', ['legal_source_id'], unique=False)
    op.create_index(op.f('ix_legal_annotations_workspace_id'), 'legal_annotations', ['workspace_id'], unique=False)
    op.create_table('platform_agent_runs',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('workflow_key', sa.String(length=100), nullable=True),
    sa.Column('runtime_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('output_payload', sa.Text(), nullable=True),
    sa.Column('error_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_agent_runs_agent_id'), 'platform_agent_runs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_platform_agent_runs_agent_key'), 'platform_agent_runs', ['agent_key'], unique=False)
    op.create_index(op.f('ix_platform_agent_runs_id'), 'platform_agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_platform_agent_runs_session_id'), 'platform_agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_platform_agent_runs_task_id'), 'platform_agent_runs', ['task_id'], unique=False)
    op.create_index(op.f('ix_platform_agent_runs_trace_id'), 'platform_agent_runs', ['trace_id'], unique=False)
    op.create_index(op.f('ix_platform_agent_runs_workspace_id'), 'platform_agent_runs', ['workspace_id'], unique=False)
    op.create_table('platform_prompt_versions',
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('change_note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['platform_prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_prompt_versions_id'), 'platform_prompt_versions', ['id'], unique=False)
    op.create_index(op.f('ix_platform_prompt_versions_template_id'), 'platform_prompt_versions', ['template_id'], unique=False)
    op.create_table('platform_tool_versions',
    sa.Column('tool_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_tool_versions_id'), 'platform_tool_versions', ['id'], unique=False)
    op.create_index(op.f('ix_platform_tool_versions_tool_id'), 'platform_tool_versions', ['tool_id'], unique=False)
    op.create_table('routine_executions',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('routine_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output_summary_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['agent_routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_executions_id'), 'routine_executions', ['id'], unique=False)
    op.create_index(op.f('ix_routine_executions_routine_id'), 'routine_executions', ['routine_id'], unique=False)
    op.create_index(op.f('ix_routine_executions_run_id'), 'routine_executions', ['run_id'], unique=False)
    op.create_index(op.f('ix_routine_executions_task_id'), 'routine_executions', ['task_id'], unique=False)
    op.create_index(op.f('ix_routine_executions_workspace_id'), 'routine_executions', ['workspace_id'], unique=False)
    op.create_table('platform_agent_steps',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_step_id', sa.BigInteger(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['platform_agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_agent_steps_id'), 'platform_agent_steps', ['id'], unique=False)
    op.create_index(op.f('ix_platform_agent_steps_run_id'), 'platform_agent_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_agent_steps_run_id'), table_name='platform_agent_steps')
    op.drop_index(op.f('ix_platform_agent_steps_id'), table_name='platform_agent_steps')
    op.drop_table('platform_agent_steps')
    op.drop_index(op.f('ix_routine_executions_workspace_id'), table_name='routine_executions')
    op.drop_index(op.f('ix_routine_executions_task_id'), table_name='routine_executions')
    op.drop_index(op.f('ix_routine_executions_run_id'), table_name='routine_executions')
    op.drop_index(op.f('ix_routine_executions_routine_id'), table_name='routine_executions')
    op.drop_index(op.f('ix_routine_executions_id'), table_name='routine_executions')
    op.drop_table('routine_executions')
    op.drop_index(op.f('ix_platform_tool_versions_tool_id'), table_name='platform_tool_versions')
    op.drop_index(op.f('ix_platform_tool_versions_id'), table_name='platform_tool_versions')
    op.drop_table('platform_tool_versions')
    op.drop_index(op.f('ix_platform_prompt_versions_template_id'), table_name='platform_prompt_versions')
    op.drop_index(op.f('ix_platform_prompt_versions_id'), table_name='platform_prompt_versions')
    op.drop_table('platform_prompt_versions')
    op.drop_index(op.f('ix_platform_agent_runs_workspace_id'), table_name='platform_agent_runs')
    op.drop_index(op.f('ix_platform_agent_runs_trace_id'), table_name='platform_agent_runs')
    op.drop_index(op.f('ix_platform_agent_runs_task_id'), table_name='platform_agent_runs')
    op.drop_index(op.f('ix_platform_agent_runs_session_id'), table_name='platform_agent_runs')
    op.drop_index(op.f('ix_platform_agent_runs_id'), table_name='platform_agent_runs')
    op.drop_index(op.f('ix_platform_agent_runs_agent_key'), table_name='platform_agent_runs')
    op.drop_index(op.f('ix_platform_agent_runs_agent_id'), table_name='platform_agent_runs')
    op.drop_table('platform_agent_runs')
    op.drop_index(op.f('ix_legal_annotations_workspace_id'), table_name='legal_annotations')
    op.drop_index(op.f('ix_legal_annotations_legal_source_id'), table_name='legal_annotations')
    op.drop_index(op.f('ix_legal_annotations_id'), table_name='legal_annotations')
    op.drop_table('legal_annotations')
    op.drop_index(op.f('ix_decision_records_workspace_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_work_product_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_task_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_business_packs_workspace_id'), table_name='business_packs')
    op.drop_index(op.f('ix_business_packs_pack_id'), table_name='business_packs')
    op.drop_index(op.f('ix_business_packs_id'), table_name='business_packs')
    op.drop_index(op.f('ix_business_packs_domain'), table_name='business_packs')
    op.drop_table('business_packs')
    op.drop_index(op.f('ix_business_asset_overrides_workspace_id'), table_name='business_asset_overrides')
    op.drop_index(op.f('ix_business_asset_overrides_pack_id'), table_name='business_asset_overrides')
    op.drop_index(op.f('ix_business_asset_overrides_id'), table_name='business_asset_overrides')
    op.drop_index(op.f('ix_business_asset_overrides_asset_id'), table_name='business_asset_overrides')
    op.drop_table('business_asset_overrides')
    op.drop_index(op.f('ix_agent_tool_permissions_workspace_id'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_tool_id'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_id'), table_name='agent_tool_permissions')
    op.drop_index(op.f('ix_agent_tool_permissions_agent_id'), table_name='agent_tool_permissions')
    op.drop_table('agent_tool_permissions')
    op.drop_index(op.f('ix_agent_hierarchies_workspace_id'), table_name='agent_hierarchies')
    op.drop_index(op.f('ix_agent_hierarchies_parent_agent_id'), table_name='agent_hierarchies')
    op.drop_index(op.f('ix_agent_hierarchies_id'), table_name='agent_hierarchies')
    op.drop_index(op.f('ix_agent_hierarchies_child_agent_id'), table_name='agent_hierarchies')
    op.drop_table('agent_hierarchies')
    op.drop_index(op.f('ix_agent_heartbeats_workspace_id'), table_name='agent_heartbeats')
    op.drop_index(op.f('ix_agent_heartbeats_id'), table_name='agent_heartbeats')
    op.drop_index(op.f('ix_agent_heartbeats_agent_key'), table_name='agent_heartbeats')
    op.drop_index(op.f('ix_agent_heartbeats_agent_id'), table_name='agent_heartbeats')
    op.drop_table('agent_heartbeats')
    op.drop_index(op.f('ix_agent_budgets_workspace_id'), table_name='agent_budgets')
    op.drop_index(op.f('ix_agent_budgets_id'), table_name='agent_budgets')
    op.drop_index(op.f('ix_agent_budgets_department'), table_name='agent_budgets')
    op.drop_index(op.f('ix_agent_budgets_agent_key'), table_name='agent_budgets')
    op.drop_index(op.f('ix_agent_budgets_agent_id'), table_name='agent_budgets')
    op.drop_table('agent_budgets')
    op.drop_index(op.f('ix_accounting_regime_transition_logs_workspace_id'), table_name='accounting_regime_transition_logs')
    op.drop_table('accounting_regime_transition_logs')
    op.drop_index(op.f('ix_accounting_fiscal_profiles_workspace_id'), table_name='accounting_fiscal_profiles')
    op.drop_index(op.f('ix_accounting_fiscal_profiles_fiscal_year'), table_name='accounting_fiscal_profiles')
    op.drop_table('accounting_fiscal_profiles')
    op.drop_index(op.f('ix_work_products_workspace_id'), table_name='work_products')
    op.drop_index(op.f('ix_work_products_task_id'), table_name='work_products')
    op.drop_index(op.f('ix_work_products_run_id'), table_name='work_products')
    op.drop_index(op.f('ix_work_products_id'), table_name='work_products')
    op.drop_index(op.f('ix_work_products_agent_key'), table_name='work_products')
    op.drop_table('work_products')
    op.drop_index(op.f('ix_unified_permissions_workspace_id'), table_name='unified_permissions')
    op.drop_index(op.f('ix_unified_permissions_resource_type'), table_name='unified_permissions')
    op.drop_index(op.f('ix_unified_permissions_resource_key'), table_name='unified_permissions')
    op.drop_index(op.f('ix_unified_permissions_principal_type'), table_name='unified_permissions')
    op.drop_index(op.f('ix_unified_permissions_principal_id'), table_name='unified_permissions')
    op.drop_index(op.f('ix_unified_permissions_id'), table_name='unified_permissions')
    op.drop_table('unified_permissions')
    op.drop_index(op.f('ix_tool_definitions_workspace_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_key'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_id'), table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index(op.f('ix_platform_secret_refs_workspace_id'), table_name='platform_secret_refs')
    op.drop_index(op.f('ix_platform_secret_refs_id'), table_name='platform_secret_refs')
    op.drop_table('platform_secret_refs')
    op.drop_index(op.f('ix_platform_prompt_templates_workspace_id'), table_name='platform_prompt_templates')
    op.drop_index(op.f('ix_platform_prompt_templates_key'), table_name='platform_prompt_templates')
    op.drop_index(op.f('ix_platform_prompt_templates_id'), table_name='platform_prompt_templates')
    op.drop_table('platform_prompt_templates')
    op.drop_index(op.f('ix_legal_sources_status'), table_name='legal_sources')
    op.drop_index(op.f('ix_legal_sources_source_id'), table_name='legal_sources')
    op.drop_index(op.f('ix_legal_sources_jurisdiction'), table_name='legal_sources')
    op.drop_index(op.f('ix_legal_sources_id'), table_name='legal_sources')
    op.drop_table('legal_sources')
    op.drop_index(op.f('ix_cost_ledger_entries_workspace_id'), table_name='cost_ledger_entries')
    op.drop_index(op.f('ix_cost_ledger_entries_task_id'), table_name='cost_ledger_entries')
    op.drop_index(op.f('ix_cost_ledger_entries_run_id'), table_name='cost_ledger_entries')
    op.drop_index(op.f('ix_cost_ledger_entries_id'), table_name='cost_ledger_entries')
    op.drop_index(op.f('ix_cost_ledger_entries_agent_key'), table_name='cost_ledger_entries')
    op.drop_index(op.f('ix_cost_ledger_entries_agent_id'), table_name='cost_ledger_entries')
    op.drop_table('cost_ledger_entries')
    op.drop_index(op.f('ix_approval_requests_workspace_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_task_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_run_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requester_agent_key'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requester_agent_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_agent_routines_workspace_id'), table_name='agent_routines')
    op.drop_index(op.f('ix_agent_routines_key'), table_name='agent_routines')
    op.drop_index(op.f('ix_agent_routines_id'), table_name='agent_routines')
    op.drop_table('agent_routines')
    op.drop_index(op.f('ix_agent_definitions_workspace_id'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_key'), table_name='agent_definitions')
    op.drop_index(op.f('ix_agent_definitions_id'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    op.drop_index(op.f('ix_accounting_coa_mappings_target_regulation'), table_name='accounting_coa_mappings')
    op.drop_index(op.f('ix_accounting_coa_mappings_target_account_code'), table_name='accounting_coa_mappings')
    op.drop_index(op.f('ix_accounting_coa_mappings_source_regulation'), table_name='accounting_coa_mappings')
    op.drop_index(op.f('ix_accounting_coa_mappings_source_account_code'), table_name='accounting_coa_mappings')
    op.drop_table('accounting_coa_mappings')
    # ### end Alembic commands ###
