"""add_missing_spec_unique_constraints

Revision ID: 3c9fd60ac308
Revises: bf752f63ca3e
Create Date: 2026-08-09 08:12:39.875732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9fd60ac308'
down_revision: Union[str, Sequence[str], None] = 'bf752f63ca3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_twelve_week_cycle_brain_start', 'twelve_week_cycles', ['brain_id', 'start_date'])
    op.create_unique_constraint('uix_weekly_plan_cycle_week', 'weekly_plans', ['cycle_id', 'week_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_weekly_plan_cycle_week', 'weekly_plans', type_='unique')
    op.drop_constraint('uix_twelve_week_cycle_brain_start', 'twelve_week_cycles', type_='unique')
    # ### end Alembic commands ###
