"""wave_2_multi_brain_rag

Revision ID: 50a0e7e178f1
Revises: c4a1b9e8d2f0
Create Date: 2026-08-09 22:35:27.832595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a0e7e178f1'
down_revision: Union[str, Sequence[str], None] = 'c4a1b9e8d2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunking_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['vault_documents.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['vault_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunking_jobs_document_id'), 'chunking_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunking_jobs_revision_id'), 'chunking_jobs', ['revision_id'], unique=False)
    op.alter_column('ai_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('brains', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('brains', sa.Column('archived_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('brains_workspace_id_key'), 'brains', type_='unique')
    op.create_index(op.f('ix_brains_workspace_id'), 'brains', ['workspace_id'], unique=False)
    op.create_unique_constraint('uix_brain_workspace_slug', 'brains', ['workspace_id', 'slug'])
    op.add_column('chat_messages', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('ck_context_packs_status'), 'context_packs', type_='check')
    op.drop_constraint(op.f('ck_core_values_slot_no'), 'core_values', type_='check')
    op.drop_constraint(op.f('ck_evidence_items_reliability'), 'evidence_items', type_='check')
    op.drop_index(op.f('ix_strategy_profiles_brain_id'), table_name='strategy_canvases')
    op.drop_index(op.f('ix_strategy_profiles_workspace_id'), table_name='strategy_canvases')
    op.create_index(op.f('ix_strategy_canvases_brain_id'), 'strategy_canvases', ['brain_id'], unique=False)
    op.create_index(op.f('ix_strategy_canvases_workspace_id'), 'strategy_canvases', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('ck_strategy_foundations_mission_len'), 'strategy_foundations', type_='check')
    op.drop_constraint(op.f('ck_strategy_foundations_status'), 'strategy_foundations', type_='check')
    op.drop_constraint(op.f('ck_strategy_foundations_vision_len'), 'strategy_foundations', type_='check')
    op.drop_index(op.f('one_approved_revision_per_canvas'), table_name='strategy_revisions', postgresql_where="((status)::text = 'approved'::text)")
    op.create_foreign_key(None, 'strategy_revisions', 'strategy_revisions', ['parent_revision_id'], ['id'], use_alter=True)
    op.drop_constraint(op.f('ck_strategy_revisions_status'), 'strategy_revisions', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_strategy_revisions_status'), 'strategy_revisions', "status::text = ANY (ARRAY['draft'::character varying, 'in_review'::character varying, 'approved'::character varying, 'changes_requested'::character varying, 'superseded'::character varying, 'archived'::character varying]::text[])")
    op.drop_constraint(None, 'strategy_revisions', type_='foreignkey')
    op.create_index(op.f('one_approved_revision_per_canvas'), 'strategy_revisions', ['canvas_id'], unique=True, postgresql_where="((status)::text = 'approved'::text)")
    op.create_check_constraint(op.f('ck_strategy_foundations_vision_len'), 'strategy_foundations', 'vision IS NULL OR char_length(vision) >= 20 AND char_length(vision) <= 500')
    op.create_check_constraint(op.f('ck_strategy_foundations_status'), 'strategy_foundations', "status::text = ANY (ARRAY['draft'::character varying, 'approved'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_strategy_foundations_mission_len'), 'strategy_foundations', 'mission IS NULL OR char_length(mission) >= 20 AND char_length(mission) <= 500')
    op.drop_index(op.f('ix_strategy_canvases_workspace_id'), table_name='strategy_canvases')
    op.drop_index(op.f('ix_strategy_canvases_brain_id'), table_name='strategy_canvases')
    op.create_index(op.f('ix_strategy_profiles_workspace_id'), 'strategy_canvases', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_strategy_profiles_brain_id'), 'strategy_canvases', ['brain_id'], unique=False)
    op.create_check_constraint(op.f('ck_evidence_items_reliability'), 'evidence_items', "reliability::text = ANY (ARRAY['high'::character varying, 'medium'::character varying, 'low'::character varying]::text[])")
    op.create_check_constraint(op.f('ck_core_values_slot_no'), 'core_values', 'slot_no >= 1 AND slot_no <= 3')
    op.create_check_constraint(op.f('ck_context_packs_status'), 'context_packs', "status::text = ANY (ARRAY['draft'::character varying, 'ready_for_review'::character varying, 'approved'::character varying, 'stale'::character varying, 'superseded'::character varying]::text[])")
    op.drop_column('chat_messages', 'citations')
    op.drop_constraint('uix_brain_workspace_slug', 'brains', type_='unique')
    op.drop_index(op.f('ix_brains_workspace_id'), table_name='brains')
    op.create_unique_constraint(op.f('brains_workspace_id_key'), 'brains', ['workspace_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('brains', 'archived_at')
    op.drop_column('brains', 'slug')
    op.alter_column('ai_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_chunking_jobs_revision_id'), table_name='chunking_jobs')
    op.drop_index(op.f('ix_chunking_jobs_document_id'), table_name='chunking_jobs')
    op.drop_table('chunking_jobs')
    # ### end Alembic commands ###
