"""Phase 5 plugins and channels

Revision ID: 53daa6ebf13d
Revises: bfe783bb6375
Create Date: 2026-08-09 08:03:44.433806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53daa6ebf13d'
down_revision: Union[str, Sequence[str], None] = 'bfe783bb6375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('manifest_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trust_level', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('outbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=False),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_dedupe_key'), 'outbox', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_outbox_workspace_id'), 'outbox', ['workspace_id'], unique=False)
    op.create_table('workspace_plugins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plugin_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('granted_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_plugins_plugin_id'), 'workspace_plugins', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_workspace_plugins_workspace_id'), 'workspace_plugins', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_plugins_workspace_id'), table_name='workspace_plugins')
    op.drop_index(op.f('ix_workspace_plugins_plugin_id'), table_name='workspace_plugins')
    op.drop_table('workspace_plugins')
    op.drop_index(op.f('ix_outbox_workspace_id'), table_name='outbox')
    op.drop_index(op.f('ix_outbox_dedupe_key'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_table('plugins')
    # ### end Alembic commands ###
