"""phase_1_vault_and_auth

Revision ID: 8e169cce4a2f
Revises: efb9062d795f
Create Date: 2026-08-09 07:36:51.847844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e169cce4a2f'
down_revision: Union[str, Sequence[str], None] = 'efb9062d795f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_brain_id'), 'attachments', ['brain_id'], unique=False)
    op.create_table('vault_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['current_revision_id'], ['vault_revisions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_documents_brain_id'), 'vault_documents', ['brain_id'], unique=False)
    op.create_index(op.f('ix_vault_documents_path'), 'vault_documents', ['path'], unique=False)
    op.create_table('vault_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['vault_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vault_revisions_document_id'), 'vault_revisions', ['document_id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_vault_revisions_document_id'), table_name='vault_revisions')
    op.drop_table('vault_revisions')
    op.drop_index(op.f('ix_vault_documents_path'), table_name='vault_documents')
    op.drop_index(op.f('ix_vault_documents_brain_id'), table_name='vault_documents')
    op.drop_table('vault_documents')
    op.drop_index(op.f('ix_attachments_brain_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
