"""add workflow lifecycle fields

Revision ID: ad6a74ebb1c7
Revises: b206bc21673f
Create Date: 2026-08-20 14:47:45.847415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad6a74ebb1c7'
down_revision: Union[str, Sequence[str], None] = 'b206bc21673f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_versions', sa.Column('state', sa.String(length=50), nullable=False))
    op.add_column('workflow_versions', sa.Column('graph_schema_version', sa.String(length=20), nullable=False))
    op.add_column('workflow_versions', sa.Column('validation_report_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_versions', sa.Column('dependency_snapshot_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflow_versions', sa.Column('revision_token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_versions', 'revision_token')
    op.drop_column('workflow_versions', 'dependency_snapshot_jsonb')
    op.drop_column('workflow_versions', 'validation_report_jsonb')
    op.drop_column('workflow_versions', 'graph_schema_version')
    op.drop_column('workflow_versions', 'state')
    # ### end Alembic commands ###
