"""Phase 4 workflow models

Revision ID: b13db2f78fcd
Revises: ab49957e4bf5
Create Date: 2026-08-09 08:00:59.702995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b13db2f78fcd'
down_revision: Union[str, Sequence[str], None] = 'ab49957e4bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_brain_id'), 'workflow_definitions', ['brain_id'], unique=False)
    op.create_table('workflow_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=True),
    sa.Column('graph_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['vault_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_versions_definition_id'), 'workflow_versions', ['definition_id'], unique=False)
    op.create_index(op.f('ix_workflow_versions_revision_id'), 'workflow_versions', ['revision_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('output_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_run_id'), 'workflow_steps', ['run_id'], unique=False)
    op.create_table('workflow_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('snapshot_payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_approvals_step_id'), 'workflow_approvals', ['step_id'], unique=False)
    op.drop_column('ai_runs', 'created_at')
    op.drop_column('ai_runs', 'cost_estimate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('cost_estimate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('ai_runs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_workflow_approvals_step_id'), table_name='workflow_approvals')
    op.drop_table('workflow_approvals')
    op.drop_index(op.f('ix_workflow_steps_run_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_versions_revision_id'), table_name='workflow_versions')
    op.drop_index(op.f('ix_workflow_versions_definition_id'), table_name='workflow_versions')
    op.drop_table('workflow_versions')
    op.drop_index(op.f('ix_workflow_definitions_brain_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
