"""extension_registry

Revision ID: b206bc21673f
Revises: v13_059_workflow_scope_snapshots
Create Date: 2026-08-20 14:22:08.082913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b206bc21673f'
down_revision: Union[str, Sequence[str], None] = 'v13_059_workflow_scope_snapshots'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('disabled_reason', sa.String(), nullable=True),
    sa.Column('manifest_jsonb', sa.JSON(), nullable=False),
    sa.Column('health_jsonb', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'extension_id', name='uq_extension_workspace')
    )
    op.create_index(op.f('ix_extension_registrations_id'), 'extension_registrations', ['id'], unique=False)
    op.create_table('dimension_states',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('pillar', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'dimension', name='uq_dimension_state_project_dim')
    )
    op.create_index(op.f('ix_dimension_states_dimension'), 'dimension_states', ['dimension'], unique=False)
    op.create_index(op.f('ix_dimension_states_project_id'), 'dimension_states', ['project_id'], unique=False)
    op.create_index(op.f('ix_dimension_states_state'), 'dimension_states', ['state'], unique=False)
    op.create_index(op.f('ix_dimension_states_workspace_id'), 'dimension_states', ['workspace_id'], unique=False)
    op.create_table('project_stage_history',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('transition_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stage_history_project_id'), 'project_stage_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stage_history_workspace_id'), 'project_stage_history', ['workspace_id'], unique=False)
    op.create_table('validation_customer_contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('contact_info', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_customer_contacts_project_id'), 'validation_customer_contacts', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_customer_contacts_role'), 'validation_customer_contacts', ['role'], unique=False)
    op.create_index(op.f('ix_validation_customer_contacts_workspace_id'), 'validation_customer_contacts', ['workspace_id'], unique=False)
    op.create_table('validation_pain_patterns',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('cluster_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_count', sa.Integer(), nullable=False),
    sa.Column('quote_refs_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_pain_patterns_cluster_type'), 'validation_pain_patterns', ['cluster_type'], unique=False)
    op.create_index(op.f('ix_validation_pain_patterns_project_id'), 'validation_pain_patterns', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_pain_patterns_workspace_id'), 'validation_pain_patterns', ['workspace_id'], unique=False)
    op.create_table('validation_problem_scorecards',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('frequency_score', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('alternatives_score', sa.Integer(), nullable=False),
    sa.Column('wtp_score', sa.Integer(), nullable=False),
    sa.Column('market_potential_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('evidence_quality', sa.String(length=50), nullable=False),
    sa.Column('evidence_refs_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interpretation_result', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_problem_scorecards_project_id'), 'validation_problem_scorecards', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_problem_scorecards_workspace_id'), 'validation_problem_scorecards', ['workspace_id'], unique=False)
    op.create_table('validation_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('current_topic', sa.String(length=50), nullable=False),
    sa.Column('workflow_state', sa.String(length=50), nullable=False),
    sa.Column('interview_mode_active', sa.Boolean(), nullable=False),
    sa.Column('fields_status_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_sessions_brain_id'), 'validation_sessions', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_sessions_project_id'), 'validation_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_sessions_workflow_state'), 'validation_sessions', ['workflow_state'], unique=False)
    op.create_index(op.f('ix_validation_sessions_workspace_id'), 'validation_sessions', ['workspace_id'], unique=False)
    op.create_table('structured_claims',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('predicate', sa.String(length=100), nullable=False),
    sa.Column('value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('epistemic_type', sa.String(length=50), nullable=False),
    sa.Column('confirmation_status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_actor', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supersedes_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['validation_sessions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_claims_brain_id'), 'structured_claims', ['brain_id'], unique=False)
    op.create_index(op.f('ix_structured_claims_confirmation_status'), 'structured_claims', ['confirmation_status'], unique=False)
    op.create_index(op.f('ix_structured_claims_dimension'), 'structured_claims', ['dimension'], unique=False)
    op.create_index(op.f('ix_structured_claims_epistemic_type'), 'structured_claims', ['epistemic_type'], unique=False)
    op.create_index(op.f('ix_structured_claims_predicate'), 'structured_claims', ['predicate'], unique=False)
    op.create_index(op.f('ix_structured_claims_project_id'), 'structured_claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_structured_claims_session_id'), 'structured_claims', ['session_id'], unique=False)
    op.create_index(op.f('ix_structured_claims_subject'), 'structured_claims', ['subject'], unique=False)
    op.create_index(op.f('ix_structured_claims_supersedes_id'), 'structured_claims', ['supersedes_id'], unique=False)
    op.create_index(op.f('ix_structured_claims_workspace_id'), 'structured_claims', ['workspace_id'], unique=False)
    op.create_table('validation_early_adopters',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=False),
    sa.Column('pain_strength', sa.String(length=50), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=False),
    sa.Column('buying_signal', sa.String(length=50), nullable=False),
    sa.Column('willingness_to_change', sa.String(length=50), nullable=False),
    sa.Column('current_alternative', sa.String(length=255), nullable=True),
    sa.Column('evidence_refs_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['validation_customer_contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_early_adopters_contact_id'), 'validation_early_adopters', ['contact_id'], unique=False)
    op.create_index(op.f('ix_validation_early_adopters_project_id'), 'validation_early_adopters', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_early_adopters_workspace_id'), 'validation_early_adopters', ['workspace_id'], unique=False)
    op.create_table('validation_interview_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('segment', sa.String(length=255), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('raw_notes', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('session_summary', sa.Text(), nullable=True),
    sa.Column('referral_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['validation_customer_contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_interview_sessions_project_id'), 'validation_interview_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_interview_sessions_workspace_id'), 'validation_interview_sessions', ['workspace_id'], unique=False)
    op.create_table('field_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=True),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('old_value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['structured_claims.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_revisions_claim_id'), 'field_revisions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_field_revisions_field_path'), 'field_revisions', ['field_path'], unique=False)
    op.create_index(op.f('ix_field_revisions_project_id'), 'field_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_field_revisions_workspace_id'), 'field_revisions', ['workspace_id'], unique=False)
    op.create_table('validation_assumptions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('claim_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['structured_claims.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_assumptions_brain_id'), 'validation_assumptions', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_assumptions_category'), 'validation_assumptions', ['category'], unique=False)
    op.create_index(op.f('ix_validation_assumptions_claim_id'), 'validation_assumptions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_validation_assumptions_project_id'), 'validation_assumptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_assumptions_risk_score'), 'validation_assumptions', ['risk_score'], unique=False)
    op.create_index(op.f('ix_validation_assumptions_status'), 'validation_assumptions', ['status'], unique=False)
    op.create_index(op.f('ix_validation_assumptions_workspace_id'), 'validation_assumptions', ['workspace_id'], unique=False)
    op.create_table('validation_hypotheses',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('assumption_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_segment', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('threshold', sa.String(length=255), nullable=False),
    sa.Column('timeframe_days', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('quality_gate_passed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['validation_assumptions.id'], ),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_hypotheses_assumption_id'), 'validation_hypotheses', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_validation_hypotheses_brain_id'), 'validation_hypotheses', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_hypotheses_project_id'), 'validation_hypotheses', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_hypotheses_workspace_id'), 'validation_hypotheses', ['workspace_id'], unique=False)
    op.create_table('validation_verbatim_quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_quote', sa.Text(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('interpretation_actor', sa.String(length=50), nullable=False),
    sa.Column('tags_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buying_signal_level', sa.String(length=50), nullable=True),
    sa.Column('linked_assumption_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_assumption_id'], ['validation_assumptions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['validation_interview_sessions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_verbatim_quotes_project_id'), 'validation_verbatim_quotes', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_verbatim_quotes_session_id'), 'validation_verbatim_quotes', ['session_id'], unique=False)
    op.create_index(op.f('ix_validation_verbatim_quotes_workspace_id'), 'validation_verbatim_quotes', ['workspace_id'], unique=False)
    op.create_table('validation_experiments',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('hypothesis_id', sa.BigInteger(), nullable=False),
    sa.Column('experiment_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('smallest_useful_scope', sa.Text(), nullable=True),
    sa.Column('success_threshold', sa.String(length=255), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['validation_hypotheses.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_experiments_brain_id'), 'validation_experiments', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_experiments_experiment_type'), 'validation_experiments', ['experiment_type'], unique=False)
    op.create_index(op.f('ix_validation_experiments_hypothesis_id'), 'validation_experiments', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_validation_experiments_project_id'), 'validation_experiments', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_experiments_status'), 'validation_experiments', ['status'], unique=False)
    op.create_index(op.f('ix_validation_experiments_workspace_id'), 'validation_experiments', ['workspace_id'], unique=False)
    op.create_table('validation_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('hypothesis_id', sa.BigInteger(), nullable=True),
    sa.Column('review_provider_type', sa.String(length=50), nullable=False),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=True),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('supported_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('challenged_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('critical_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_next_action', sa.Text(), nullable=True),
    sa.Column('human_review_recommended', sa.Boolean(), nullable=False),
    sa.Column('raw_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['validation_hypotheses.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_reviews_brain_id'), 'validation_reviews', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_reviews_hypothesis_id'), 'validation_reviews', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_validation_reviews_project_id'), 'validation_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_reviews_review_provider_type'), 'validation_reviews', ['review_provider_type'], unique=False)
    op.create_index(op.f('ix_validation_reviews_verdict'), 'validation_reviews', ['verdict'], unique=False)
    op.create_index(op.f('ix_validation_reviews_workspace_id'), 'validation_reviews', ['workspace_id'], unique=False)
    op.create_table('validation_decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_recommendation', sa.String(length=50), nullable=True),
    sa.Column('human_expert_review', sa.String(length=50), nullable=True),
    sa.Column('founder_decision', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('risks_acknowledged', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['validation_reviews.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_decisions_brain_id'), 'validation_decisions', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_decisions_founder_decision'), 'validation_decisions', ['founder_decision'], unique=False)
    op.create_index(op.f('ix_validation_decisions_project_id'), 'validation_decisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_decisions_workspace_id'), 'validation_decisions', ['workspace_id'], unique=False)
    op.create_table('validation_evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('assumption_id', sa.BigInteger(), nullable=True),
    sa.Column('hypothesis_id', sa.BigInteger(), nullable=True),
    sa.Column('experiment_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=True),
    sa.Column('metric_value', sa.String(length=100), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attachments_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['validation_assumptions.id'], ),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['validation_experiments.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['validation_hypotheses.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_evidence_assumption_id'), 'validation_evidence', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_validation_evidence_brain_id'), 'validation_evidence', ['brain_id'], unique=False)
    op.create_index(op.f('ix_validation_evidence_evidence_type'), 'validation_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_validation_evidence_experiment_id'), 'validation_evidence', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_validation_evidence_hypothesis_id'), 'validation_evidence', ['hypothesis_id'], unique=False)
    op.create_index(op.f('ix_validation_evidence_project_id'), 'validation_evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_validation_evidence_relationship'), 'validation_evidence', ['relationship'], unique=False)
    op.create_index(op.f('ix_validation_evidence_workspace_id'), 'validation_evidence', ['workspace_id'], unique=False)
    op.alter_column('agent_aliases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_aliases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_agent_aliases_id'), 'agent_aliases', ['id'], unique=False)
    op.alter_column('capability_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('founder_decisions', 'decided_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('founder_decisions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('founder_decisions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_founder_decisions_id'), 'founder_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_local_entitlement_snapshots_id'), 'local_entitlement_snapshots', ['id'], unique=False)
    op.alter_column('marketing_decisions', 'based_on_assumption_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('marketing_decisions', 'based_on_evidence_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('marketing_experiments', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('marketing_experiments', 'requires_external_action',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('marketing_learnings', 'affected_assumption_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('marketing_learnings', 'evidence_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_offerings_workspace_unit_status'), table_name='offerings')
    op.create_index(op.f('ix_offerings_operating_unit_id'), 'offerings', ['operating_unit_id'], unique=False)
    op.create_index(op.f('ix_offerings_status'), 'offerings', ['status'], unique=False)
    op.create_index(op.f('ix_offerings_workspace_id'), 'offerings', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_operating_units_workspace_status'), table_name='operating_units')
    op.create_index(op.f('ix_operating_units_status'), 'operating_units', ['status'], unique=False)
    op.create_index(op.f('ix_operating_units_workspace_id'), 'operating_units', ['workspace_id'], unique=False)
    op.alter_column('pestel_signals', 'dimension',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pestel_signals', 'impact_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pestel_signals', 'time_horizon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pestel_signals', 'stage_captured',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_platform_inbox_id'), 'platform_inbox', ['id'], unique=False)
    op.drop_index(op.f('ix_platform_outbox_status'), table_name='platform_outbox')
    op.create_index(op.f('ix_platform_outbox_id'), 'platform_outbox', ['id'], unique=False)
    op.alter_column('projects', 'project_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'S1_PROBLEM_VALIDATION'::character varying"))
    op.alter_column('projects', 'stage_started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'critical_constraints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('projects', 'exit_criteria_jsonb',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('projects', 'stage_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('strategic_decisions', 'alternatives_jsonb',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('strategic_decisions', 'evidence_refs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('strategic_decisions', 'stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('swot_items', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('swot_items', 'evidence_refs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('swot_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tows_options', 'linked_strength_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tows_options', 'linked_weakness_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tows_options', 'linked_opportunity_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tows_options', 'linked_threat_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tows_options', 'tactics_12wy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('tows_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('twelve_week_cycles', 'vision_statement',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('twelve_week_cycles', 'stage_at_start',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('twelve_week_cycles', 'current_week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('twelve_week_cycles', 'overall_execution_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('workspaces', 'company_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'company_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('twelve_week_cycles', 'overall_execution_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('twelve_week_cycles', 'current_week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('twelve_week_cycles', 'stage_at_start',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('twelve_week_cycles', 'vision_statement',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tows_options', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tows_options', 'tactics_12wy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tows_options', 'linked_threat_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tows_options', 'linked_opportunity_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tows_options', 'linked_weakness_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('tows_options', 'linked_strength_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('swot_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('swot_items', 'evidence_refs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('swot_items', 'importance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('strategic_decisions', 'stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('strategic_decisions', 'evidence_refs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('strategic_decisions', 'alternatives_jsonb',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('projects', 'stage_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('projects', 'exit_criteria_jsonb',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('projects', 'critical_constraints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('projects', 'stage_started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'project_stage',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'S1_PROBLEM_VALIDATION'::character varying"))
    op.drop_index(op.f('ix_platform_outbox_id'), table_name='platform_outbox')
    op.create_index(op.f('ix_platform_outbox_status'), 'platform_outbox', ['status'], unique=False)
    op.drop_index(op.f('ix_platform_inbox_id'), table_name='platform_inbox')
    op.alter_column('pestel_signals', 'stage_captured',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('pestel_signals', 'time_horizon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('pestel_signals', 'impact_level',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('pestel_signals', 'dimension',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_operating_units_workspace_id'), table_name='operating_units')
    op.drop_index(op.f('ix_operating_units_status'), table_name='operating_units')
    op.create_index(op.f('ix_operating_units_workspace_status'), 'operating_units', ['workspace_id', 'status'], unique=False)
    op.drop_index(op.f('ix_offerings_workspace_id'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_status'), table_name='offerings')
    op.drop_index(op.f('ix_offerings_operating_unit_id'), table_name='offerings')
    op.create_index(op.f('ix_offerings_workspace_unit_status'), 'offerings', ['workspace_id', 'operating_unit_id', 'status'], unique=False)
    op.alter_column('marketing_learnings', 'evidence_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('marketing_learnings', 'affected_assumption_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('marketing_experiments', 'requires_external_action',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('marketing_experiments', 'method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('marketing_decisions', 'based_on_evidence_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('marketing_decisions', 'based_on_assumption_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_local_entitlement_snapshots_id'), table_name='local_entitlement_snapshots')
    op.drop_index(op.f('ix_founder_decisions_id'), table_name='founder_decisions')
    op.alter_column('founder_decisions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('founder_decisions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('founder_decisions', 'decided_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('capability_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_agent_aliases_id'), table_name='agent_aliases')
    op.alter_column('agent_aliases', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('agent_aliases', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_validation_evidence_workspace_id'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_relationship'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_project_id'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_hypothesis_id'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_experiment_id'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_evidence_type'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_brain_id'), table_name='validation_evidence')
    op.drop_index(op.f('ix_validation_evidence_assumption_id'), table_name='validation_evidence')
    op.drop_table('validation_evidence')
    op.drop_index(op.f('ix_validation_decisions_workspace_id'), table_name='validation_decisions')
    op.drop_index(op.f('ix_validation_decisions_project_id'), table_name='validation_decisions')
    op.drop_index(op.f('ix_validation_decisions_founder_decision'), table_name='validation_decisions')
    op.drop_index(op.f('ix_validation_decisions_brain_id'), table_name='validation_decisions')
    op.drop_table('validation_decisions')
    op.drop_index(op.f('ix_validation_reviews_workspace_id'), table_name='validation_reviews')
    op.drop_index(op.f('ix_validation_reviews_verdict'), table_name='validation_reviews')
    op.drop_index(op.f('ix_validation_reviews_review_provider_type'), table_name='validation_reviews')
    op.drop_index(op.f('ix_validation_reviews_project_id'), table_name='validation_reviews')
    op.drop_index(op.f('ix_validation_reviews_hypothesis_id'), table_name='validation_reviews')
    op.drop_index(op.f('ix_validation_reviews_brain_id'), table_name='validation_reviews')
    op.drop_table('validation_reviews')
    op.drop_index(op.f('ix_validation_experiments_workspace_id'), table_name='validation_experiments')
    op.drop_index(op.f('ix_validation_experiments_status'), table_name='validation_experiments')
    op.drop_index(op.f('ix_validation_experiments_project_id'), table_name='validation_experiments')
    op.drop_index(op.f('ix_validation_experiments_hypothesis_id'), table_name='validation_experiments')
    op.drop_index(op.f('ix_validation_experiments_experiment_type'), table_name='validation_experiments')
    op.drop_index(op.f('ix_validation_experiments_brain_id'), table_name='validation_experiments')
    op.drop_table('validation_experiments')
    op.drop_index(op.f('ix_validation_verbatim_quotes_workspace_id'), table_name='validation_verbatim_quotes')
    op.drop_index(op.f('ix_validation_verbatim_quotes_session_id'), table_name='validation_verbatim_quotes')
    op.drop_index(op.f('ix_validation_verbatim_quotes_project_id'), table_name='validation_verbatim_quotes')
    op.drop_table('validation_verbatim_quotes')
    op.drop_index(op.f('ix_validation_hypotheses_workspace_id'), table_name='validation_hypotheses')
    op.drop_index(op.f('ix_validation_hypotheses_project_id'), table_name='validation_hypotheses')
    op.drop_index(op.f('ix_validation_hypotheses_brain_id'), table_name='validation_hypotheses')
    op.drop_index(op.f('ix_validation_hypotheses_assumption_id'), table_name='validation_hypotheses')
    op.drop_table('validation_hypotheses')
    op.drop_index(op.f('ix_validation_assumptions_workspace_id'), table_name='validation_assumptions')
    op.drop_index(op.f('ix_validation_assumptions_status'), table_name='validation_assumptions')
    op.drop_index(op.f('ix_validation_assumptions_risk_score'), table_name='validation_assumptions')
    op.drop_index(op.f('ix_validation_assumptions_project_id'), table_name='validation_assumptions')
    op.drop_index(op.f('ix_validation_assumptions_claim_id'), table_name='validation_assumptions')
    op.drop_index(op.f('ix_validation_assumptions_category'), table_name='validation_assumptions')
    op.drop_index(op.f('ix_validation_assumptions_brain_id'), table_name='validation_assumptions')
    op.drop_table('validation_assumptions')
    op.drop_index(op.f('ix_field_revisions_workspace_id'), table_name='field_revisions')
    op.drop_index(op.f('ix_field_revisions_project_id'), table_name='field_revisions')
    op.drop_index(op.f('ix_field_revisions_field_path'), table_name='field_revisions')
    op.drop_index(op.f('ix_field_revisions_claim_id'), table_name='field_revisions')
    op.drop_table('field_revisions')
    op.drop_index(op.f('ix_validation_interview_sessions_workspace_id'), table_name='validation_interview_sessions')
    op.drop_index(op.f('ix_validation_interview_sessions_project_id'), table_name='validation_interview_sessions')
    op.drop_table('validation_interview_sessions')
    op.drop_index(op.f('ix_validation_early_adopters_workspace_id'), table_name='validation_early_adopters')
    op.drop_index(op.f('ix_validation_early_adopters_project_id'), table_name='validation_early_adopters')
    op.drop_index(op.f('ix_validation_early_adopters_contact_id'), table_name='validation_early_adopters')
    op.drop_table('validation_early_adopters')
    op.drop_index(op.f('ix_structured_claims_workspace_id'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_supersedes_id'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_subject'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_session_id'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_project_id'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_predicate'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_epistemic_type'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_dimension'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_confirmation_status'), table_name='structured_claims')
    op.drop_index(op.f('ix_structured_claims_brain_id'), table_name='structured_claims')
    op.drop_table('structured_claims')
    op.drop_index(op.f('ix_validation_sessions_workspace_id'), table_name='validation_sessions')
    op.drop_index(op.f('ix_validation_sessions_workflow_state'), table_name='validation_sessions')
    op.drop_index(op.f('ix_validation_sessions_project_id'), table_name='validation_sessions')
    op.drop_index(op.f('ix_validation_sessions_brain_id'), table_name='validation_sessions')
    op.drop_table('validation_sessions')
    op.drop_index(op.f('ix_validation_problem_scorecards_workspace_id'), table_name='validation_problem_scorecards')
    op.drop_index(op.f('ix_validation_problem_scorecards_project_id'), table_name='validation_problem_scorecards')
    op.drop_table('validation_problem_scorecards')
    op.drop_index(op.f('ix_validation_pain_patterns_workspace_id'), table_name='validation_pain_patterns')
    op.drop_index(op.f('ix_validation_pain_patterns_project_id'), table_name='validation_pain_patterns')
    op.drop_index(op.f('ix_validation_pain_patterns_cluster_type'), table_name='validation_pain_patterns')
    op.drop_table('validation_pain_patterns')
    op.drop_index(op.f('ix_validation_customer_contacts_workspace_id'), table_name='validation_customer_contacts')
    op.drop_index(op.f('ix_validation_customer_contacts_role'), table_name='validation_customer_contacts')
    op.drop_index(op.f('ix_validation_customer_contacts_project_id'), table_name='validation_customer_contacts')
    op.drop_table('validation_customer_contacts')
    op.drop_index(op.f('ix_project_stage_history_workspace_id'), table_name='project_stage_history')
    op.drop_index(op.f('ix_project_stage_history_project_id'), table_name='project_stage_history')
    op.drop_table('project_stage_history')
    op.drop_index(op.f('ix_dimension_states_workspace_id'), table_name='dimension_states')
    op.drop_index(op.f('ix_dimension_states_state'), table_name='dimension_states')
    op.drop_index(op.f('ix_dimension_states_project_id'), table_name='dimension_states')
    op.drop_index(op.f('ix_dimension_states_dimension'), table_name='dimension_states')
    op.drop_table('dimension_states')
    op.drop_index(op.f('ix_extension_registrations_id'), table_name='extension_registrations')
    op.drop_table('extension_registrations')
    # ### end Alembic commands ###
