"""add_task_idempotency_key

Revision ID: bf752f63ca3e
Revises: 53daa6ebf13d
Create Date: 2026-08-09 08:06:57.713536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf752f63ca3e'
down_revision: Union[str, Sequence[str], None] = '53daa6ebf13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uix_task_workspace_idempotency_key', 'tasks', ['workspace_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_task_workspace_idempotency_key', 'tasks', type_='unique')
    op.drop_column('tasks', 'idempotency_key')
    # ### end Alembic commands ###
