"""Fix AIRun columns

Revision ID: bfe783bb6375
Revises: b13db2f78fcd
Create Date: 2026-08-09 08:01:25.375326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe783bb6375'
down_revision: Union[str, Sequence[str], None] = 'b13db2f78fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('ai_runs', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_runs', 'created_at')
    op.drop_column('ai_runs', 'cost_estimate')
    # ### end Alembic commands ###
