"""Phase 2B strategy models

Revision ID: db5ef3f5199b
Revises: b09231eca17c
Create Date: 2026-08-09 07:54:48.730693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db5ef3f5199b'
down_revision: Union[str, Sequence[str], None] = 'b09231eca17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_packs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_packs_workspace_id'), 'context_packs', ['workspace_id'], unique=False)
    op.create_table('okr_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('from_entity_type', sa.String(length=50), nullable=False),
    sa.Column('from_entity_id', sa.Uuid(), nullable=False),
    sa.Column('to_entity_type', sa.String(length=50), nullable=False),
    sa.Column('to_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_okr_links_from_entity_id'), 'okr_links', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_okr_links_to_entity_id'), 'okr_links', ['to_entity_id'], unique=False)
    op.create_index(op.f('ix_okr_links_workspace_id'), 'okr_links', ['workspace_id'], unique=False)
    op.create_table('context_pack_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('context_pack_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('citation_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('included_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['context_pack_id'], ['context_packs.id'], ),
    sa.ForeignKeyConstraint(['included_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_pack_sources_context_pack_id'), 'context_pack_sources', ['context_pack_id'], unique=False)
    op.create_index(op.f('ix_context_pack_sources_revision_id'), 'context_pack_sources', ['revision_id'], unique=False)
    op.create_index(op.f('ix_context_pack_sources_workspace_id'), 'context_pack_sources', ['workspace_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('cadence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_brain_id'), 'metrics', ['brain_id'], unique=False)
    op.create_index(op.f('ix_metrics_workspace_id'), 'metrics', ['workspace_id'], unique=False)
    op.create_table('okr_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_okr_cycles_brain_id'), 'okr_cycles', ['brain_id'], unique=False)
    op.create_index(op.f('ix_okr_cycles_workspace_id'), 'okr_cycles', ['workspace_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('current_gate', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_brain_id'), 'projects', ['brain_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('strategy_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('context_pack_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_revision_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_pack_id'], ['context_packs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_analyses_context_pack_id'), 'strategy_analyses', ['context_pack_id'], unique=False)
    op.create_index(op.f('ix_strategy_analyses_workspace_id'), 'strategy_analyses', ['workspace_id'], unique=False)
    op.create_table('strategy_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_profiles_brain_id'), 'strategy_profiles', ['brain_id'], unique=False)
    op.create_index(op.f('ix_strategy_profiles_workspace_id'), 'strategy_profiles', ['workspace_id'], unique=False)
    op.create_table('bsc_scorecards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_profile_id', sa.Uuid(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_profile_id'], ['strategy_profiles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bsc_scorecards_strategy_profile_id'), 'bsc_scorecards', ['strategy_profile_id'], unique=False)
    op.create_index(op.f('ix_bsc_scorecards_workspace_id'), 'bsc_scorecards', ['workspace_id'], unique=False)
    op.create_table('initiatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiatives_brain_id'), 'initiatives', ['brain_id'], unique=False)
    op.create_index(op.f('ix_initiatives_workspace_id'), 'initiatives', ['workspace_id'], unique=False)
    op.create_table('metric_checkins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('as_of_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('entered_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_checkins_metric_id'), 'metric_checkins', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metric_checkins_workspace_id'), 'metric_checkins', ['workspace_id'], unique=False)
    op.create_table('pestel_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('factor', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=50), nullable=False),
    sa.Column('horizon', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['strategy_analyses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pestel_items_analysis_id'), 'pestel_items', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_pestel_items_workspace_id'), 'pestel_items', ['workspace_id'], unique=False)
    op.create_table('swot_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=50), nullable=False),
    sa.Column('likelihood', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('evidence_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['strategy_analyses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swot_items_analysis_id'), 'swot_items', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_swot_items_workspace_id'), 'swot_items', ['workspace_id'], unique=False)
    op.create_table('tows_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('quadrant', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('tradeoffs', sa.Text(), nullable=False),
    sa.Column('expected_impact', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['strategy_analyses.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tows_options_analysis_id'), 'tows_options', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_tows_options_workspace_id'), 'tows_options', ['workspace_id'], unique=False)
    op.create_table('twelve_week_cycles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('okr_cycle_id', sa.Uuid(), nullable=True),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('commitment_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['okr_cycle_id'], ['okr_cycles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twelve_week_cycles_brain_id'), 'twelve_week_cycles', ['brain_id'], unique=False)
    op.create_index(op.f('ix_twelve_week_cycles_workspace_id'), 'twelve_week_cycles', ['workspace_id'], unique=False)
    op.create_table('strategic_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brain_id', sa.Uuid(), nullable=False),
    sa.Column('context_pack_id', sa.Uuid(), nullable=False),
    sa.Column('tows_option_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('rationale_revision_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['context_pack_id'], ['context_packs.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tows_option_id'], ['tows_options.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_decisions_brain_id'), 'strategic_decisions', ['brain_id'], unique=False)
    op.create_index(op.f('ix_strategic_decisions_context_pack_id'), 'strategic_decisions', ['context_pack_id'], unique=False)
    op.create_index(op.f('ix_strategic_decisions_workspace_id'), 'strategic_decisions', ['workspace_id'], unique=False)
    op.create_table('strategic_objectives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scorecard_id', sa.Uuid(), nullable=False),
    sa.Column('perspective', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scorecard_id'], ['bsc_scorecards.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_objectives_scorecard_id'), 'strategic_objectives', ['scorecard_id'], unique=False)
    op.create_index(op.f('ix_strategic_objectives_workspace_id'), 'strategic_objectives', ['workspace_id'], unique=False)
    op.create_table('weekly_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('execution_score', sa.Float(), nullable=True),
    sa.Column('blockers_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['twelve_week_cycles.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plans_cycle_id'), 'weekly_plans', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_workspace_id'), 'weekly_plans', ['workspace_id'], unique=False)
    op.create_table('okr_objectives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('strategic_objective_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['okr_cycles.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategic_objective_id'], ['strategic_objectives.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_okr_objectives_cycle_id'), 'okr_objectives', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_okr_objectives_workspace_id'), 'okr_objectives', ['workspace_id'], unique=False)
    op.create_table('strategic_objective_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('from_objective_id', sa.Uuid(), nullable=False),
    sa.Column('to_objective_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_objective_id'], ['strategic_objectives.id'], ),
    sa.ForeignKeyConstraint(['to_objective_id'], ['strategic_objectives.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_objective_links_from_objective_id'), 'strategic_objective_links', ['from_objective_id'], unique=False)
    op.create_index(op.f('ix_strategic_objective_links_to_objective_id'), 'strategic_objective_links', ['to_objective_id'], unique=False)
    op.create_index(op.f('ix_strategic_objective_links_workspace_id'), 'strategic_objective_links', ['workspace_id'], unique=False)
    op.create_table('weekly_commitments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_plan_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('planned_effort', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_commitments_weekly_plan_id'), 'weekly_commitments', ['weekly_plan_id'], unique=False)
    op.create_index(op.f('ix_weekly_commitments_workspace_id'), 'weekly_commitments', ['workspace_id'], unique=False)
    op.create_table('key_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('objective_id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('cadence', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.ForeignKeyConstraint(['objective_id'], ['okr_objectives.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_results_objective_id'), 'key_results', ['objective_id'], unique=False)
    op.create_index(op.f('ix_key_results_workspace_id'), 'key_results', ['workspace_id'], unique=False)
    op.create_table('initiative_key_result_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('initiative_id', sa.Uuid(), nullable=False),
    sa.Column('key_result_id', sa.Uuid(), nullable=False),
    sa.Column('contribution_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['key_result_id'], ['key_results.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_key_result_links_initiative_id'), 'initiative_key_result_links', ['initiative_id'], unique=False)
    op.create_index(op.f('ix_initiative_key_result_links_key_result_id'), 'initiative_key_result_links', ['key_result_id'], unique=False)
    op.create_index(op.f('ix_initiative_key_result_links_workspace_id'), 'initiative_key_result_links', ['workspace_id'], unique=False)
    op.add_column('tasks', sa.Column('initiative_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('weekly_commitment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'weekly_commitments', ['weekly_commitment_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'initiatives', ['initiative_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'weekly_commitment_id')
    op.drop_column('tasks', 'initiative_id')
    op.drop_index(op.f('ix_initiative_key_result_links_workspace_id'), table_name='initiative_key_result_links')
    op.drop_index(op.f('ix_initiative_key_result_links_key_result_id'), table_name='initiative_key_result_links')
    op.drop_index(op.f('ix_initiative_key_result_links_initiative_id'), table_name='initiative_key_result_links')
    op.drop_table('initiative_key_result_links')
    op.drop_index(op.f('ix_key_results_workspace_id'), table_name='key_results')
    op.drop_index(op.f('ix_key_results_objective_id'), table_name='key_results')
    op.drop_table('key_results')
    op.drop_index(op.f('ix_weekly_commitments_workspace_id'), table_name='weekly_commitments')
    op.drop_index(op.f('ix_weekly_commitments_weekly_plan_id'), table_name='weekly_commitments')
    op.drop_table('weekly_commitments')
    op.drop_index(op.f('ix_strategic_objective_links_workspace_id'), table_name='strategic_objective_links')
    op.drop_index(op.f('ix_strategic_objective_links_to_objective_id'), table_name='strategic_objective_links')
    op.drop_index(op.f('ix_strategic_objective_links_from_objective_id'), table_name='strategic_objective_links')
    op.drop_table('strategic_objective_links')
    op.drop_index(op.f('ix_okr_objectives_workspace_id'), table_name='okr_objectives')
    op.drop_index(op.f('ix_okr_objectives_cycle_id'), table_name='okr_objectives')
    op.drop_table('okr_objectives')
    op.drop_index(op.f('ix_weekly_plans_workspace_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_cycle_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_index(op.f('ix_strategic_objectives_workspace_id'), table_name='strategic_objectives')
    op.drop_index(op.f('ix_strategic_objectives_scorecard_id'), table_name='strategic_objectives')
    op.drop_table('strategic_objectives')
    op.drop_index(op.f('ix_strategic_decisions_workspace_id'), table_name='strategic_decisions')
    op.drop_index(op.f('ix_strategic_decisions_context_pack_id'), table_name='strategic_decisions')
    op.drop_index(op.f('ix_strategic_decisions_brain_id'), table_name='strategic_decisions')
    op.drop_table('strategic_decisions')
    op.drop_index(op.f('ix_twelve_week_cycles_workspace_id'), table_name='twelve_week_cycles')
    op.drop_index(op.f('ix_twelve_week_cycles_brain_id'), table_name='twelve_week_cycles')
    op.drop_table('twelve_week_cycles')
    op.drop_index(op.f('ix_tows_options_workspace_id'), table_name='tows_options')
    op.drop_index(op.f('ix_tows_options_analysis_id'), table_name='tows_options')
    op.drop_table('tows_options')
    op.drop_index(op.f('ix_swot_items_workspace_id'), table_name='swot_items')
    op.drop_index(op.f('ix_swot_items_analysis_id'), table_name='swot_items')
    op.drop_table('swot_items')
    op.drop_index(op.f('ix_pestel_items_workspace_id'), table_name='pestel_items')
    op.drop_index(op.f('ix_pestel_items_analysis_id'), table_name='pestel_items')
    op.drop_table('pestel_items')
    op.drop_index(op.f('ix_metric_checkins_workspace_id'), table_name='metric_checkins')
    op.drop_index(op.f('ix_metric_checkins_metric_id'), table_name='metric_checkins')
    op.drop_table('metric_checkins')
    op.drop_index(op.f('ix_initiatives_workspace_id'), table_name='initiatives')
    op.drop_index(op.f('ix_initiatives_brain_id'), table_name='initiatives')
    op.drop_table('initiatives')
    op.drop_index(op.f('ix_bsc_scorecards_workspace_id'), table_name='bsc_scorecards')
    op.drop_index(op.f('ix_bsc_scorecards_strategy_profile_id'), table_name='bsc_scorecards')
    op.drop_table('bsc_scorecards')
    op.drop_index(op.f('ix_strategy_profiles_workspace_id'), table_name='strategy_profiles')
    op.drop_index(op.f('ix_strategy_profiles_brain_id'), table_name='strategy_profiles')
    op.drop_table('strategy_profiles')
    op.drop_index(op.f('ix_strategy_analyses_workspace_id'), table_name='strategy_analyses')
    op.drop_index(op.f('ix_strategy_analyses_context_pack_id'), table_name='strategy_analyses')
    op.drop_table('strategy_analyses')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_brain_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_okr_cycles_workspace_id'), table_name='okr_cycles')
    op.drop_index(op.f('ix_okr_cycles_brain_id'), table_name='okr_cycles')
    op.drop_table('okr_cycles')
    op.drop_index(op.f('ix_metrics_workspace_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_brain_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_context_pack_sources_workspace_id'), table_name='context_pack_sources')
    op.drop_index(op.f('ix_context_pack_sources_revision_id'), table_name='context_pack_sources')
    op.drop_index(op.f('ix_context_pack_sources_context_pack_id'), table_name='context_pack_sources')
    op.drop_table('context_pack_sources')
    op.drop_index(op.f('ix_okr_links_workspace_id'), table_name='okr_links')
    op.drop_index(op.f('ix_okr_links_to_entity_id'), table_name='okr_links')
    op.drop_index(op.f('ix_okr_links_from_entity_id'), table_name='okr_links')
    op.drop_table('okr_links')
    op.drop_index(op.f('ix_context_packs_workspace_id'), table_name='context_packs')
    op.drop_table('context_packs')
    # ### end Alembic commands ###
