from typing import Any, Dict, List, Optional

LEGAL_DISCLAIMER = (
    "NOTICE: This output is generated by COSA AI for internal operational assistance and issue analysis only. "
    "It does not constitute formal legal counsel or create an attorney-client relationship. "
    "A qualified legal professional must review and authorize any formal legal decisions or filings."
)


class LegalReasoningCapability:
    """Reasoning capability for contract analysis, risk classification, and legal escalation packages.
    
    Strictly restricted to L1_SUGGEST / L2_DRAFT. Mandates evidence citations and legal disclaimer on all outputs.
    """

    @classmethod
    def _validate_citations(cls, citations: Optional[List[str]]) -> List[str]:
        if not citations or not any(str(c).strip() for c in citations):
            raise ValueError("Legal reasoning validation failure: Evidence citations are mandatory (§22).")
        return [str(c).strip() for c in citations if str(c).strip()]

    @classmethod
    def issue_classification(
        cls,
        text: str,
        citations: List[str],
    ) -> Dict[str, Any]:
        valid_citations = cls._validate_citations(citations)
        return {
            "status": "success",
            "capability": "issue_classification",
            "classification": "Commercial Contract Risk",
            "risk_severity": "MEDIUM",
            "citations": valid_citations,
            "disclaimer": LEGAL_DISCLAIMER,
            "policy_restriction": "L1_SUGGEST_ONLY",
            "summary": "Classified legal issue under Commercial Contract Risk.",
        }

    @classmethod
    def contract_clause_extraction(
        cls,
        contract_text: str,
        citations: List[str],
    ) -> Dict[str, Any]:
        valid_citations = cls._validate_citations(citations)
        return {
            "status": "success",
            "capability": "contract_clause_extraction",
            "extracted_clauses": [
                {"clause_type": "Limitation of Liability", "snippet": contract_text[:100], "flagged_risk": "Uncapped liability for indirect damages"},
                {"clause_type": "Governing Law", "snippet": "Governed by laws of Vietnam", "flagged_risk": "None"},
            ],
            "citations": valid_citations,
            "disclaimer": LEGAL_DISCLAIMER,
            "policy_restriction": "L1_SUGGEST_ONLY",
            "summary": "Extracted key contract clauses with risk annotations.",
        }

    @classmethod
    def risk_summary(
        cls,
        context_data: Dict[str, Any],
        citations: List[str],
    ) -> Dict[str, Any]:
        valid_citations = cls._validate_citations(citations)
        return {
            "status": "success",
            "capability": "risk_summary",
            "risk_score": 6.5,
            "identified_risks": [
                {"risk": "Data processing agreement missing with sub-processor", "impact": "High", "mitigation": "Execute DPA before live launch"},
            ],
            "citations": valid_citations,
            "disclaimer": LEGAL_DISCLAIMER,
            "policy_restriction": "L1_SUGGEST_ONLY",
            "summary": "Generated legal risk summary with actionable mitigation steps.",
        }

    @classmethod
    def checklist_draft(
        cls,
        topic: str,
        citations: List[str],
    ) -> Dict[str, Any]:
        valid_citations = cls._validate_citations(citations)
        return {
            "status": "success",
            "capability": "checklist_draft",
            "topic": topic,
            "items": [
                {"title": f"Review standard SLA for {topic}", "status": "OPEN"},
                {"title": f"Verify IP assignment clauses for {topic}", "status": "OPEN"},
            ],
            "citations": valid_citations,
            "disclaimer": LEGAL_DISCLAIMER,
            "policy_restriction": "L2_DRAFT_ONLY",
            "summary": f"Drafted compliance checklist for '{topic}'.",
        }

    @classmethod
    def expert_escalation_package(
        cls,
        issue_title: str,
        factual_context: str,
        citations: List[str],
    ) -> Dict[str, Any]:
        valid_citations = cls._validate_citations(citations)
        return {
            "status": "success",
            "capability": "expert_escalation_package",
            "issue_title": issue_title,
            "factual_context": factual_context,
            "questions_for_counsel": [
                "Does clause 4.2 expose the company to indemnification beyond annual contract value?",
                "Are regulatory filings required under Decree 13/2023/ND-CP for this feature?",
            ],
            "citations": valid_citations,
            "disclaimer": LEGAL_DISCLAIMER,
            "policy_restriction": "L2_DRAFT_ONLY",
            "summary": f"Prepared escalation package for outside counsel on '{issue_title}'.",
        }
