# All Startup/Validation models moved to core/validation/ (COSA Structure.md §49
# Business Core migration). Re-exported here for backward compatibility with
# existing `from app.founder_os.validation.models import ...` call sites.
from core.validation.models import (  # noqa: F401
    ProjectStage,
    ValidationWorkflowState,
    EpistemicType,
    ClaimConfirmationStatus,
    DimensionName,
    DimensionStateEnum,
    FeasibilityPillar,
    AssumptionCategory,
    AssumptionStatus,
    ExperimentType,
    EvidenceType,
    QuestionTypeEnum,
    BuyingSignalLevelEnum,
    CustomerRoleEnum,
    ICPLifecycleState,
    AutopsyClusterType,
    ProblemValidationResultEnum,
    EvidenceRelationship,
    ReviewProviderType,
    ReviewVerdict,
    FounderDecisionEnum,
    ValidationSession,
    StructuredClaim,
    FieldRevision,
    DimensionState,
    ProjectStageHistory,
    ValidationAssumption,
    ValidationHypothesis,
    ValidationExperiment,
    ValidationEvidence,
    ValidationReview,
    ValidationDecision,
    CustomerContact,
    CustomerInterviewSession,
    VerbatimQuote,
    ProblemSeverityScorecard,
    PainPattern,
    EarlyAdopterCandidate,
)
