"""add_escalation_records_phase6

Revision ID: 5a2db44a5acd
Revises: 34e87711c422
Create Date: 2026-08-18 18:22:50.746126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a2db44a5acd'
down_revision: Union[str, Sequence[str], None] = '34e87711c422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_records',
    sa.Column('workspace_id', sa.BigInteger(), nullable=True),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('agent_key', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('stage_code', sa.String(length=20), nullable=True),
    sa.Column('details_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_action', sa.String(length=50), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalation_records_agent_key'), 'escalation_records', ['agent_key'], unique=False)
    op.create_index(op.f('ix_escalation_records_created_at'), 'escalation_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_escalation_records_exception_type'), 'escalation_records', ['exception_type'], unique=False)
    op.create_index(op.f('ix_escalation_records_id'), 'escalation_records', ['id'], unique=False)
    op.create_index(op.f('ix_escalation_records_run_id'), 'escalation_records', ['run_id'], unique=False)
    op.create_index(op.f('ix_escalation_records_status'), 'escalation_records', ['status'], unique=False)
    op.create_index(op.f('ix_escalation_records_tier'), 'escalation_records', ['tier'], unique=False)
    op.create_index(op.f('ix_escalation_records_workspace_id'), 'escalation_records', ['workspace_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('canvas_id', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Integer(), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experiment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assumptions_brain_id'), 'assumptions', ['brain_id'], unique=False)
    op.create_index(op.f('ix_assumptions_canvas_id'), 'assumptions', ['canvas_id'], unique=False)
    op.create_index(op.f('ix_assumptions_category'), 'assumptions', ['category'], unique=False)
    op.create_index(op.f('ix_assumptions_criticality'), 'assumptions', ['criticality'], unique=False)
    op.create_index(op.f('ix_assumptions_project_id'), 'assumptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_assumptions_status'), 'assumptions', ['status'], unique=False)
    op.create_index(op.f('ix_assumptions_workspace_id'), 'assumptions', ['workspace_id'], unique=False)
    op.create_table('bsc_goals',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('perspective', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('kpi_name', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.String(length=100), nullable=False),
    sa.Column('initiatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bsc_goals_perspective'), 'bsc_goals', ['perspective'], unique=False)
    op.create_index(op.f('ix_bsc_goals_project_id'), 'bsc_goals', ['project_id'], unique=False)
    op.create_index(op.f('ix_bsc_goals_workspace_id'), 'bsc_goals', ['workspace_id'], unique=False)
    op.create_table('canvas_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('canvas_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_revisions_brain_id'), 'canvas_revisions', ['brain_id'], unique=False)
    op.create_index(op.f('ix_canvas_revisions_canvas_type'), 'canvas_revisions', ['canvas_type'], unique=False)
    op.create_index(op.f('ix_canvas_revisions_project_id'), 'canvas_revisions', ['project_id'], unique=False)
    op.create_index(op.f('ix_canvas_revisions_workspace_id'), 'canvas_revisions', ['workspace_id'], unique=False)
    op.create_table('customer_interviews',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('segment', sa.String(length=255), nullable=False),
    sa.Column('interview_date', sa.DateTime(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alternatives', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('objections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('willingness_to_pay', sa.Text(), nullable=True),
    sa.Column('notable_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interviews_brain_id'), 'customer_interviews', ['brain_id'], unique=False)
    op.create_index(op.f('ix_customer_interviews_contact_id'), 'customer_interviews', ['contact_id'], unique=False)
    op.create_index(op.f('ix_customer_interviews_project_id'), 'customer_interviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_customer_interviews_workspace_id'), 'customer_interviews', ['workspace_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('supports_assumption_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradicts_assumption_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_brain_id'), 'evidence', ['brain_id'], unique=False)
    op.create_index(op.f('ix_evidence_project_id'), 'evidence', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_type'), 'evidence', ['source_type'], unique=False)
    op.create_index(op.f('ix_evidence_workspace_id'), 'evidence', ['workspace_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('ladder_level', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('claim_supported', sa.Text(), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('hypothesis_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_ladder_level'), 'evidences', ['ladder_level'], unique=False)
    op.create_index(op.f('ix_evidences_project_id'), 'evidences', ['project_id'], unique=False)
    op.create_index(op.f('ix_evidences_type'), 'evidences', ['type'], unique=False)
    op.create_index(op.f('ix_evidences_workspace_id'), 'evidences', ['workspace_id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stage_created', sa.String(length=50), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experiment_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_category'), 'hypotheses', ['category'], unique=False)
    op.create_index(op.f('ix_hypotheses_project_id'), 'hypotheses', ['project_id'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_index(op.f('ix_hypotheses_workspace_id'), 'hypotheses', ['workspace_id'], unique=False)
    op.create_table('knowledge_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_statements_brain_id'), 'knowledge_statements', ['brain_id'], unique=False)
    op.create_index(op.f('ix_knowledge_statements_epistemic_status'), 'knowledge_statements', ['epistemic_status'], unique=False)
    op.create_index(op.f('ix_knowledge_statements_project_id'), 'knowledge_statements', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledge_statements_workspace_id'), 'knowledge_statements', ['workspace_id'], unique=False)
    op.create_table('premature_scaling_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premature_scaling_alerts_project_id'), 'premature_scaling_alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_premature_scaling_alerts_workspace_id'), 'premature_scaling_alerts', ['workspace_id'], unique=False)
    op.create_table('stage_transition_audits',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('audit_status', sa.String(length=50), nullable=False),
    sa.Column('passed_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('audited_by_agent', sa.String(length=100), nullable=False),
    sa.Column('recommendation_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transition_audits_project_id'), 'stage_transition_audits', ['project_id'], unique=False)
    op.create_index(op.f('ix_stage_transition_audits_workspace_id'), 'stage_transition_audits', ['workspace_id'], unique=False)
    op.create_table('weekly_accountability_reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('execution_score', sa.Float(), nullable=False),
    sa.Column('total_planned', sa.Integer(), nullable=False),
    sa.Column('total_completed', sa.Integer(), nullable=False),
    sa.Column('key_breakthroughs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('root_cause_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['twelve_week_cycles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_accountability_reviews_cycle_id'), 'weekly_accountability_reviews', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_weekly_accountability_reviews_project_id'), 'weekly_accountability_reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_weekly_accountability_reviews_workspace_id'), 'weekly_accountability_reviews', ['workspace_id'], unique=False)
    op.create_table('tactical_execution_items',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tows_option_id', sa.BigInteger(), nullable=True),
    sa.Column('hypothesis_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_indicator_name', sa.String(length=255), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('actual_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_role', sa.String(length=100), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['twelve_week_cycles.id'], ),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['tows_option_id'], ['tows_options.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tactical_execution_items_cycle_id'), 'tactical_execution_items', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_tactical_execution_items_project_id'), 'tactical_execution_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_tactical_execution_items_week_number'), 'tactical_execution_items', ['week_number'], unique=False)
    op.create_index(op.f('ix_tactical_execution_items_workspace_id'), 'tactical_execution_items', ['workspace_id'], unique=False)
    op.create_table('marketing_attributions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('experiment_id', sa.BigInteger(), nullable=True),
    sa.Column('variant_id', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['marketing_experiments.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_attributions_campaign_id'), 'marketing_attributions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_marketing_attributions_contact_id'), 'marketing_attributions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_marketing_attributions_experiment_id'), 'marketing_attributions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_marketing_attributions_lead_id'), 'marketing_attributions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_marketing_attributions_workspace_id'), 'marketing_attributions', ['workspace_id'], unique=False)
    op.add_column('marketing_campaigns', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_marketing_campaigns_project_id'), 'marketing_campaigns', ['project_id'], unique=False)
    op.create_foreign_key(None, 'marketing_campaigns', 'projects', ['project_id'], ['id'])
    op.add_column('marketing_contexts', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('marketing_contexts', sa.Column('duration_weeks', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_marketing_contexts_project_id'), 'marketing_contexts', ['project_id'], unique=False)
    op.create_foreign_key(None, 'marketing_contexts', 'projects', ['project_id'], ['id'])
    op.add_column('marketing_decisions', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('marketing_decisions', sa.Column('experiment_id', sa.BigInteger(), nullable=True))
    op.add_column('marketing_decisions', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('marketing_decisions', sa.Column('based_on_assumption_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketing_decisions', sa.Column('based_on_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketing_decisions', sa.Column('next_action', sa.Text(), nullable=True))
    op.add_column('marketing_decisions', sa.Column('owner', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_marketing_decisions_experiment_id'), 'marketing_decisions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_marketing_decisions_project_id'), 'marketing_decisions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'marketing_decisions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'marketing_decisions', 'marketing_experiments', ['experiment_id'], ['id'])
    op.add_column('marketing_experiments', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('marketing_experiments', sa.Column('assumption_id', sa.BigInteger(), nullable=True))
    op.add_column('marketing_experiments', sa.Column('method', sa.String(length=50), nullable=True))
    op.add_column('marketing_experiments', sa.Column('success_threshold', sa.String(length=255), nullable=True))
    op.add_column('marketing_experiments', sa.Column('minimum_sample', sa.Integer(), nullable=True))
    op.add_column('marketing_experiments', sa.Column('timebox_days', sa.Integer(), nullable=True))
    op.add_column('marketing_experiments', sa.Column('requires_external_action', sa.Boolean(), nullable=True))
    op.add_column('marketing_experiments', sa.Column('conclusion', sa.String(length=50), nullable=True))
    op.add_column('marketing_experiments', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('marketing_experiments', 'variant_a',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('marketing_experiments', 'variant_b',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_marketing_experiments_assumption_id'), 'marketing_experiments', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_marketing_experiments_project_id'), 'marketing_experiments', ['project_id'], unique=False)
    op.create_foreign_key(None, 'marketing_experiments', 'assumptions', ['assumption_id'], ['id'])
    op.create_foreign_key(None, 'marketing_experiments', 'projects', ['project_id'], ['id'])
    op.add_column('marketing_learnings', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('marketing_learnings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('marketing_learnings', sa.Column('affected_assumption_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketing_learnings', sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('marketing_learnings', sa.Column('decision_recommendation', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_marketing_learnings_project_id'), 'marketing_learnings', ['project_id'], unique=False)
    op.create_foreign_key(None, 'marketing_learnings', 'projects', ['project_id'], ['id'])
    op.add_column('marketing_objectives', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_marketing_objectives_project_id'), 'marketing_objectives', ['project_id'], unique=False)
    op.create_foreign_key(None, 'marketing_objectives', 'projects', ['project_id'], ['id'])
    op.drop_column('model_profile_overrides', 'updated_at')
    op.drop_column('model_profile_overrides', 'created_at')
    op.drop_column('model_profile_overrides', 'is_active')
    op.add_column('pestel_signals', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('pestel_signals', sa.Column('dimension', sa.String(length=50), nullable=True))
    op.add_column('pestel_signals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('pestel_signals', sa.Column('impact_level', sa.String(length=50), nullable=True))
    op.add_column('pestel_signals', sa.Column('time_horizon', sa.String(length=50), nullable=True))
    op.add_column('pestel_signals', sa.Column('resulting_hypothesis_id', sa.BigInteger(), nullable=True))
    op.add_column('pestel_signals', sa.Column('stage_captured', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_pestel_signals_dimension'), 'pestel_signals', ['dimension'], unique=False)
    op.create_index(op.f('ix_pestel_signals_project_id'), 'pestel_signals', ['project_id'], unique=False)
    op.create_foreign_key(None, 'pestel_signals', 'projects', ['project_id'], ['id'])
    op.add_column('projects', sa.Column('project_stage', sa.String(length=50), nullable=True, server_default='S1_PROBLEM_VALIDATION'))
    op.add_column('projects', sa.Column('stage_started_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('stage_goal', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('critical_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('exit_criteria_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('stage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_projects_project_stage'), 'projects', ['project_stage'], unique=False)
    op.add_column('strategic_decisions', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('strategic_decisions', sa.Column('question', sa.Text(), nullable=True))
    op.add_column('strategic_decisions', sa.Column('selected_option', sa.Text(), nullable=True))
    op.add_column('strategic_decisions', sa.Column('alternatives_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('strategic_decisions', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('strategic_decisions', sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('strategic_decisions', sa.Column('stage', sa.String(length=50), nullable=True))
    op.add_column('strategic_decisions', sa.Column('expected_result', sa.Text(), nullable=True))
    op.add_column('strategic_decisions', sa.Column('review_date', sa.DateTime(), nullable=True))
    op.alter_column('strategic_decisions', 'context_pack_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_strategic_decisions_project_id'), 'strategic_decisions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'strategic_decisions', 'projects', ['project_id'], ['id'])
    op.add_column('swot_items', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('swot_items', sa.Column('importance', sa.Float(), nullable=True))
    op.add_column('swot_items', sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('swot_items', sa.Column('pestel_signal_ref', sa.BigInteger(), nullable=True))
    op.add_column('swot_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('swot_items', 'analysis_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_swot_items_project_id'), 'swot_items', ['project_id'], unique=False)
    op.create_foreign_key(None, 'swot_items', 'projects', ['project_id'], ['id'])
    op.add_column('tows_options', sa.Column('project_id', sa.BigInteger(), nullable=True))
    op.add_column('tows_options', sa.Column('linked_strength_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tows_options', sa.Column('linked_weakness_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tows_options', sa.Column('linked_opportunity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tows_options', sa.Column('linked_threat_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tows_options', sa.Column('resulting_hypothesis_id', sa.BigInteger(), nullable=True))
    op.add_column('tows_options', sa.Column('tactics_12wy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tows_options', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('tows_options', 'analysis_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_tows_options_project_id'), 'tows_options', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tows_options', 'projects', ['project_id'], ['id'])
    op.add_column('twelve_week_cycles', sa.Column('vision_statement', sa.Text(), nullable=True))
    op.add_column('twelve_week_cycles', sa.Column('stage_at_start', sa.String(length=50), nullable=True))
    op.add_column('twelve_week_cycles', sa.Column('current_week', sa.Integer(), nullable=True))
    op.add_column('twelve_week_cycles', sa.Column('overall_execution_score', sa.Float(), nullable=True))
    op.add_column('workspaces', sa.Column('company_stage', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'company_stage')
    op.drop_column('twelve_week_cycles', 'overall_execution_score')
    op.drop_column('twelve_week_cycles', 'current_week')
    op.drop_column('twelve_week_cycles', 'stage_at_start')
    op.drop_column('twelve_week_cycles', 'vision_statement')
    op.drop_constraint(None, 'tows_options', type_='foreignkey')
    op.drop_index(op.f('ix_tows_options_project_id'), table_name='tows_options')
    op.alter_column('tows_options', 'analysis_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('tows_options', 'created_at')
    op.drop_column('tows_options', 'tactics_12wy')
    op.drop_column('tows_options', 'resulting_hypothesis_id')
    op.drop_column('tows_options', 'linked_threat_ids')
    op.drop_column('tows_options', 'linked_opportunity_ids')
    op.drop_column('tows_options', 'linked_weakness_ids')
    op.drop_column('tows_options', 'linked_strength_ids')
    op.drop_column('tows_options', 'project_id')
    op.drop_constraint(None, 'swot_items', type_='foreignkey')
    op.drop_index(op.f('ix_swot_items_project_id'), table_name='swot_items')
    op.alter_column('swot_items', 'analysis_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('swot_items', 'created_at')
    op.drop_column('swot_items', 'pestel_signal_ref')
    op.drop_column('swot_items', 'evidence_refs')
    op.drop_column('swot_items', 'importance')
    op.drop_column('swot_items', 'project_id')
    op.drop_constraint(None, 'strategic_decisions', type_='foreignkey')
    op.drop_index(op.f('ix_strategic_decisions_project_id'), table_name='strategic_decisions')
    op.alter_column('strategic_decisions', 'context_pack_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('strategic_decisions', 'review_date')
    op.drop_column('strategic_decisions', 'expected_result')
    op.drop_column('strategic_decisions', 'stage')
    op.drop_column('strategic_decisions', 'evidence_refs')
    op.drop_column('strategic_decisions', 'rationale')
    op.drop_column('strategic_decisions', 'alternatives_jsonb')
    op.drop_column('strategic_decisions', 'selected_option')
    op.drop_column('strategic_decisions', 'question')
    op.drop_column('strategic_decisions', 'project_id')
    op.drop_index(op.f('ix_projects_project_stage'), table_name='projects')
    op.drop_column('projects', 'stage_metadata')
    op.drop_column('projects', 'exit_criteria_jsonb')
    op.drop_column('projects', 'critical_constraints')
    op.drop_column('projects', 'stage_goal')
    op.drop_column('projects', 'stage_started_at')
    op.drop_column('projects', 'project_stage')
    op.drop_constraint(None, 'pestel_signals', type_='foreignkey')
    op.drop_index(op.f('ix_pestel_signals_project_id'), table_name='pestel_signals')
    op.drop_index(op.f('ix_pestel_signals_dimension'), table_name='pestel_signals')
    op.drop_column('pestel_signals', 'stage_captured')
    op.drop_column('pestel_signals', 'resulting_hypothesis_id')
    op.drop_column('pestel_signals', 'time_horizon')
    op.drop_column('pestel_signals', 'impact_level')
    op.drop_column('pestel_signals', 'description')
    op.drop_column('pestel_signals', 'dimension')
    op.drop_column('pestel_signals', 'project_id')
    op.add_column('model_profile_overrides', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('model_profile_overrides', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('model_profile_overrides', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'marketing_objectives', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_objectives_project_id'), table_name='marketing_objectives')
    op.drop_column('marketing_objectives', 'project_id')
    op.drop_constraint(None, 'marketing_learnings', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_learnings_project_id'), table_name='marketing_learnings')
    op.drop_column('marketing_learnings', 'decision_recommendation')
    op.drop_column('marketing_learnings', 'evidence_ids')
    op.drop_column('marketing_learnings', 'affected_assumption_ids')
    op.drop_column('marketing_learnings', 'summary')
    op.drop_column('marketing_learnings', 'project_id')
    op.drop_constraint(None, 'marketing_experiments', type_='foreignkey')
    op.drop_constraint(None, 'marketing_experiments', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_experiments_project_id'), table_name='marketing_experiments')
    op.drop_index(op.f('ix_marketing_experiments_assumption_id'), table_name='marketing_experiments')
    op.alter_column('marketing_experiments', 'variant_b',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('marketing_experiments', 'variant_a',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('marketing_experiments', 'result')
    op.drop_column('marketing_experiments', 'conclusion')
    op.drop_column('marketing_experiments', 'requires_external_action')
    op.drop_column('marketing_experiments', 'timebox_days')
    op.drop_column('marketing_experiments', 'minimum_sample')
    op.drop_column('marketing_experiments', 'success_threshold')
    op.drop_column('marketing_experiments', 'method')
    op.drop_column('marketing_experiments', 'assumption_id')
    op.drop_column('marketing_experiments', 'project_id')
    op.drop_constraint(None, 'marketing_decisions', type_='foreignkey')
    op.drop_constraint(None, 'marketing_decisions', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_decisions_project_id'), table_name='marketing_decisions')
    op.drop_index(op.f('ix_marketing_decisions_experiment_id'), table_name='marketing_decisions')
    op.drop_column('marketing_decisions', 'owner')
    op.drop_column('marketing_decisions', 'next_action')
    op.drop_column('marketing_decisions', 'based_on_evidence_ids')
    op.drop_column('marketing_decisions', 'based_on_assumption_ids')
    op.drop_column('marketing_decisions', 'question')
    op.drop_column('marketing_decisions', 'experiment_id')
    op.drop_column('marketing_decisions', 'project_id')
    op.drop_constraint(None, 'marketing_contexts', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_contexts_project_id'), table_name='marketing_contexts')
    op.drop_column('marketing_contexts', 'duration_weeks')
    op.drop_column('marketing_contexts', 'project_id')
    op.drop_constraint(None, 'marketing_campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_marketing_campaigns_project_id'), table_name='marketing_campaigns')
    op.drop_column('marketing_campaigns', 'project_id')
    op.drop_index(op.f('ix_marketing_attributions_workspace_id'), table_name='marketing_attributions')
    op.drop_index(op.f('ix_marketing_attributions_lead_id'), table_name='marketing_attributions')
    op.drop_index(op.f('ix_marketing_attributions_experiment_id'), table_name='marketing_attributions')
    op.drop_index(op.f('ix_marketing_attributions_contact_id'), table_name='marketing_attributions')
    op.drop_index(op.f('ix_marketing_attributions_campaign_id'), table_name='marketing_attributions')
    op.drop_table('marketing_attributions')
    op.drop_index(op.f('ix_tactical_execution_items_workspace_id'), table_name='tactical_execution_items')
    op.drop_index(op.f('ix_tactical_execution_items_week_number'), table_name='tactical_execution_items')
    op.drop_index(op.f('ix_tactical_execution_items_project_id'), table_name='tactical_execution_items')
    op.drop_index(op.f('ix_tactical_execution_items_cycle_id'), table_name='tactical_execution_items')
    op.drop_table('tactical_execution_items')
    op.drop_index(op.f('ix_weekly_accountability_reviews_workspace_id'), table_name='weekly_accountability_reviews')
    op.drop_index(op.f('ix_weekly_accountability_reviews_project_id'), table_name='weekly_accountability_reviews')
    op.drop_index(op.f('ix_weekly_accountability_reviews_cycle_id'), table_name='weekly_accountability_reviews')
    op.drop_table('weekly_accountability_reviews')
    op.drop_index(op.f('ix_stage_transition_audits_workspace_id'), table_name='stage_transition_audits')
    op.drop_index(op.f('ix_stage_transition_audits_project_id'), table_name='stage_transition_audits')
    op.drop_table('stage_transition_audits')
    op.drop_index(op.f('ix_premature_scaling_alerts_workspace_id'), table_name='premature_scaling_alerts')
    op.drop_index(op.f('ix_premature_scaling_alerts_project_id'), table_name='premature_scaling_alerts')
    op.drop_table('premature_scaling_alerts')
    op.drop_index(op.f('ix_knowledge_statements_workspace_id'), table_name='knowledge_statements')
    op.drop_index(op.f('ix_knowledge_statements_project_id'), table_name='knowledge_statements')
    op.drop_index(op.f('ix_knowledge_statements_epistemic_status'), table_name='knowledge_statements')
    op.drop_index(op.f('ix_knowledge_statements_brain_id'), table_name='knowledge_statements')
    op.drop_table('knowledge_statements')
    op.drop_index(op.f('ix_hypotheses_workspace_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_project_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_category'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_evidences_workspace_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_type'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_project_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_ladder_level'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_evidence_workspace_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_project_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_brain_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_customer_interviews_workspace_id'), table_name='customer_interviews')
    op.drop_index(op.f('ix_customer_interviews_project_id'), table_name='customer_interviews')
    op.drop_index(op.f('ix_customer_interviews_contact_id'), table_name='customer_interviews')
    op.drop_index(op.f('ix_customer_interviews_brain_id'), table_name='customer_interviews')
    op.drop_table('customer_interviews')
    op.drop_index(op.f('ix_canvas_revisions_workspace_id'), table_name='canvas_revisions')
    op.drop_index(op.f('ix_canvas_revisions_project_id'), table_name='canvas_revisions')
    op.drop_index(op.f('ix_canvas_revisions_canvas_type'), table_name='canvas_revisions')
    op.drop_index(op.f('ix_canvas_revisions_brain_id'), table_name='canvas_revisions')
    op.drop_table('canvas_revisions')
    op.drop_index(op.f('ix_bsc_goals_workspace_id'), table_name='bsc_goals')
    op.drop_index(op.f('ix_bsc_goals_project_id'), table_name='bsc_goals')
    op.drop_index(op.f('ix_bsc_goals_perspective'), table_name='bsc_goals')
    op.drop_table('bsc_goals')
    op.drop_index(op.f('ix_assumptions_workspace_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_status'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_project_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_criticality'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_category'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_canvas_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_brain_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_escalation_records_workspace_id'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_tier'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_status'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_run_id'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_id'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_exception_type'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_created_at'), table_name='escalation_records')
    op.drop_index(op.f('ix_escalation_records_agent_key'), table_name='escalation_records')
    op.drop_table('escalation_records')
    # ### end Alembic commands ###
