"""Sync schema with models: policy_funding/skills/tech_radar/navigation/deployments/
web_events tables, plus accumulated pending columns (agent_runs.outcome_run_id,
outcome_runs.agent_run_id/verification_*, sales UTM tracking, workspace_domains
multi-site fields). Also drops automation_callbacks/report_delivery_history/
report_automation_flows/automation_definitions/automation_runs - no model references
these table names anywhere in app/, they were superseded by the current
automations/runtime/* + agents/governance/* models.

Revision ID: v13_050_pending_schema_sync
Revises: v13_049_project_weekly_dates
Create Date: 2026-08-16 20:45:55.714792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'v13_050_pending_schema_sync'
down_revision: Union[str, Sequence[str], None] = 'v13_049_project_weekly_dates'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_policy_inboxes',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('source_title', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('extracted_summary', sa.Text(), nullable=True),
    sa.Column('extracted_data_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_memory_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=True),
    sa.Column('layer', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memory_entries_brain_id'), 'agent_memory_entries', ['brain_id'], unique=False)
    op.create_index(op.f('ix_agent_memory_entries_key'), 'agent_memory_entries', ['key'], unique=False)
    op.create_index(op.f('ix_agent_memory_entries_layer'), 'agent_memory_entries', ['layer'], unique=False)
    op.create_index(op.f('ix_agent_memory_entries_workspace_id'), 'agent_memory_entries', ['workspace_id'], unique=False)
    op.create_table('global_skill_registry',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('positive_feedback', sa.Integer(), nullable=False),
    sa.Column('negative_feedback', sa.Integer(), nullable=False),
    sa.Column('created_by_agent', sa.String(length=100), nullable=True),
    sa.Column('approved_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_skill_registry_domain'), 'global_skill_registry', ['domain'], unique=False)
    op.create_index(op.f('ix_global_skill_registry_id'), 'global_skill_registry', ['id'], unique=False)
    op.create_index(op.f('ix_global_skill_registry_name'), 'global_skill_registry', ['name'], unique=False)
    op.create_index(op.f('ix_global_skill_registry_status'), 'global_skill_registry', ['status'], unique=False)
    op.create_index(op.f('ix_global_skill_registry_workspace_id'), 'global_skill_registry', ['workspace_id'], unique=False)
    op.create_table('navigation_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('site_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_groups_site_key'), 'navigation_groups', ['site_key'], unique=False)
    op.create_index(op.f('ix_navigation_groups_workspace_id'), 'navigation_groups', ['workspace_id'], unique=False)
    op.create_table('skill_trajectory_candidates',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('mission_id', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('proposed_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_sop', sa.Text(), nullable=False),
    sa.Column('tools_used', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pii_scan_passed', sa.Boolean(), nullable=False),
    sa.Column('secret_scan_passed', sa.Boolean(), nullable=False),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('eval_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_trajectory_candidates_id'), 'skill_trajectory_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_skill_trajectory_candidates_mission_id'), 'skill_trajectory_candidates', ['mission_id'], unique=False)
    op.create_index(op.f('ix_skill_trajectory_candidates_run_id'), 'skill_trajectory_candidates', ['run_id'], unique=False)
    op.create_index(op.f('ix_skill_trajectory_candidates_workspace_id'), 'skill_trajectory_candidates', ['workspace_id'], unique=False)
    op.create_table('technology_radar_items',
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('maturity', sa.String(length=50), nullable=False),
    sa.Column('potential', sa.String(length=50), nullable=False),
    sa.Column('cosa_use', sa.String(length=50), nullable=False),
    sa.Column('integration', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_reviewed', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_radar_items_category'), 'technology_radar_items', ['category'], unique=False)
    op.create_index(op.f('ix_technology_radar_items_id'), 'technology_radar_items', ['id'], unique=False)
    op.create_index(op.f('ix_technology_radar_items_name'), 'technology_radar_items', ['name'], unique=False)
    op.create_index(op.f('ix_technology_radar_items_status'), 'technology_radar_items', ['status'], unique=False)
    op.create_index(op.f('ix_technology_radar_items_workspace_id'), 'technology_radar_items', ['workspace_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('vps_id', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('compose_yaml', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('logs_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['workspace_domains.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_domain_id'), 'deployments', ['domain_id'], unique=False)
    op.create_index(op.f('ix_deployments_workspace_id'), 'deployments', ['workspace_id'], unique=False)
    op.create_table('navigation_items',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=50), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('children_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['navigation_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_items_group_id'), 'navigation_items', ['group_id'], unique=False)
    op.create_table('policy_source_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_source_documents_brain_id'), 'policy_source_documents', ['brain_id'], unique=False)
    op.create_index(op.f('ix_policy_source_documents_workspace_id'), 'policy_source_documents', ['workspace_id'], unique=False)
    op.create_table('policy_programs',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('program_type', sa.String(length=50), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('company_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('project_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trl_min', sa.Integer(), nullable=True),
    sa.Column('industries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('funding_min', sa.Float(), nullable=True),
    sa.Column('funding_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('matching_fund_pct', sa.Float(), nullable=True),
    sa.Column('eligible_costs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.Column('matching_mode', sa.String(length=20), nullable=False),
    sa.Column('publish_to_matching', sa.Boolean(), nullable=False),
    sa.Column('source_claim', sa.Text(), nullable=True),
    sa.Column('claimed_values_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('application_window_start', sa.DateTime(), nullable=True),
    sa.Column('application_window_end', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['policy_source_documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_programs_brain_id'), 'policy_programs', ['brain_id'], unique=False)
    op.create_index(op.f('ix_policy_programs_source_document_id'), 'policy_programs', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_policy_programs_workspace_id'), 'policy_programs', ['workspace_id'], unique=False)
    op.create_table('policy_source_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('extracted_metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['policy_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_source_snapshots_source_document_id'), 'policy_source_snapshots', ['source_document_id'], unique=False)
    op.create_table('project_funding_needs',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('need_category', sa.String(length=50), nullable=False),
    sa.Column('amount_target', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('purpose_description', sa.Text(), nullable=True),
    sa.Column('co_funding_available', sa.Float(), nullable=False),
    sa.Column('co_funding_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_funding_needs_project_id'), 'project_funding_needs', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_funding_needs_workspace_id'), 'project_funding_needs', ['workspace_id'], unique=False)
    op.create_table('project_stage_assessments',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('ai_suggested_type', sa.String(length=50), nullable=True),
    sa.Column('ai_suggested_stage', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('is_founder_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stage_assessments_project_id'), 'project_stage_assessments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stage_assessments_workspace_id'), 'project_stage_assessments', ['workspace_id'], unique=False)
    op.create_table('policy_applications',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('template_version', sa.String(length=50), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=True),
    sa.Column('co_funding_amount', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_applications_brain_id'), 'policy_applications', ['brain_id'], unique=False)
    op.create_index(op.f('ix_policy_applications_program_id'), 'policy_applications', ['program_id'], unique=False)
    op.create_index(op.f('ix_policy_applications_project_id'), 'policy_applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_policy_applications_workspace_id'), 'policy_applications', ['workspace_id'], unique=False)
    op.create_table('policy_change_proposals',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_change_proposals_program_id'), 'policy_change_proposals', ['program_id'], unique=False)
    op.create_table('policy_eligibility_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_path', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('expected_value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('legal_reference', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['policy_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_eligibility_rules_program_id'), 'policy_eligibility_rules', ['program_id'], unique=False)
    op.create_table('policy_program_claims',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_key', sa.String(length=100), nullable=False),
    sa.Column('claim_value', sa.Text(), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_excerpt', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['policy_source_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_program_claims_program_id'), 'policy_program_claims', ['program_id'], unique=False)
    op.create_table('policy_program_rounds',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('round_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('budget_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_program_rounds_program_id'), 'policy_program_rounds', ['program_id'], unique=False)
    op.create_table('policy_verifications',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('official_source_url', sa.Text(), nullable=True),
    sa.Column('official_document_id', sa.BigInteger(), nullable=True),
    sa.Column('official_authority', sa.String(length=255), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('diff_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['official_document_id'], ['policy_source_documents.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_verifications_program_id'), 'policy_verifications', ['program_id'], unique=False)
    op.create_table('project_funding_awards',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('brain_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('award_name', sa.String(length=255), nullable=False),
    sa.Column('award_type', sa.String(length=50), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('cash_amount', sa.Float(), nullable=False),
    sa.Column('non_cash_value', sa.Float(), nullable=False),
    sa.Column('matching_required', sa.Float(), nullable=False),
    sa.Column('matching_actual', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('restricted_use', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brain_id'], ['brains.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_funding_awards_brain_id'), 'project_funding_awards', ['brain_id'], unique=False)
    op.create_index(op.f('ix_project_funding_awards_program_id'), 'project_funding_awards', ['program_id'], unique=False)
    op.create_index(op.f('ix_project_funding_awards_project_id'), 'project_funding_awards', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_funding_awards_workspace_id'), 'project_funding_awards', ['workspace_id'], unique=False)
    op.create_table('project_program_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('eligibility_status', sa.String(length=30), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=30), nullable=False),
    sa.Column('passed_rules_count', sa.Integer(), nullable=False),
    sa.Column('total_rules_count', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'program_id', name='uq_project_program_match')
    )
    op.create_index(op.f('ix_project_program_matches_program_id'), 'project_program_matches', ['program_id'], unique=False)
    op.create_index(op.f('ix_project_program_matches_project_id'), 'project_program_matches', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_program_matches_workspace_id'), 'project_program_matches', ['workspace_id'], unique=False)
    op.create_table('policy_application_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('section_key', sa.String(length=100), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('content_draft', sa.Text(), nullable=True),
    sa.Column('content_approved', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('missing_fields_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['policy_applications.id'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_application_sections_application_id'), 'policy_application_sections', ['application_id'], unique=False)
    op.create_table('project_cost_allocations',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('award_id', sa.BigInteger(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('work_package', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('cost_category', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['policy_applications.id'], ),
    sa.ForeignKeyConstraint(['award_id'], ['project_funding_awards.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_cost_allocations_project_id'), 'project_cost_allocations', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_cost_allocations_workspace_id'), 'project_cost_allocations', ['workspace_id'], unique=False)
    op.create_table('form_definitions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('form_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('experiment_id', sa.BigInteger(), nullable=True),
    sa.Column('schema_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submit_action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['marketing_campaigns.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['marketing_experiments.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_definitions_campaign_id'), 'form_definitions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_form_definitions_experiment_id'), 'form_definitions', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_form_definitions_form_key'), 'form_definitions', ['form_key'], unique=True)
    op.create_index(op.f('ix_form_definitions_workspace_id'), 'form_definitions', ['workspace_id'], unique=False)
    op.create_table('web_events',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('experiment_id', sa.BigInteger(), nullable=True),
    sa.Column('site_id', sa.BigInteger(), nullable=True),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('visitor_id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['marketing_experiments.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['workspace_domains.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_web_events_created_at'), 'web_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_web_events_event_type'), 'web_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_web_events_experiment_id'), 'web_events', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_web_events_session_id'), 'web_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_web_events_site_id'), 'web_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_web_events_visitor_id'), 'web_events', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_web_events_workspace_id'), 'web_events', ['workspace_id'], unique=False)
    op.create_index('ix_web_events_ws_exp_type', 'web_events', ['workspace_id', 'experiment_id', 'event_type'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('form_definition_id', sa.BigInteger(), nullable=True),
    sa.Column('form_key', sa.String(length=100), nullable=False),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['form_definition_id'], ['form_definitions.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['sales_leads.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_contact_id'), 'form_submissions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_form_definition_id'), 'form_submissions', ['form_definition_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_form_key'), 'form_submissions', ['form_key'], unique=False)
    op.create_index(op.f('ix_form_submissions_lead_id'), 'form_submissions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_form_submissions_workspace_id'), 'form_submissions', ['workspace_id'], unique=False)
    op.create_table('project_missing_requirements',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('program_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('linked_task_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['policy_programs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_missing_requirements_program_id'), 'project_missing_requirements', ['program_id'], unique=False)
    op.create_index(op.f('ix_project_missing_requirements_project_id'), 'project_missing_requirements', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_missing_requirements_workspace_id'), 'project_missing_requirements', ['workspace_id'], unique=False)
    op.create_table('project_compliance_obligations',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('award_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence_artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['project_funding_awards.id'], ),
    sa.ForeignKeyConstraint(['evidence_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_compliance_obligations_award_id'), 'project_compliance_obligations', ['award_id'], unique=False)
    op.create_index(op.f('ix_project_compliance_obligations_workspace_id'), 'project_compliance_obligations', ['workspace_id'], unique=False)
    op.create_table('project_eligibility_evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('actual_value_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('evidence_artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['project_program_matches.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['policy_eligibility_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_eligibility_evaluations_match_id'), 'project_eligibility_evaluations', ['match_id'], unique=False)
    op.create_index(op.f('ix_project_eligibility_evaluations_rule_id'), 'project_eligibility_evaluations', ['rule_id'], unique=False)
    op.create_table('project_trl_assessments',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('trl_current', sa.Integer(), nullable=False),
    sa.Column('trl_target', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('evidence_artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_trl_assessments_project_id'), 'project_trl_assessments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_trl_assessments_workspace_id'), 'project_trl_assessments', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_automation_callbacks_run_id'), table_name='automation_callbacks')
    op.drop_table('automation_callbacks')
    op.drop_index(op.f('ix_report_delivery_history_flow_id'), table_name='report_delivery_history')
    op.drop_index(op.f('ix_report_delivery_history_workspace_id'), table_name='report_delivery_history')
    op.drop_table('report_delivery_history')
    op.drop_index(op.f('ix_report_automation_flows_user_id'), table_name='report_automation_flows')
    op.drop_index(op.f('ix_report_automation_flows_workspace_id'), table_name='report_automation_flows')
    op.drop_table('report_automation_flows')
    op.drop_index(op.f('ix_automation_definitions_automation_key'), table_name='automation_definitions')
    op.drop_table('automation_definitions')
    op.drop_index(op.f('ix_automation_runs_agent_run_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_approval_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_automation_key'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_company_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_provider_execution_id'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_workspace_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.create_index(op.f('ix_agent_approvals_id'), 'agent_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_agent_business_memories_id'), 'agent_business_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_events_id'), 'agent_events', ['id'], unique=False)
    op.create_index(op.f('ix_agent_goals_id'), 'agent_goals', ['id'], unique=False)
    op.create_index(op.f('ix_agent_plan_steps_id'), 'agent_plan_steps', ['id'], unique=False)
    op.create_index(op.f('ix_agent_plans_id'), 'agent_plans', ['id'], unique=False)
    op.add_column('agent_proposals', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('agent_proposals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_agent_proposals_id'), 'agent_proposals', ['id'], unique=False)
    op.add_column('agent_runs', sa.Column('outcome_run_id', sa.BigInteger(), nullable=True))
    op.add_column('agent_runs', sa.Column('budget_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_outcome_run_id'), 'agent_runs', ['outcome_run_id'], unique=False)
    op.create_foreign_key(None, 'agent_runs', 'outcome_runs', ['outcome_run_id'], ['id'], use_alter=True)
    op.alter_column('agent_tool_calls', 'run_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_index(op.f('ix_agent_tool_calls_id'), 'agent_tool_calls', ['id'], unique=False)
    op.create_index(op.f('ix_capability_grants_id'), 'capability_grants', ['id'], unique=False)
    op.create_index(op.f('ix_execution_jobs_id'), 'execution_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_execution_steps_id'), 'execution_steps', ['id'], unique=False)
    op.create_index(op.f('ix_job_outcomes_id'), 'job_outcomes', ['id'], unique=False)
    op.add_column('marketing_experiments', sa.Column('landing_url', sa.String(length=500), nullable=True))
    op.add_column('marketing_experiments', sa.Column('variant_a_url', sa.String(length=500), nullable=True))
    op.add_column('marketing_experiments', sa.Column('variant_b_url', sa.String(length=500), nullable=True))
    op.add_column('outcome_runs', sa.Column('agent_run_id', sa.BigInteger(), nullable=True))
    op.add_column('outcome_runs', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('outcome_runs', sa.Column('verification_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_outcome_runs_agent_run_id'), 'outcome_runs', ['agent_run_id'], unique=False)
    op.create_foreign_key(None, 'outcome_runs', 'agent_runs', ['agent_run_id'], ['id'], use_alter=True)
    op.create_index(op.f('ix_protected_resource_revisions_id'), 'protected_resource_revisions', ['id'], unique=False)
    op.create_index(op.f('ix_protected_resources_id'), 'protected_resources', ['id'], unique=False)
    op.drop_constraint(op.f('uq_runtime_heartbeats_component'), 'runtime_heartbeats', type_='unique')
    op.drop_index(op.f('ix_runtime_heartbeats_component'), table_name='runtime_heartbeats')
    op.create_index(op.f('ix_runtime_heartbeats_component'), 'runtime_heartbeats', ['component'], unique=True)
    op.add_column('sales_leads', sa.Column('source_experiment_id', sa.BigInteger(), nullable=True))
    op.add_column('sales_leads', sa.Column('utm_source', sa.String(length=100), nullable=True))
    op.add_column('sales_leads', sa.Column('utm_medium', sa.String(length=100), nullable=True))
    op.add_column('sales_leads', sa.Column('utm_campaign', sa.String(length=100), nullable=True))
    op.add_column('sales_leads', sa.Column('utm_content', sa.String(length=255), nullable=True))
    op.add_column('sales_leads', sa.Column('utm_term', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'sales_leads', 'marketing_experiments', ['source_experiment_id'], ['id'])
    op.create_index(op.f('ix_sandbox_policies_id'), 'sandbox_policies', ['id'], unique=False)
    op.create_index(op.f('ix_twelve_week_cycles_project_id'), 'twelve_week_cycles', ['project_id'], unique=False)
    op.add_column('workspace_domains', sa.Column('subdomain', sa.String(length=100), nullable=True))
    op.add_column('workspace_domains', sa.Column('site_type', sa.String(length=50), nullable=False))
    op.add_column('workspace_domains', sa.Column('environment', sa.String(length=50), nullable=False))
    op.add_column('workspace_domains', sa.Column('deployment_id', sa.BigInteger(), nullable=True))
    op.add_column('workspace_domains', sa.Column('navigation_group_id', sa.BigInteger(), nullable=True))
    op.add_column('workspace_domains', sa.Column('site_title', sa.String(length=255), nullable=True))
    op.add_column('workspace_domains', sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_workspace_domains_deployment_id'), 'workspace_domains', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_workspace_domains_navigation_group_id'), 'workspace_domains', ['navigation_group_id'], unique=False)
    op.create_index(op.f('ix_workspace_domains_subdomain'), 'workspace_domains', ['subdomain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_domains_subdomain'), table_name='workspace_domains')
    op.drop_index(op.f('ix_workspace_domains_navigation_group_id'), table_name='workspace_domains')
    op.drop_index(op.f('ix_workspace_domains_deployment_id'), table_name='workspace_domains')
    op.drop_column('workspace_domains', 'metadata_jsonb')
    op.drop_column('workspace_domains', 'site_title')
    op.drop_column('workspace_domains', 'navigation_group_id')
    op.drop_column('workspace_domains', 'deployment_id')
    op.drop_column('workspace_domains', 'environment')
    op.drop_column('workspace_domains', 'site_type')
    op.drop_column('workspace_domains', 'subdomain')
    op.drop_index(op.f('ix_twelve_week_cycles_project_id'), table_name='twelve_week_cycles')
    op.drop_index(op.f('ix_sandbox_policies_id'), table_name='sandbox_policies')
    op.drop_constraint(None, 'sales_leads', type_='foreignkey')
    op.drop_column('sales_leads', 'utm_term')
    op.drop_column('sales_leads', 'utm_content')
    op.drop_column('sales_leads', 'utm_campaign')
    op.drop_column('sales_leads', 'utm_medium')
    op.drop_column('sales_leads', 'utm_source')
    op.drop_column('sales_leads', 'source_experiment_id')
    op.drop_index(op.f('ix_runtime_heartbeats_component'), table_name='runtime_heartbeats')
    op.create_index(op.f('ix_runtime_heartbeats_component'), 'runtime_heartbeats', ['component'], unique=False)
    op.create_unique_constraint(op.f('uq_runtime_heartbeats_component'), 'runtime_heartbeats', ['component'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_protected_resources_id'), table_name='protected_resources')
    op.drop_index(op.f('ix_protected_resource_revisions_id'), table_name='protected_resource_revisions')
    op.drop_constraint(None, 'outcome_runs', type_='foreignkey')
    op.drop_index(op.f('ix_outcome_runs_agent_run_id'), table_name='outcome_runs')
    op.drop_column('outcome_runs', 'verification_jsonb')
    op.drop_column('outcome_runs', 'verification_status')
    op.drop_column('outcome_runs', 'agent_run_id')
    op.drop_column('marketing_experiments', 'variant_b_url')
    op.drop_column('marketing_experiments', 'variant_a_url')
    op.drop_column('marketing_experiments', 'landing_url')
    op.drop_index(op.f('ix_job_outcomes_id'), table_name='job_outcomes')
    op.drop_index(op.f('ix_execution_steps_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_jobs_id'), table_name='execution_jobs')
    op.drop_index(op.f('ix_capability_grants_id'), table_name='capability_grants')
    op.drop_index(op.f('ix_agent_tool_calls_id'), table_name='agent_tool_calls')
    op.alter_column('agent_tool_calls', 'run_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_index(op.f('ix_agent_runs_outcome_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_column('agent_runs', 'budget_jsonb')
    op.drop_column('agent_runs', 'outcome_run_id')
    op.drop_index(op.f('ix_agent_proposals_id'), table_name='agent_proposals')
    op.drop_column('agent_proposals', 'updated_at')
    op.drop_column('agent_proposals', 'created_at')
    op.drop_index(op.f('ix_agent_plans_id'), table_name='agent_plans')
    op.drop_index(op.f('ix_agent_plan_steps_id'), table_name='agent_plan_steps')
    op.drop_index(op.f('ix_agent_goals_id'), table_name='agent_goals')
    op.drop_index(op.f('ix_agent_events_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_business_memories_id'), table_name='agent_business_memories')
    op.drop_index(op.f('ix_agent_approvals_id'), table_name='agent_approvals')
    op.create_table('automation_runs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('automation_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), server_default=sa.text("'n8n'::character varying"), autoincrement=False, nullable=False),
    sa.Column('provider_execution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('agent_run_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('approval_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'running'::character varying"), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=20), server_default=sa.text("'low'::character varying"), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('error_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('automation_runs_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_runs_pkey')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_automation_runs_idempotency_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_automation_runs_workspace_id'), 'automation_runs', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_provider_execution_id'), 'automation_runs', ['provider_execution_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_company_id'), 'automation_runs', ['company_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_automation_key'), 'automation_runs', ['automation_key'], unique=False)
    op.create_index(op.f('ix_automation_runs_approval_id'), 'automation_runs', ['approval_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_agent_run_id'), 'automation_runs', ['agent_run_id'], unique=False)
    op.create_table('automation_definitions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('automation_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), server_default=sa.text("'n8n'::character varying"), autoincrement=False, nullable=False),
    sa.Column('provider_workflow_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=20), server_default=sa.text("'low'::character varying"), autoincrement=False, nullable=False),
    sa.Column('approval_mode', sa.VARCHAR(length=50), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False),
    sa.Column('input_schema_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('output_schema_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_definitions_pkey')),
    sa.UniqueConstraint('automation_key', name=op.f('uq_automation_definitions_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_automation_definitions_automation_key'), 'automation_definitions', ['automation_key'], unique=True)
    op.create_table('report_automation_flows',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), server_default=sa.text("'cron'::character varying"), autoincrement=False, nullable=False),
    sa.Column('schedule_cron', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Asia/Ho_Chi_Minh'::character varying"), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(length=50), server_default=sa.text("'cycle'::character varying"), autoincrement=False, nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('report_automation_flows_user_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('report_automation_flows_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('report_automation_flows_pkey'))
    )
    op.create_index(op.f('ix_report_automation_flows_workspace_id'), 'report_automation_flows', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_report_automation_flows_user_id'), 'report_automation_flows', ['user_id'], unique=False)
    op.create_table('report_delivery_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('flow_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'delivered'::character varying"), autoincrement=False, nullable=False),
    sa.Column('delivered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('summary_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload_snapshot_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['report_automation_flows.id'], name=op.f('report_delivery_history_flow_id_fkey')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('report_delivery_history_workspace_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('report_delivery_history_pkey'))
    )
    op.create_index(op.f('ix_report_delivery_history_workspace_id'), 'report_delivery_history', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_report_delivery_history_flow_id'), 'report_delivery_history', ['flow_id'], unique=False)
    op.create_table('automation_callbacks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('provider_execution_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('signature', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('payload_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], name=op.f('automation_callbacks_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('automation_callbacks_pkey'))
    )
    op.create_index(op.f('ix_automation_callbacks_run_id'), 'automation_callbacks', ['run_id'], unique=False)
    op.drop_index(op.f('ix_project_trl_assessments_workspace_id'), table_name='project_trl_assessments')
    op.drop_index(op.f('ix_project_trl_assessments_project_id'), table_name='project_trl_assessments')
    op.drop_table('project_trl_assessments')
    op.drop_index(op.f('ix_project_eligibility_evaluations_rule_id'), table_name='project_eligibility_evaluations')
    op.drop_index(op.f('ix_project_eligibility_evaluations_match_id'), table_name='project_eligibility_evaluations')
    op.drop_table('project_eligibility_evaluations')
    op.drop_index(op.f('ix_project_compliance_obligations_workspace_id'), table_name='project_compliance_obligations')
    op.drop_index(op.f('ix_project_compliance_obligations_award_id'), table_name='project_compliance_obligations')
    op.drop_table('project_compliance_obligations')
    op.drop_index(op.f('ix_project_missing_requirements_workspace_id'), table_name='project_missing_requirements')
    op.drop_index(op.f('ix_project_missing_requirements_project_id'), table_name='project_missing_requirements')
    op.drop_index(op.f('ix_project_missing_requirements_program_id'), table_name='project_missing_requirements')
    op.drop_table('project_missing_requirements')
    op.drop_index(op.f('ix_form_submissions_workspace_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_lead_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_key'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_form_definition_id'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_contact_id'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index('ix_web_events_ws_exp_type', table_name='web_events')
    op.drop_index(op.f('ix_web_events_workspace_id'), table_name='web_events')
    op.drop_index(op.f('ix_web_events_visitor_id'), table_name='web_events')
    op.drop_index(op.f('ix_web_events_site_id'), table_name='web_events')
    op.drop_index(op.f('ix_web_events_session_id'), table_name='web_events')
    op.drop_index(op.f('ix_web_events_experiment_id'), table_name='web_events')
    op.drop_index(op.f('ix_web_events_event_type'), table_name='web_events')
    op.drop_index(op.f('ix_web_events_created_at'), table_name='web_events')
    op.drop_table('web_events')
    op.drop_index(op.f('ix_form_definitions_workspace_id'), table_name='form_definitions')
    op.drop_index(op.f('ix_form_definitions_form_key'), table_name='form_definitions')
    op.drop_index(op.f('ix_form_definitions_experiment_id'), table_name='form_definitions')
    op.drop_index(op.f('ix_form_definitions_campaign_id'), table_name='form_definitions')
    op.drop_table('form_definitions')
    op.drop_index(op.f('ix_project_cost_allocations_workspace_id'), table_name='project_cost_allocations')
    op.drop_index(op.f('ix_project_cost_allocations_project_id'), table_name='project_cost_allocations')
    op.drop_table('project_cost_allocations')
    op.drop_index(op.f('ix_policy_application_sections_application_id'), table_name='policy_application_sections')
    op.drop_table('policy_application_sections')
    op.drop_index(op.f('ix_project_program_matches_workspace_id'), table_name='project_program_matches')
    op.drop_index(op.f('ix_project_program_matches_project_id'), table_name='project_program_matches')
    op.drop_index(op.f('ix_project_program_matches_program_id'), table_name='project_program_matches')
    op.drop_table('project_program_matches')
    op.drop_index(op.f('ix_project_funding_awards_workspace_id'), table_name='project_funding_awards')
    op.drop_index(op.f('ix_project_funding_awards_project_id'), table_name='project_funding_awards')
    op.drop_index(op.f('ix_project_funding_awards_program_id'), table_name='project_funding_awards')
    op.drop_index(op.f('ix_project_funding_awards_brain_id'), table_name='project_funding_awards')
    op.drop_table('project_funding_awards')
    op.drop_index(op.f('ix_policy_verifications_program_id'), table_name='policy_verifications')
    op.drop_table('policy_verifications')
    op.drop_index(op.f('ix_policy_program_rounds_program_id'), table_name='policy_program_rounds')
    op.drop_table('policy_program_rounds')
    op.drop_index(op.f('ix_policy_program_claims_program_id'), table_name='policy_program_claims')
    op.drop_table('policy_program_claims')
    op.drop_index(op.f('ix_policy_eligibility_rules_program_id'), table_name='policy_eligibility_rules')
    op.drop_table('policy_eligibility_rules')
    op.drop_index(op.f('ix_policy_change_proposals_program_id'), table_name='policy_change_proposals')
    op.drop_table('policy_change_proposals')
    op.drop_index(op.f('ix_policy_applications_workspace_id'), table_name='policy_applications')
    op.drop_index(op.f('ix_policy_applications_project_id'), table_name='policy_applications')
    op.drop_index(op.f('ix_policy_applications_program_id'), table_name='policy_applications')
    op.drop_index(op.f('ix_policy_applications_brain_id'), table_name='policy_applications')
    op.drop_table('policy_applications')
    op.drop_index(op.f('ix_project_stage_assessments_workspace_id'), table_name='project_stage_assessments')
    op.drop_index(op.f('ix_project_stage_assessments_project_id'), table_name='project_stage_assessments')
    op.drop_table('project_stage_assessments')
    op.drop_index(op.f('ix_project_funding_needs_workspace_id'), table_name='project_funding_needs')
    op.drop_index(op.f('ix_project_funding_needs_project_id'), table_name='project_funding_needs')
    op.drop_table('project_funding_needs')
    op.drop_index(op.f('ix_policy_source_snapshots_source_document_id'), table_name='policy_source_snapshots')
    op.drop_table('policy_source_snapshots')
    op.drop_index(op.f('ix_policy_programs_workspace_id'), table_name='policy_programs')
    op.drop_index(op.f('ix_policy_programs_source_document_id'), table_name='policy_programs')
    op.drop_index(op.f('ix_policy_programs_brain_id'), table_name='policy_programs')
    op.drop_table('policy_programs')
    op.drop_index(op.f('ix_policy_source_documents_workspace_id'), table_name='policy_source_documents')
    op.drop_index(op.f('ix_policy_source_documents_brain_id'), table_name='policy_source_documents')
    op.drop_table('policy_source_documents')
    op.drop_index(op.f('ix_navigation_items_group_id'), table_name='navigation_items')
    op.drop_table('navigation_items')
    op.drop_index(op.f('ix_deployments_workspace_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_domain_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_technology_radar_items_workspace_id'), table_name='technology_radar_items')
    op.drop_index(op.f('ix_technology_radar_items_status'), table_name='technology_radar_items')
    op.drop_index(op.f('ix_technology_radar_items_name'), table_name='technology_radar_items')
    op.drop_index(op.f('ix_technology_radar_items_id'), table_name='technology_radar_items')
    op.drop_index(op.f('ix_technology_radar_items_category'), table_name='technology_radar_items')
    op.drop_table('technology_radar_items')
    op.drop_index(op.f('ix_skill_trajectory_candidates_workspace_id'), table_name='skill_trajectory_candidates')
    op.drop_index(op.f('ix_skill_trajectory_candidates_run_id'), table_name='skill_trajectory_candidates')
    op.drop_index(op.f('ix_skill_trajectory_candidates_mission_id'), table_name='skill_trajectory_candidates')
    op.drop_index(op.f('ix_skill_trajectory_candidates_id'), table_name='skill_trajectory_candidates')
    op.drop_table('skill_trajectory_candidates')
    op.drop_index(op.f('ix_navigation_groups_workspace_id'), table_name='navigation_groups')
    op.drop_index(op.f('ix_navigation_groups_site_key'), table_name='navigation_groups')
    op.drop_table('navigation_groups')
    op.drop_index(op.f('ix_global_skill_registry_workspace_id'), table_name='global_skill_registry')
    op.drop_index(op.f('ix_global_skill_registry_status'), table_name='global_skill_registry')
    op.drop_index(op.f('ix_global_skill_registry_name'), table_name='global_skill_registry')
    op.drop_index(op.f('ix_global_skill_registry_id'), table_name='global_skill_registry')
    op.drop_index(op.f('ix_global_skill_registry_domain'), table_name='global_skill_registry')
    op.drop_table('global_skill_registry')
    op.drop_index(op.f('ix_agent_memory_entries_workspace_id'), table_name='agent_memory_entries')
    op.drop_index(op.f('ix_agent_memory_entries_layer'), table_name='agent_memory_entries')
    op.drop_index(op.f('ix_agent_memory_entries_key'), table_name='agent_memory_entries')
    op.drop_index(op.f('ix_agent_memory_entries_brain_id'), table_name='agent_memory_entries')
    op.drop_table('agent_memory_entries')
    op.drop_table('admin_policy_inboxes')
    # ### end Alembic commands ###
