"""add install_credentials table

Revision ID: 364cffc3b459
Revises: c9a1f0b2e3d4
Create Date: 2026-08-21 18:38:21.434478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364cffc3b459'
down_revision: Union[str, Sequence[str], None] = 'c9a1f0b2e3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('install_credentials',
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['control_plane.companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='control_plane'
    )
    op.create_index('ix_install_credentials_company', 'install_credentials', ['company_id'], unique=False, schema='control_plane')
    op.create_index(op.f('ix_install_credentials_id'), 'install_credentials', ['id'], unique=False, schema='control_plane')
    op.create_index('ix_install_credentials_token_hash', 'install_credentials', ['token_hash'], unique=False, schema='control_plane')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_install_credentials_token_hash', table_name='install_credentials', schema='control_plane')
    op.drop_index(op.f('ix_install_credentials_id'), table_name='install_credentials', schema='control_plane')
    op.drop_index('ix_install_credentials_company', table_name='install_credentials', schema='control_plane')
    op.drop_table('install_credentials', schema='control_plane')
    # ### end Alembic commands ###
