"""Service for Agent Proposal lifecycle and applying proposals to real OKRs and Tasks."""

from datetime import datetime, timezone
from copy import deepcopy
import logging
from typing import Any, Optional
from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.agents.proposals.models import AgentProposal
from app.agents.proposals.command import parse_proposal_command
from app.core.snowflake import generate_snowflake_id
from app.modules.strategy.models import OkrCycle, OkrObjective, Project
from app.modules.strategy.project_orchestration_service import ProjectOrchestrationService
from app.modules.strategy.routing_service import RoutingService
from app.modules.tasks.models import Task
from app.modules.vault.models import Brain

logger = logging.getLogger(__name__)


class AgentProposalService:
    """Manages creation, review, and application of proposals generated by AI agents."""

    @staticmethod
    def create_proposal(
        db: Session,
        workspace_id: int,
        proposal_type: str,
        title: str,
        payload: dict[str, Any],
        description: Optional[str] = None,
        agent_key: str = "chief_of_staff",
        company_id: Optional[int] = None,
        run_id: Optional[int] = None,
    ) -> AgentProposal:
        now = datetime.now(timezone.utc)
        proposal = AgentProposal(
            id=generate_snowflake_id(),
            workspace_id=workspace_id,
            company_id=company_id or workspace_id,
            run_id=run_id,
            proposal_type=proposal_type,
            created_by_agent=agent_key,
            title=title,
            description=description,
            payload_jsonb=AgentProposalService._validated_payload(payload),
            status="pending",
            created_at=now,
            updated_at=now,
        )
        db.add(proposal)
        db.commit()
        db.refresh(proposal)
        return proposal

    @staticmethod
    def _validated_payload(payload: dict[str, Any]) -> dict[str, Any]:
        """Validate the executable command while retaining the full payload."""
        command = parse_proposal_command(payload)
        validated_payload = deepcopy(payload)
        validated_payload["command"] = command.model_dump(mode="json")
        return validated_payload

    @staticmethod
    def list_proposals(
        db: Session,
        workspace_id: int,
        status_filter: Optional[str] = None,
    ) -> list[AgentProposal]:
        query = db.query(AgentProposal).filter(AgentProposal.workspace_id == workspace_id)
        if status_filter:
            query = query.filter(AgentProposal.status == status_filter)
        return query.order_by(AgentProposal.created_at.desc()).all()

    @staticmethod
    def get_proposal(
        db: Session,
        workspace_id: int,
        proposal_id: int,
    ) -> Optional[AgentProposal]:
        return (
            db.query(AgentProposal)
            .filter(
                AgentProposal.id == proposal_id,
                AgentProposal.workspace_id == workspace_id,
            )
            .first()
        )

    @staticmethod
    def review_proposal(
        db: Session,
        workspace_id: int,
        proposal_id: int,
        reviewed_by: int,
        action: str,  # "approve", "reject"
        rejection_reason: Optional[str] = None,
    ) -> AgentProposal:
        proposal = AgentProposalService.get_proposal(db, workspace_id, proposal_id)
        if not proposal:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Agent proposal '{proposal_id}' not found in workspace",
            )

        if action == "approve":
            proposal.status = "approved"
        elif action == "reject":
            proposal.status = "rejected"
            proposal.rejection_reason = rejection_reason
        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid review action '{action}', must be 'approve' or 'reject'",
            )

        proposal.reviewed_by = reviewed_by
        proposal.reviewed_at = datetime.now(timezone.utc)
        proposal.updated_at = datetime.now(timezone.utc)

        db.commit()
        db.refresh(proposal)
        return proposal

    @staticmethod
    def apply_proposal(
        db: Session,
        workspace_id: int,
        proposal_id: int,
        reviewed_by: int,
    ) -> dict[str, Any]:
        proposal = AgentProposalService.get_proposal(db, workspace_id, proposal_id)
        if not proposal:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Agent proposal '{proposal_id}' not found in workspace",
            )

        if proposal.status == "applied":
            return {
                "status": "applied",
                "proposal_id": str(proposal.id),
                "resource_type": proposal.proposal_type,
                "resource_id": proposal.applied_resource_id,
                "message": "Proposal has already been applied",
            }

        if proposal.status == "rejected":
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Cannot apply a rejected proposal",
            )

        payload = proposal.payload_jsonb or {}
        applied_res_id = None

        if proposal.proposal_type == "okr_objective":
            target_cycle_id = payload.get("cycle_id")
            if not target_cycle_id:
                active_cycle = (
                    db.query(OkrCycle)
                    .filter(OkrCycle.workspace_id == workspace_id)
                    .order_by(OkrCycle.created_at.desc())
                    .first()
                )
                if active_cycle:
                    target_cycle_id = active_cycle.id
                else:
                    brain = db.query(Brain).filter(Brain.workspace_id == workspace_id).first()
                    new_cycle = OkrCycle(
                        id=generate_snowflake_id(),
                        workspace_id=workspace_id,
                        brain_id=brain.id if brain else generate_snowflake_id(),
                        name="Q1 Annual Cycle",
                        status="active",
                    )
                    db.add(new_cycle)
                    db.flush()
                    target_cycle_id = new_cycle.id

            obj = OkrObjective(
                id=generate_snowflake_id(),
                workspace_id=workspace_id,
                cycle_id=target_cycle_id,
                title=payload.get("title", proposal.title),
                why=payload.get("why") or payload.get("description", proposal.description),
                owner_id=payload.get("owner_id", reviewed_by),
                status=payload.get("status", "draft"),
            )
            db.add(obj)
            db.flush()
            applied_res_id = str(obj.id)

        elif proposal.proposal_type == "strategy_task":
            task = Task(
                id=generate_snowflake_id(),
                workspace_id=workspace_id,
                title=payload.get("title", proposal.title),
                status=payload.get("status", "TODO"),
                priority=payload.get("priority", "MEDIUM"),
                assignee_id=payload.get("assignee_id", reviewed_by),
                source="agent_proposal",
            )
            db.add(task)
            db.flush()
            applied_res_id = str(task.id)

        elif proposal.proposal_type == "project_cycle":
            arguments = payload.get("command", {}).get("arguments", {})
            desired_week_count = int(arguments.get("desired_week_count") or 12)
            # applied_resource_id ưu tiên hơn arguments: nếu một lần apply trước đã tạo
            # Project rồi hỏng ở bước roadmap/plan (AI trả JSON không hợp lệ), lần apply
            # lại sau phải nối vào đúng Project đó, không tạo trùng.
            existing_project_id = proposal.applied_resource_id or arguments.get("existing_project_id")

            brain = db.query(Brain).filter(Brain.workspace_id == workspace_id).first()
            if not brain:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail="Workspace chưa có Brain, không thể tạo Project",
                )

            if existing_project_id:
                project_id = int(existing_project_id)
            else:
                project = Project(
                    id=generate_snowflake_id(),
                    workspace_id=workspace_id,
                    brain_id=brain.id,
                    title=arguments.get("title") or proposal.title,
                    description=arguments.get("description") or proposal.description,
                )
                db.add(project)
                db.commit()
                project_id = project.id
                proposal.applied_resource_id = str(project_id)
                db.commit()

            orchestration = ProjectOrchestrationService(db, workspace_id, brain.id, reviewed_by)
            routing = RoutingService(db, workspace_id, brain.id, reviewed_by)

            draft = orchestration.generate_roadmap(project_id)
            orchestration.save_roadmap_draft(project_id, draft)
            stages = orchestration.confirm_roadmap(project_id)
            first_stage = next(s for s in stages if s.sequence_no == 1)
            plan_draft = routing.plan_stage(first_stage.id, desired_weeks=desired_week_count)
            orchestration.activate_stage(project_id, first_stage.id, plan_draft)
            applied_res_id = str(project_id)

        else:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Unsupported proposal type '{proposal.proposal_type}'",
            )

        now = datetime.now(timezone.utc)
        proposal.status = "applied"
        proposal.reviewed_by = reviewed_by
        proposal.reviewed_at = now
        proposal.applied_resource_id = applied_res_id
        proposal.updated_at = now

        db.commit()
        db.refresh(proposal)

        return {
            "status": "applied",
            "proposal_id": str(proposal.id),
            "resource_type": proposal.proposal_type,
            "resource_id": applied_res_id,
        }
